(function(contentstree){
	contentstree.demo_template=_.template(
		[
'			<li id=<%=id%> class="tree-item">',
'               <div class="wraparea">',
 '              		<h4><a href="#"><%=title%></a></h4>',
 '						<div class="hitarea"></div>',
  // '             		<div class="share">',
   // '            			<a rel="tooltip" href="#" data-original-title="共享信息">共享信息</a>',
   // '            		</div>',
 '              </div>',
'            </li>',
		].join("")
	);
	contentstree.template=_.template(
		[
'			<li id=<%=id%> <%=(!_.isEmpty(children)||type=="Column")&&"class=\'hasmenu unfold\'"%>>',
'               <div class="wraparea">',
 '              		<h4><a href="#"><%=title%></a></h4>',
 '						<div class="hitarea"></div>',
 '              		<% if(!_.isEmpty(actions)){ %>',
 '              		<div class="action-new">',
 '              			<a href="javascript:void(0)">新建</a>',
 '              			<ul style="top: 20px; display: none;">',
 '              				<% _.each(actions,function(action){ %>',
 '              				<li><a target="_blank" href=<%=portal_url+"createfactory?Type="+action.id+"&id="+id%>><%=action.title%></a></li>',
 '              				<%   }) %>',
//'               				<li class="divider"></li>',
// '              				<li><a href="#lib">引入内容</a></li>',
 '              			</ul>',
 '              		</div>',
 '              		<% } %>',
 '              		<% if(type=="Column"){ %>',
 '              		<div class="platform">',
 '              			<ul>',
 '              				<% if(_.include(channels.values,"web")) {%><li rel="tooltip" class="platform-web" data-original-title="Web">Web</li><% } %>',
 '              				<% if(_.include(channels.values,"ipad")) {%><li rel="tooltip" class="platform-ipad" data-original-title="iPad">iPad</li><% } %>',
 '              			</ul>',
 '              		</div>',
 '              		<% } %>',
  // '             		<div class="share">',
   // '            			<a rel="tooltip" href="#" data-original-title="共享信息">共享信息</a>',
   // '            		</div>',
 '              </div>',
'            </li>',
		].join("")
	);
	contentstree.empty_list_template=_.template(
		[
	  '  <li class="content-item empty">',
 '	        <div class="wraparea">',
 '	        	<h4><空></h4>',
 '	        	<div rel="tooltip" class="btn-draged" data-original-title="上下拖拽">',
 '	        	</div>',
	   '    </div>',
	 '   </li>',
		].join("")
	);
	contentstree.list_template=_.template(
		[
	  '  <li class="content-item" data-type=<%=type%> id=<%=id%>>',
 '	        <div class="wraparea <%=review_state%> <%=type.toLowerCase()%>">',
 '	        	<h4><%=title%></h4>',
 '				<div class="hitarea"></div>',
 '	        	<div rel="tooltip" class="btn-draged" data-original-title="上下拖拽">',
 '	        	</div>',
 '	        	<div class="action-pub <%=review_state%>">',
	 '        		<a class="action-publish" href="#" data-original-title="">操作</a>',
	  '       	</div>',
	   '      	<div class="action">',
	    '     		<ul>',
 '	        			<li><a class="action-edit" href="<%if(type=="Column"){%><%=url%>/edit<%}%>">编辑</a></li>',
' 						<% if(type=="Column"||type=="Category"){ %>',
	 '        			<li class="action-new"><a href="javascript:void(0)">+ 追加</a>',
	   '      				<ul>',
	  '       					<li><a href="#" class="action-addCategory">添加子分类</a></li>',
	   '      					<li><a class="action-addLink" href="#">新建链接</a></li>',
	    '     					<li><a class="action-lib" href="#">引入内容</a></li>',
	      '   					<li><a class="action-category" href="#">引入分类</a></li>',
	         '				</ul>',
	        	 '		</li>',
'	        	 		<% } %>',
	      '  	 		<li><a href="#confirmModal" class="action-delete">删除</a></li>',
	        	 '	</ul>',
	     '    	</div>',
 '              		<% if(type=="Column"){ %>',
 '              		<div class="platform">',
 '              			<ul>',
 '              				<% if(_.include(channels.values,"web")) {%><li rel="tooltip" class="platform-web" data-original-title="Web">Web</li><% } %>',
 '              				<% if(_.include(channels.values,"ipad")) {%><li rel="tooltip" class="platform-ipad" data-original-title="iPad">iPad</li><% } %>',
 '              			</ul>',
 '              		</div>',
 '              		<% } %>',
	   '      </div>',
	 '   </li>',
		].join("")
	);
	contentstree.lib_template=_.template(
		[
'                <li class="content-item" data-type=<%=type%> id=<%=id%>>',
'                  <div class="wraparea content"><h4>',
 '                   <input type="checkbox" name="category-item" value=<%=id%> <%=(type!="Category")&&"disabled"%>>',
  '                  <%=title%></h4></div>',
   '             </li>',
		].join("")
	);
	contentstree.edit_template=_.template(
		[
'		  <div class="modal-header">',
'		    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>',
'		    <h3>新建／编辑分类名称</h3>',
'		  </div>',
'		    <form class="form-horizontal" onsubmit="javascript:return false;">',
'		  <div class="modal-body">',
'		      <div class="control-group">',
'		        <label class="control-label" for="title"><em>*</em> 标题：</label>',
'		        <div class="controls">',
'		          <input type="text" id="title" name="title" value="<%=title%>">',
'		          <input type="hidden" id="id" name="id" value="<%=id%>">',
'		          <input type="hidden" id="thumbnail" name="thumbnail" value="<%=thumbnail%>">',
'		          <input type="hidden" id="picture" name="picture" value="<%=picture%>">',
'		          <input type="hidden" id="type" name="type" value="<%=type%>">',
'		        </div>',
'		      </div>',
'		      <div class="control-group thumb">',
'		        <label class="control-label">缩略图：</label>',
'		        <div class="controls">',
'		          <div class="action">',
'		            <a class="btn btn-small action-change" type="button">设置</a>',
'		            <!--<input name="" type="file">--> ',
'		          </div>',
'		          <div class="cover"><img src="<%=thumbnail%>" alt=""></div>',
'		        </div>',
'		      </div>',
'		      <div class="control-group">',
'		        <label class="control-label" for="description">描述：</label>',
'		        <div class="controls">',
'		          <textarea rows="4" name="description" id="description"><%=description%></textarea>',
'		        </div>',
'		      </div>',
'		  </div>',
'		  <div class="modal-footer">',
'		    <button class="btn">确定</button>',
'		  </div>',
'		    </form>',
		 ].join("")
	);
	contentstree.link_template=_.template(
		[
'		  <div class="modal-header">',
'		    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>',
'		    <h3>新建／编辑链接</h3>',
'		  </div>',
'		  <div class="modal-body">',
'		    <form class="form-horizontal">',
'		      <div class="control-group">',
'		        <label class="control-label" for="title"><em>*</em> 显示名称：</label>',
'		        <div class="controls">',
'		          <input type="text" id="title" name="title" value="<%=title%>">',
'		          <input type="hidden" id="id" name="id" value="<%=id%>">',
'		          <input type="hidden" id="thumbnail" name="thumbnail" value="<%=thumbnail%>">',
'		          <input type="hidden" id="picture" name="picture" value="<%=picture%>">',
'		          <input type="hidden" id="type" name="type" value="<%=type%>">',
'		        </div>',
'		      </div>',
'		      <div class="control-group">',
'		        <label class="control-label" for="href"><em>*</em> 链接：</label>',
'		        <div class="controls">',
'		          <input name="href" id="href" value=<%=href%>>',
'		        </div>',
'		      </div>',
'		      <div class="control-group thumb">',
'		        <label class="control-label">缩略图：</label>',
'		        <div class="controls">',
'		          <div class="action">',
'		            <a class="btn btn-small action-change" type="button">设置</a>',
'		            <!--<input name="" type="file">--> ',
'		          </div>',
'		          <div class="cover"><img src="<%=thumbnail%>" alt=""></div>',
'		        </div>',
'		      </div>',
'		    </form>',
'		  </div>',
'		  <div class="modal-footer">',
'		    <button class="btn">确定</button>',
'		  </div>',
		 ].join("")
	);
	contentstree.modal_template=_.template(
		[
'	  <div class="modal-header">',
'	    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>',
'	    <h3>资源库</h3>',
//'	    <button class="btn btn-small btn-primary action-copy" type="button">复制所选</button>',
'	    <button class="btn btn-small btn-primary action-quote-units action-quote" type="button">引用所选</button>',
'	    <form class="search" style="position:absolute; left:auto; right:20px; top:5px;">',
'	      <input type="text" placeholder="搜索" class="input-medium search-query">',
'	      <button class="btn" type="submit"><i class="icon-search"></i></button>',
'	    </form>',
//'	    <button class="btn btn-small action-fav" type="button" style="position:absolute; right:205px; top:5px;"><i class="icon-star"></i> 收藏</button>',
'	  </div>',
'	  <div class="modal-body"></div>',
		].join("")
	);
})(contentstree);