var editorModel = {
	"siteHeader": {
		"id": "b1b3473c-8124-4de4-a074-0f650b1b3ee4",
		"userId": "399d07cd-6fbc-49a5-9f12-c042f365c7e0",
		"revision": 0,
		"version": 1339489498444,
		"applicationType": "HtmlWeb",
		"documentType": "template",
		"published": false
	},
	"mode": "nodebug",
	"selenium": false,
	"firstSave": true,
	"metaSiteTemplate": false,
	"serviceMappings": {},
	"publicUrl": "http://wagon7310.wix.com",
	"usedMetaSiteNames": [],
	"runningExperiments": {
		"URM": "New",
		"WalkMe": "Old",
		"AdminLogin": "New",
		"Fix3713": "New",
		"Lang_pt": "New",
		"TPA": "New",
		"TPAButtons": "New",
		"Fullcolor": "New",
		"SocialPanel": "New",
		"Lang_ru": "New",
		"Lang_it": "New",
		"Lang_pl": "New",
		"Lang_fr": "New",
		"PagesDropDown": "Old",
		"Lang_de": "New",
		"Lang_es": "New",
		"FPP": "New",
		"PaginatedGrid": "New",
		"MasterPage": "New"
	},
	"editorSessionId": "16233ADD-AD61-49F1-AFC1-300DCFD9D5CE",
	"languageCode": "de"
};
var serviceTopology = {
	"productionMode": true,
	"scriptsVersion": "1.186.4",
	"serverName": "wix.com",
	"mediaServerRoot": "wix.com",
	"metaSiteManagerUrl": "http://127.0.0.1:8585/meta-site-manager",
	"htmlPublicApiUrl": "http://public.aus.wix.com/wix-public-html-api",
	"htmlEditorRootUrl": "http://editor.wix.com/html/editor",
	"staticServerRootUrl": "http://static.wix.com",
	"relativeStaticSkinUrl": "/services/html-web-skins/1.151.0/javascript/",
	"relativeStaticMobileUrl": "/services/html-wysiwyg/1.186.4/javascript/",
	"scriptsRoot": "http://static.wix.com/services/html-wysiwyg/1.186.4/",
	"staticSkinUrl": "http://static.wix.com/services/html-web-skins/1.151.0/",
	"staticThemeUrl": "http://static.wix.com/services/html-wysiwyg/1.186.4//images/mobile/core/themes",
	"staticThemeUrlWeb": "http://static.wix.com/services/html-web-skins/1.151.0//images/wysiwyg/core/themes",
	"testScriptsRoot": "http://static.wix.com/services/html-wysiwyg/1.186.4/",
	"nestedSkinsMapUrl": "http://static.wix.com/services/html-web-skins/1.151.0/dependencies.json",
	"nestedComponentsMapUrl": "",
	"staticMediaUrl": "http://static.wix.com/media",
	"biServerUrl": "http://frog.wix.com",
	"emailServer": "http://assets.wix.com/common-services/notification/invoke",
	"helpServer": "http://www.wix.com/support/main/html5",
	"htmlComponentServer": "http://htmlcomponentservice.appspot.com",
	"htmlComponentEchoUrl": "http://htmlcomponentservice.appspot.com/echo",
	"premiumServerUrl": "https://premium.wix.com",
	"publicStaticsUrl": "http://static.wix.com/services/wix-public/latest",
	"createFacebookUrl": "http://www.wix.com/create/website/html/facebook-welcomer/fb",
	"createWebsiteUrl": "http://www.wix.com/create/website/all/all/web",
	"createMobileUrl": "http://meditor.wix.com/site/add/",
	"dashboardUrl": "http://www.wix.com/create/my-account",
	"dashboardServiceUrl": "http://public.wix.com/wix-dashboard",
	"flashPublicApiUrl": "http://public.wix.com/wix-public-api",
	"siteMapApiUrl": "http://editor.wix.com/wix-sitemap2-webapp",
	"staticSkinMapWebUrl": "http://static.wix.com/services/html-web-skins/1.151.0/resources/server-skin-map.xml",
	"appStoreUrl": "http://editor.wix.com/wix-apps",
	"scriptsLocationMap": {
		"wixapps": "http://static.wix.com/services/wix-apps-client/1.4.0",
		"core": "http://static.wix.com/services/html-wysiwyg/1.186.4",
		"skins": "http://static.wix.com/services/html-web-skins/1.151.0"
	},
	"editorServerRoot": "http://editor.wix.com/html/editor/web",
	"editorServerRootFB": "http://editor.wix.com/html/editor/fb",
	"staticServerUrl": "http://static.wix.com",
	"staticImagesUrl": "http://static.wix.com/media",
	"staticDocsUrl": "http://media.wix.com/ugd",
	"staticAudioUrl": "http://static.wix.com/media",
	"floggerUrl": "http://frog.wix.com",
	"ecommerceStoreManagerUrl": "http://editor.wix.com/ecommerce",
	"publicStaticBaseUri": "http://static.wix.com/services/wix-public/latest"
};

var debugMode = "nodebug";
var viewMode = 'editor';
var configUrls = {
	"productionMode": true,
	"scriptsVersion": "1.186.4",
	"serverName": "wix.com",
	"mediaServerRoot": "wix.com",
	"metaSiteManagerUrl": "http://127.0.0.1:8585/meta-site-manager",
	"htmlPublicApiUrl": "http://public.aus.wix.com/wix-public-html-api",
	"htmlEditorRootUrl": "http://editor.wix.com/html/editor",
	"staticServerRootUrl": "http://static.wix.com",
	"relativeStaticSkinUrl": "/services/html-web-skins/1.151.0/javascript/",
	"relativeStaticMobileUrl": "/services/html-wysiwyg/1.186.4/javascript/",
	"scriptsRoot": "http://static.wix.com/services/html-wysiwyg/1.186.4/",
	"staticSkinUrl": "http://static.wix.com/services/html-web-skins/1.151.0/",
	"staticThemeUrl": "http://static.wix.com/services/html-wysiwyg/1.186.4//images/mobile/core/themes",
	"staticThemeUrlWeb": "http://static.wix.com/services/html-web-skins/1.151.0//images/wysiwyg/core/themes",
	"testScriptsRoot": "http://static.wix.com/services/html-wysiwyg/1.186.4/",
	"nestedSkinsMapUrl": "http://static.wix.com/services/html-web-skins/1.151.0/dependencies.json",
	"nestedComponentsMapUrl": "",
	"staticMediaUrl": "http://static.wix.com/media",
	"biServerUrl": "http://frog.wix.com",
	"emailServer": "http://assets.wix.com/common-services/notification/invoke",
	"helpServer": "http://www.wix.com/support/main/html5",
	"htmlComponentServer": "http://htmlcomponentservice.appspot.com",
	"htmlComponentEchoUrl": "http://htmlcomponentservice.appspot.com/echo",
	"premiumServerUrl": "https://premium.wix.com",
	"publicStaticsUrl": "http://static.wix.com/services/wix-public/latest",
	"createFacebookUrl": "http://www.wix.com/create/website/html/facebook-welcomer/fb",
	"createWebsiteUrl": "http://www.wix.com/create/website/all/all/web",
	"createMobileUrl": "http://meditor.wix.com/site/add/",
	"dashboardUrl": "http://www.wix.com/create/my-account",
	"dashboardServiceUrl": "http://public.wix.com/wix-dashboard",
	"flashPublicApiUrl": "http://public.wix.com/wix-public-api",
	"siteMapApiUrl": "http://editor.wix.com/wix-sitemap2-webapp",
	"staticSkinMapWebUrl": "http://static.wix.com/services/html-web-skins/1.151.0/resources/server-skin-map.xml",
	"appStoreUrl": "http://editor.wix.com/wix-apps",
	"scriptsLocationMap": {
		"wixapps": "http://static.wix.com/services/wix-apps-client/1.4.0",
		"core": "http://static.wix.com/services/html-wysiwyg/1.186.4",
		"skins": "http://static.wix.com/services/html-web-skins/1.151.0"
	},
	"editorServerRoot": "http://editor.wix.com/html/editor/web",
	"editorServerRootFB": "http://editor.wix.com/html/editor/fb",
	"staticServerUrl": "http://static.wix.com",
	"staticImagesUrl": "http://static.wix.com/media",
	"staticDocsUrl": "http://media.wix.com/ugd",
	"staticAudioUrl": "http://static.wix.com/media",
	"floggerUrl": "http://frog.wix.com",
	"ecommerceStoreManagerUrl": "http://editor.wix.com/ecommerce",
	"publicStaticBaseUri": "http://static.wix.com/services/wix-public/latest"
};
var siteId
siteId = 'b1b3473c-8124-4de4-a074-0f650b1b3ee4';

var siteHeader = {
	"id": "b1b3473c-8124-4de4-a074-0f650b1b3ee4",
	"userId": "399d07cd-6fbc-49a5-9f12-c042f365c7e0",
	"revision": 0,
	"version": 1339489498444,
	"applicationType": "HtmlWeb",
	"documentType": "template",
	"published": false
};