W.Resources.set('EDITOR_LANGUAGE', {
  "EMPTY": "",
  "SAVE": "Speichern",
  "WIX_BASE_URL": "www.wix.com",
  "show": "Anzeigen",
  "hide": "Ausblenden",
  "open": "脰ffnen",
  "close": "Schlie脽en",
  "duplicate": "Verdoppeln",
  "headerDataPanelTitle": "Kopfleiste bearbeiten",
  "deletePic": "Bild entfernen",
  "delete": "Entfernen",
  "SAVE_CHANGES": "脛nderungen speichern",
  "headerPresetText": "Kopfleistentitel bearbeiten",
  "done": "Erledigt",
  "ok": "OK",
  "ADD_ANOTHER_LINK": "Links hinzuf眉gen",
  "FREE_LINK": "Beliebiger Link",
  "min_2_chars": "Mindestens 2 Zeichen",
  "empty_title_text": "Leerer Titel",
  "files_rejected": "Die folgenden Dateien konnten nicht hochgeladen werden",
  "too_large": "Die maximale Dateigr枚脽e, die hochgeladen werden kann, betr盲gt 5MB",
  "invalid_chars": "Der Dateipfad enth盲lt ein ung眉ltiges Zeichen",
  "SELECT_COLOR": "OK",
  "RESET": "Zur眉cksetzen",
  "SELECT_COLOR_DIALOG_TITLE": "Farbpicker",
  "SELECT_COLOR_DIALOG_CUSTOM": "Mehr Farben",
  "IMAGE_REPLACE": "Bild 盲ndern",
  "IMAGE_REPLACE_ALT": "脛ndern",
  "IMAGE_ADD": "Bild hinzuf眉gen",
  "PHOTO_ADD": "Foto hinzuf眉gen",
  "IMAGE_REMOVE": "Bild entfernen",
  "GENERAL_HORIZONTAL": "Horizontal",
  "GENERAL_VERTICAL": "Vertikal",
  "GENERAL_LAYOUT": "Layout",
  "GENERAL_SPACING": "Abstand",
  "GENERAL_TITLE": "Titel",
  "GENERAL_DESCRIPTION": "Beschreibung",
  "GENERAL_UPDATE": "Aktualisieren",
  "GENERAL_FIND": "Finden",
  "GENERAL_SET": "Einrichten",
  "GENERAL_COLOR_SCHEME": "Farbe",
  "GENERAL_IMAGES": "Bilder",
  "GENERAL_DOCS": "Dokumente",
  "GENERAL_SWFS": "Flash",
  "GENERAL_CHANGE": "脛ndern",
  "NOT_A_NUMBER": "Der Wert ist keine Ziffer",
  "NEGATIVE_NUMBER": "Die Zahl darf nicht negativ sein",
  "MAIN_BAR_COPY": "Kopieren",
  "MAIN_BAR_PASTE": "Einf眉gen",
  "MAIN_BAR_GRID": "Grid",
  "MAIN_BAR_SNAP": "Klicken",
  "MAIN_BAR_PREVIEW": "Vorschau",
  "MAIN_BAR_SAVE": "Speichern",
  "MAIN_BAR_PUBLISH": "Publizieren",
  "MAIN_BAR_UPGRADE": "Upgrade",
  "MAIN_BAR_HELP": "Editor Hilfe",
  "CUT_COMPONENT_TITLE": "Warten Sie!",
  "CUT_COMPONENT_TEXT": "Sind Sie sicher, dass Sie diese Komponente in Ihre Zwischenablage schneiden m枚chten? ",
  "DELETE_COMPONENT_TITLE": "Warten Sie!",
  "DELETE_COMPONENT_TEXT": "Sind Sie sicher, dass Sie dieses Element entfernen m枚chten?",
  "DELETE_MULTI_COMPONENT_TEXT": "Sind Sie sichern, dass Sie alle diese Elemente entfernen m枚chten?",
  "you_wont_be_able_to_change_this_url": "Sie werden diese Webadresse sp盲ter nicht 盲ndern k枚nnen",
  "change_url": "(Webadresse 盲ndern)",
  "change_url_done": "(erledigt)",
  "empty_site_name_error": "Ein leerer Websitename ist nicht g眉ltig",
  "empty_title_error": "Der Websitetitel ist leer, klicken Sie auf \"Webadresse 盲ndern\", um die Siteadresse einzurichten",
  "ERROR_SAVE_40003": "Eine Site mit diesem Namen existiert bereits in Ihrem Konto",
  "ERROR_SAVE_10116": "Ihre Site wird in zwei verschiedenen Browsern bearbeitet. Bitte schlie脽en Sie einen davon und speichern Sie erneut. Sollte das Problem weiterhin bestehen, kontaktieren Sie bitte support@wix.com",
  "ERROR_SAVE_GENERAL": "Ein Fehler ist beim Speichern Ihrer Site aufgetreten. Bitte versuchen Sie es erneut. Sollte das Problem weiterhin bestehen, kontaktieren Sie bitte support@wix.vom",
  "ERROR_SAVE_DOCUMENT": "Ein unerwarteter Fehler ist aufgetreten, w盲hrend die Daten Ihrer Site gespeichert wurden. Bitte stellen Sie sicher, das Sie bei Wix.com eingeloggt sind. Sollte das Problem weiterhin bestehen, kontaktieren Sie bitte support@wix.com",
  "ERROR_SAVE_THEME": "Ein unerwarteter Fehler ist aufgetreten, w盲hrend Ihre Themendaten gespeichert wurden. Sollte das Problem weiterhin bestehen, kontaktieren Sie bitte support@wix.com",
  "ERROR_CODE_IS": "Fehlermeldung f眉r Support",
  "editHeaderTitle": "Kopfleiste",
  "editDesignTitle": "Design",
  "editDesignBgTitle": "Hintergrund",
  "editDesignColorTitle": "Farben",
  "editDesignIconsTitle": "Symbol",
  "editDesignHeaderTitle": "Websitefarben",
  "editDesignBgDesc": "Hier k枚nnen Sie Ihren Hintergrund bearbeiten",
  "editDesignColorDesc": "Hier k枚nnen Sie die Farben Ihrer Website bearbeiten",
  "editDesignIconsDesc": "Hier k枚nnen Sie Ihre Symbole bearbeiten",
  "editDesignHeaderDesc": "Hier k枚nnen Sie Ihre Kopfleiste bearbeiten",
  "editDesignColorSubTitle": "W盲hlen Sie Ihre Farben aus",
  "editDesignTemplateTitle": "Templates",
  "editDesignTemplateDesc": "Hier k枚nnen Sie Ihre Templates 盲ndern",
  "siteBgColor": "Hintergrund",
  "headerTextColor": "Titeltext",
  "textColor": "Textk枚rper",
  "borderColor": "Rand",
  "brc": "Rand",
  "brc1": "Rand 1",
  "brc2": "Rand 2",
  "areaBgColor": "Button",
  "iconBgColor": "Symbol",
  "headerBgColor": "Kopfleistenhintergrund",
  "headerColor": "Kopfleistenfarbe",
  "$bgColor": "Hintergrund",
  "bgc": "Hintergrund",
  "backgroundColor": "Hintergrund",
  "fontColor": "Fontfarbe",
  "fnt": "Fontstil",
  "fntt": "Titel Font",
  "fntds": "Beschreibungsfont",
  "fntlnk": "Link Font",
  "linkColor": "Link",
  "clr": "Farbe",
  "txt1": "Text 1",
  "txt2": "Text 2",
  "elm": "Elementfarbe",
  "elm2": "Zweite Elementfarbe",
  "els": "Elementgr枚脽e",
  "bg": "Hintergrund",
  "bgctr": "Hintergrund Mitte",
  "bg1": "Hintergrund 1",
  "bg2": "Hintergrund 2",
  "bg3": "Hintergrund 3",
  "bgs": "Hintergrund ausgew盲hlt",
  "bgh": "Hintergrund Mouse",
  "bgDrop": "Dropdown Hintergrund",
  "txt": "Text",
  "ttl": "Titel",
  "txt3": "Text 3",
  "txts": "Text ausgew盲hlt",
  "txth": "Text Mouseover",
  "brd": "Rand",
  "brds": "Rand wurde ausgew盲hlt",
  "brdh": "Rand Mouseover",
  "brw": "Randbreite",
  "brwt": "Obere Randbreite",
  "brwb": "Untere Randbreite",
  "sep": "Trennfarben",
  "lnw": "Linienbreite",
  "lnw1": "Linie 1 Breite",
  "lnw2": "Linie 2 Breite",
  "pad": "Abstand",
  "lnk": "Link",
  "color_0": "Websitehintergrund",
  "color_1": "Box 1",
  "color_2": "Box 2",
  "color_3": "Box",
  "color_4": "Box 4",
  "color_5": "Text 1",
  "color_6": "Text 2",
  "color_7": "Text 3",
  "color_8": "Text 4",
  "color_9": "Betonung 1",
  "color_10": "Betonung 2",
  "rd": "",
  "rdDrop": "Dropdown  Eckengr枚脽e",
  "shd": "Schatten ",
  "ERROR_TITLE_TO_LONG": "Text ist zu lang",
  "ERROR_CONTENT_TO_LONG": "Der Text, den Sie eingegeben haben, ist l盲nger als erlaubt",
  "ERROR_SAVE_TITLE": "Speicherfehler",
  "ERROR_PUBLISH_TITLE": "Fehler beim Publizieren",
  "ERROR_CLONE_SITE": "Ein unerwarteter Fehler ist aufgetreten, w盲hrend die Daten Ihrer Site vorbereitet wurden. Sollte das Problem weiterhin bestehen, kontaktieren Sie uns bitte unter support@wix.com",
  "ERROR_PUBLISH_DOCUMENT": "Fehler beim Speichern des Dokuments",
  "ERROR_PUBLISH_DOCUMENT_FB_TITLE": "Oops...",
  "ERROR_PUBLISH_DOCUMENT_FB": "Ein Fehler ist beim Publizieren Ihres Dokuments aufgetreten. Bitte kehren Sie zur眉ck zum Editor und versuchen Sie erneut zu publizieren. Sollte das Problem weiterhin bestehen, kontaktieren Sie bitte support@wix.com oder klicken Sie im Editor auf den Hilfe Button",
  "SUCCESS_SAVE_TITLE": "Gespeichert!",
  "SUCCESS_SAVE_DESCRIPTION": "Sie haben ihre Site erfolgreich gespeichert. ",
  "FACEBOOK_TARGET_PRESET_TEXT": "Geben Sie Ihre Facebook URL ein",
  "LINKEDIN_TARGET_PRESET_TEXT": "Geben Sie Ihre LinkedIn URL ein",
  "TWITTER_TARGET_PRESET_TEXT": "Geben Sie Ihre Twitter URL ein",
  "CALL_TARGET_PRESET_TEXT": "Geben Sie Ihre Telefonnummer ein",
  "SMS_TARGET_PRESET_TEXT": "Geben Sie Ihre Telefonnummer ein",
  "EMAIL_TARGET_PRESET_TEXT": "Geben Sie Ihre Emailadresse ein",
  "MAP_TARGET_PRESET_TEXT": "Geben Sie Ihre Adresse ein",
  "BLOGGER_TARGET_PRESET_TEXT": "Geben Sie Ihre Blogger URL ein",
  "YOUTUBE_TARGET_PRESET_TEXT": "Geben Sie Ihre YouTube URL ein",
  "FREE_LINK_TARGET_PRESET_TEXT": "Eine beliebige URL eingeben",
  "FLICKR_TARGET_PRESET_TEXT": "Geben Sie Ihre Flickr URL ein",
  "SKYPE_TARGET_PRESET_TEXT": "Geben Sie Ihre Skype URL ein",
  "MYSPACE_TARGET_PRESET_TEXT": "Geben Sie Ihre Myspace URL ein",
  "VIMEO_TARGET_PRESET_TEXT": "Geben Sie Ihre Vimeo URL ein",
  "DELICIOUS_TARGET_PRESET_TEXT": "Geben Sie Ihre geschmackvolle URL ein",
  "CHOOSE_TEMPLATE": "Template ausw盲hlen",
  "NAME_SITE": "Sitename",
  "EDIT_PAGES": "Seiten bearbeiten",
  "PUBLISH": "Publizieren",
  "NOTE": "Hinweis: \"Mein Konto\" wird nicht aktualisiert, bis Sie die Seite neu gestartet haben",
  "CHOOSE_TEMPLATE_DIALOG_HEADER": "W盲hlen Sie ein template aus",
  "NEXT_STEP_BUTTON": "N盲chster Schritt",
  "MY_PAGES": "Meine Seiten",
  "ADD_PAGE_BUTTON": "Seite hinzuf眉gen",
  "EDIT_DESIGN_BUTTON": "Design bearbeiten",
  "Show": "Anzeigen",
  "Hide": "Ausblenden",
  "ADD_LINKS": "Links hinzuf眉gen",
  "NEXT_PAGE_BUTTON": "N盲chste Seite",
  "PREV_PAGE_BUTTON": "Vorherige Seite",
  "ADD_PAGE_DIALOG_HEADER": "Seite hinzuf眉gen",
  "ADD_PAGE_DIALOG_DESCRIPTION": "",
  "ADD_PAGE_CONTENT_LABEL": "Seitenlayout",
  "NAME_YOUR_PAGE": "Ihre Seite benennen",
  "ADD_AS_SUB_PAGE": "Als Unterseite hinzuf眉gen",
  "ADD_BUTTON": "Hinzuf眉gen",
  "ADD_PAGE_BLANK_GROUPNAME": "Leer",
  "ADD_PAGE_ABOUT_GROUPNAME": "脺ber",
  "ADD_PAGE_SERVICES_GROUPNAME": "Services",
  "ADD_PAGE_TEXT_GROUPNAME": "Text",
  "ADD_PAGE_GALLERY_GROUPNAME": "Galerie",
  "ADD_PAGE_CONTACT_GROUPNAME": "Kontakt",
  "ADD_PAGE_SITE_CONTENT_GROUPNAME": "Websiteinhalt",
  "ADD_PAGE_MUSIC_VIDEO_GROUPNAME": "Musik & Video",
  "ADD_PAGE_SHOP_GROUPNAME": "Produktgalerie",
  "ADD_PAGE_DEBUG_GROUPNAME": "Debug",
  "ADD_PAGE_BLANK_DESCRIPTION": "Eine leere Seite",
  "ADD_PAGE_ABOUT1_DESCRIPTION": "Klassische About Seite mit gro脽em Bild neben Titel, Untertitel und Text.",
  "ADD_PAGE_ABOUT2_DESCRIPTION": "Text fokussiert und einfach. Diese 脺ber Seite enth盲lt einen Titel, Untertitel und einen gro脽en Paragrafen f眉r langen Text.",
  "ADD_PAGE_ABOUT3_DESCRIPTION": "Die komplette 脺ber Seite, die Bilder und Text kombiniert, so dass Sie mehr Firmeninformationen, hinzuf眉gen k枚nnen, wie z.B. 脺ber, Dienstleistungen, Team.",
  "ADD_PAGE_ABOUT4_DESCRIPTION": "Einfache Textseite mit Titel und Text. Eignet sich besonders f眉r Seiten mit Vollbildhintergrund",
  "ADD_PAGE_SERVICES1_DESCRIPTION": "Bilder, Titel und Text ordentlich in einem Raster ausgerichtet, um genug Raum f眉r ausf眉hrliche Informationen 眉ber Ihren Service zu bieten",
  "ADD_PAGE_SERVICES2_DESCRIPTION": "Eine fettgedruckte und auff盲llige Service-Seite. Drei Abschnitte mit vertikalem Layout mit Bildern und Text.",
  "ADD_PAGE_SERVICES3_DESCRIPTION": "Einfach und effektiv. Drei Abschnitte mit horizontalem Layout mir Bildern und Text.",
  "ADD_PAGE_SERVICES4_DESCRIPTION": "Eine wunderbare M枚glichkeit, Preislisten und Pakete auf einer Seite anzuzeigen. Das einfache Design bietet Platz f眉r Bilder und f眉r Text.",
  "ADD_PAGE_TEXT1_DESCRIPTION": "Eine einfache Textseite mit Titel, Untertitel und Paragrafen f眉r viel Inhalt.",
  "ADD_PAGE_TEXT2_DESCRIPTION": "Dieses frische Text Layout erm枚glicht Ihnen, Ihren Inhalt in Paragrafen einzuteilen. Eignet sich besondern f眉r eine Seite f眉r Neuigkeiten.",
  "ADD_PAGE_TEXT3_DESCRIPTION": "Ein einfaches 3 Kolumnen Layout, das sich gut f眉r eine Seite f眉r Neuigkeiten eignet. ",
  "ADD_PAGE_GALLERY1_DESCRIPTION": "Eignet sich gut f眉r Portfolios, Shops, Homepages",
  "ADD_PAGE_GALLERY2_DESCRIPTION": "Eine gro脽artige Galerieseite, die Ihnen erm枚glicht, Ihrer Bilder mit einer Beschreibung in einem akkuraten Raster",
  "ADD_PAGE_GALLERY3_DESCRIPTION": "Zeigen Sie Ihr gesamtes Portfolio in einer Diashow an. Die Seite enth盲lt einen Titel und Text, um Ihre Arbeiten zu beschreiben.",
  "ADD_PAGE_GALLERY4_DESCRIPTION": "Eignet sich gut f眉r das visuelle Auflisten Ihrer Portfolios mit Platz f眉r Textbeschreibungen. ",
  "ADD_PAGE_CONTACT1_DESCRIPTION": "Ihre Bild- und Kontaktdetails kommen mit einem Kontaktformular. So k枚nnen Ihre Kunden Sie direkt 眉ber Ihre Website kontaktieren.",
  "ADD_PAGE_CONTACT2_DESCRIPTION": "Eignet sich besonders gut f眉r Firmen, die ihren Kunden den direkten Weg zu sich zeigen m枚chten. Ihre Kontaktangaben mit einer Landkarte!",
  "ADD_PAGE_CONTACT3_DESCRIPTION": "Die alles in allem Kontaktseite. Kontaktinformationen, Landkarte und Kontaktformular. Eignet sich gut f眉r Firmen",
  "ADD_PAGE_SITE_CONTENT1_DESCRIPTION": "Eignet sich gut, um Ihre Speisekarte anzuzeigen! Bilder werden mit Titel und Text angezeigt.",
  "ADD_PAGE_SITE_CONTENT2_DESCRIPTION": "Zeigen Sie Ihre Immobilienauflistung mit Stil an. Mit einer Galerie und Text, um sie zu vermarkten.",
  "ADD_PAGE_SITE_CONTENT3_DESCRIPTION": "Zeigen Sie Ihre FAQs (H盲ufig gestellte Fragen) mit diesem Textlayout stilvoll an.",
  "ADD_PAGE_SITE_CONTENT4_DESCRIPTION": "Der perfekte online Lebenslauf, um Arbeitgeber zu beeindrucken. Listen Sie Ihre Berufserfahrung und Ausbildung auf. F眉gen Sie eine Beschreibung mit oder ohne Bild hinzu.",
  "ADD_PAGE_SITE_CONTENT5_DESCRIPTION": "Eine wunderbare Art, Ihre Kunden auf dem Laufenden zu halten. Geben Sie Ihre Neuigkeiten mit Bilder ein und f眉gen Sie Links hinzu.",
  "ADD_PAGE_SITE_CONTENT6_DESCRIPTION": "Zeigen Sie Portfolios in einer stilvollen Galerie mit Platz f眉r Logos und Namen Ihrer Kunden. Eine gro脽artige Kundenseite, mit Raum f眉r Empfehlungen.",
  "ADD_PAGE_MUSIC_VIDEO1_DESCRIPTION": "Eignet sich gut f眉r das Anzeigen eines Videoplayers. Inklusive Platz f眉r Titel, Untertitel und Text unter dem Player.",
  "ADD_PAGE_MUSIC_VIDEO2_DESCRIPTION": "Eignet sich gut, um mehrere Videoplayer auf der selben Seite anzuzeigen. Inklusive Platz f眉r Titel, Untertitel und Text unter jedem Player.",
  "ADD_PAGE_MUSIC_VIDEO3_DESCRIPTION": "Eignet sich gut, um Ihre Musikvideos und Tracks auf einer Seite anzubringen. Importieren Sie YouTube Videos und SoundCloud Musik und lassen Sie Ihre Besucher Ihnen zuh枚ren.",
  "ADD_PAGE_MUSIC_VIDEO4_DESCRIPTION": "Eine wunderbare M枚glichkeit, Ihre Alben anzuzeigen. Mit Bild f眉r Album Cover, Text f眉r die Songliste und einem Button mit einem Link, direkt in Ihren Onlineshop.",
  "ADD_PAGE_SHOP1_DESCRIPTION": "Die Kombo eines gro脽en Bildheaders und Titels 眉ber dem Raster eignet sich gut f眉r Ihren Shop! Die Grid-Galerie erm枚glicht Ihnen Ihre Produkte mit Beschreibung und Preis anzuzeigen.",
  "ADD_PAGE_SHOP2_DESCRIPTION": "Eignet sich gut f眉r eine weitere Verkaufsseite. Die Grid-Galerie erm枚glich Ihnen, Ihre Produkte mit einer Beschreibung und dem Preis anzuzeigen.",
  "ADD_PAGE_DEBUG1_DESCRIPTION": "Diese Seite enth'lt alle Komponenten, die es in diesem Editor gibt und in der Galaxie im Allgemeinen",
  "ADD_PAGE_DEBUG2_DESCRIPTION": "Enth盲lt verschiedene Textstile",
  "ADD_PAGE_BLANK_NAME": "Leer",
  "ADD_PAGE_ABOUT1_NAME": "脺ber1",
  "ADD_PAGE_ABOUT2_NAME": "脺ber2",
  "ADD_PAGE_ABOUT3_NAME": "脺ber3",
  "ADD_PAGE_ABOUT4_NAME": "脺ber4",
  "ADD_PAGE_SERVICES1_NAME": "Services1",
  "ADD_PAGE_SERVICES2_NAME": "Services2",
  "ADD_PAGE_SERVICES3_NAME": "Services3",
  "ADD_PAGE_SERVICES4_NAME": "Preisliste",
  "ADD_PAGE_TEXT1_NAME": "Text1",
  "ADD_PAGE_TEXT2_NAME": "Text2",
  "ADD_PAGE_TEXT3_NAME": "Text3",
  "ADD_PAGE_GALLERY1_NAME": "Raster",
  "ADD_PAGE_GALLERY2_NAME": "Gro脽es Raster",
  "ADD_PAGE_GALLERY3_NAME": "Diashow",
  "ADD_PAGE_GALLERY4_NAME": "Portfolio",
  "ADD_PAGE_CONTACT1_NAME": "Formular",
  "ADD_PAGE_CONTACT2_NAME": "Landkarte",
  "ADD_PAGE_CONTACT3_NAME": "Formular & Landkarte",
  "ADD_PAGE_SITE_CONTENT1_NAME": "Speisekarte",
  "ADD_PAGE_SITE_CONTENT2_NAME": "Immobilenehandel",
  "ADD_PAGE_SITE_CONTENT3_NAME": "FAQ",
  "ADD_PAGE_SITE_CONTENT4_NAME": "Lebenslauf",
  "ADD_PAGE_SITE_CONTENT5_NAME": "Neuigkeiten",
  "ADD_PAGE_SITE_CONTENT6_NAME": "Kunden",
  "ADD_PAGE_MUSIC_VIDEO1_NAME": "Video",
  "ADD_PAGE_MUSIC_VIDEO2_NAME": "Videoband",
  "ADD_PAGE_MUSIC_VIDEO3_NAME": "Musikseite",
  "ADD_PAGE_MUSIC_VIDEO4_NAME": "Diskografie",
  "ADD_PAGE_SHOP1_NAME": "Shop1",
  "ADD_PAGE_SHOP2_NAME": "Shop2",
  "ADD_PAGE_DEBUG1_NAME": "Alle Komponenten",
  "ADD_PAGE_DEBUG2_NAME": "Textstile",
  "EDIT_DESIGN_DIALOG_HEADER": "Design bearbeiten",
  "EDIT_HEADER": "Kopfleiste bearbeiten",
  "CHANGE_SITE_TITLE": "Websitetitel 盲ndern",
  "replacePic": "Bild 盲ndern",
  "addPic": "Bild hinzuf眉gen",
  "addIcon": "Symbol hinzuf眉gen",
  "DONE_BUTTON": "Erledigt",
  "CANCEL_BUTTON": "Abbrechen",
  "OK_BUTTON": "OK",
  "YES_BUTTON": "Ja",
  "NO_BUTTON": "Nein",
  "DELETE_BUTTON": "Entfernen",
  "DEFAULT_BUTTON_LABEL": "MEIN BUTTON",
  "ADD_LINK_DIALOG_HEADER": "W盲hlen Sie den Link aus, den Sie hinzuf眉gen m枚chten",
  "FACEBOOK_TITLE": "Facebook",
  "LINKEDIN_TITLE": "Linkedin",
  "TWITTER_TITLE": "Twitter",
  "CALL_TITLE": "Klicken um anzurufen",
  "SMS_TITLE": "Klicken, um zu texten",
  "EMAIL_TITLE": "Email",
  "MAP_TITLE": "Ort",
  "BLOGGER_TITLE": "Blogger",
  "YOUTUBE_TITLE": "YouTube",
  "FREE_LINK_TITLE": "Beliebiger Link",
  "FLICKR_TITLE": "Flickr",
  "SKYPE_TITLE": "Skype",
  "MYSPACE_TITLE": "Myspace",
  "VIMEO_TITLE": "Vimeo",
  "DELICIOUS_TITLE": "Geschmackvoll",
  "CHOOSE_TRANSITION": "Seiten眉berg盲nge",
  "STATISTICS_TITLE": "Statistiken",
  "SEO_TITLE": "SEO (Google)",
  "CLIP_ART_REPLACE_IMAGE": "Clipart 盲ndern",
  "PHOTO_REPLACE_IMAGE": "Bild 盲ndern",
  "PHOTO_IMAGE_MODE": "Bildmodus: ",
  "PHOTO_TITLE": "Titel",
  "PHOTO_ALT_TEXT": "Alt Text (optional)",
  "FLASH_DISPLAY_MODE": "Skalierung: ",
  "FLASH_REPLACEMENT_IMAGE": "Ausweichbild:",
  "SOCIAL_BAR_ICON_SIZE": "Symbolgr枚脽e",
  "SOCIAL_BAR_BG_SCALE": "Hintergrundskala",
  "SOCIAL_BAR_MNG_ICONS": "Symbole organisieren",
  "FLICKR_USERNAME": "Flickr Benutzername",
  "FLICKR_USERNAME_PLACEHOLDER": "Ihr Flickr Benutzername",
  "FLICKR_TAG_TITLE": "Nach Tag anzeigen",
  "FLICKR_SHOW_TITLE": "Anzeigen",
  "FLICKR_SHOW_ITEM_LATEST": "Letzte",
  "FLICKR_SHOW_ITEM_RANDOM": "Zuf盲llig",
  "FLICKR_LAYOUT_TITLE": "Layout",
  "FLICKR_LAYOUT_ITEM_HORZ": "Horizontal",
  "FLICKR_LAYOUT_ITEM_VERT": "Vertikal",
  "FLICKR_GALLERY_SIZE": "Galeriegr枚脽e",
  "FLICKR_IMAGE_SIZE": "Bildgr枚脽e",
  "SOUNDCLOUD_EMBED_TITLE": "Eingebetteter Code",
  "SOUNDCLOUD_SHOW_ARTWORK": "Bild anzeigen",
  "SOUNDCLOUD_AUTOPLAY": "Automatische Wiedergabe",
  "VIDEO_URL": "Video URL",
  "VIDEO_URL_PLACE_HOLDER": "YouTube oder Vimeo URL",
  "VIDEO_PLAYER_CONTROLS": "Steuerungsleiste",
  "VIDEO_PLAYER_AUTO_PLAY": "Automatische Wiedergabe",
  "VIDEO_PLAYER_LOOP": "Schleife",
  "VIDEO_TITLE": "Titelleiste anzeigen",
  "VIDEO_PLAYER_LIGHT_THEME": "Helle Steuerungsleiste",
  "VIDEO_VALIDATION_ERR": "Bitte geben Sie eine g眉ltige YoutTube oder Vimeo URL ein",
  "EDIT_RICH_TEXT": "Text bearbeiten",
  "PAYPAL_BUTTON_TYPE": "Buttonart",
  "PAYPAL_MERCHANT_EMAIL": "PayPal H盲ndler Email",
  "PAYPAL_ITEM_NAME": "Artikelname",
  "PAYPAL_ITEM_ID": "Artikel ID (optional)",
  "PAYPAL_ORG_NAME": "Organisationsname",
  "PAYPAL_ORG_ID": "Organisations ID (optional)",
  "PAYPAL_PRICE": "Preis",
  "PAYPAL_AMOUNT": "Menge",
  "PAYPAL_CURRENCY": "W盲hrung",
  "PAYPAL_OPEN_IN": "脰ffnen in: ",
  "PAYPAL_USE_SMALL_BUTTON": "Kleinen Button benutzen",
  "PAYPAL_HIDE_CREDIT_CARD_LOGOS": "Kreditkartenlogo ausblenden",
  "GOOGLE_MAP_ADDRESS": "Adresse",
  "GOOGLE_MAP_ADDRESS_PH": "Geben Sie hier eine Adresse ein, um zu suchen",
  "GOOGLE_MAP_DESCRIPTION_PH": "Wix Lounge NYC",
  "GOOGLE_MAP_MAP_TYPE": "Kartentyp",
  "GOOGLE_MAP_MAP_TYPE_NORMAL": "Normal",
  "GOOGLE_MAP_MAP_TYPE_SATELLITE": "Satellit",
  "GOOGLE_MAP_MAP_TYPE_HYBRID": "Hybrid",
  "GOOGLE_MAP_MAP_TYPE_TERRAIN": "Gel盲nde",
  "GOOGLE_MAP_SHOW_CONTROL_MAP_TYPE": "Kartentyp kontrollieren",
  "GOOGLE_MAP_SHOW_CONTROL_ZOOM": "Zoom Optionen",
  "GOOGLE_MAP_SHOW_CONTROL_POSITION": "Navigationskontrolle",
  "GOOGLE_MAP_SHOW_CONTROL_STREET_VIEW": "Street View Kontrolle",
  "GOOGLE_MAP_ALLOW_MAP_DRAGGING": "Map dragging",
  "GOOGLE_MAP_ALLOW": "Zulassen",
  "GOOGLE_MAP_INVALID_ADDRESS_VAL_ERR": "Bitte geben Sie eine g眉ltige Adresse ein",
  "GOOGLE_MAP_CLICK_2_C_More": "Klicken Sie, um mehr zu sehen...",
  "FB_LIKE_BUTTON_STYLE": "Button Stil",
  "FB_LIKE_ACTION": "Aktion",
  "FB_LIKE_SHOW_SEND_BUTTON": "Button senden",
  "FB_LIKE_SHOW_PROFILE_PICS": "Profilbilder anzeigen",
  "FB_COMMENTS_NUM_OF_COMMENTS": "Anzahl der Kommentare",
  "TWITTER_USER_TO_FOLLOW": "Twitter Benutzername",
  "TWITTER_USER_TO_FOLLOW_PLACEHOLDER": "Ihr Twitter Benutzername",
  "TWITTER_TWEET_TWEET_TEXT": "Tweet Text",
  "TWITTER_TWEET_TWEET_DEF_TEXT": "Ich bin von dieser Site besessen!",
  "TWITTER_TWEET_BUTTON_STYLE": "Button Stil",
  "TWITTER_FOLLOW_DISPLAY_TOTAL_FOLLOWERS": "Alle Follower anzeigen",
  "TWITTER_FOLLOW_DISPLAY_TWITTER_HANDLE": "Twitter Handle anzeigen",
  "TWITTER_USER_VAL_ERR": "Bitte geben Sie einen g眉ltigen Twitter Benutzernamen ein",
  "TWITTER_FEED_NUMBER_OF_TWEETS": "Tweets in Feed",
  "GOOGLE_PLUS_ONE_BUTTON_SIZE": "Buttongr枚脽e",
  "GOOGLE_PLUS_ONE_BUTTON_STYLE": "Button Stil",
  "LINK_ADD_LINK": "Link hinzuf眉gen",
  "LINK_LINK_TO": "Verlinken mit",
  "ADD_PHOTO_BUTTON": "Bilder hinzuf眉gen",
  "DESC_PRESET_TEXT": "F眉gen Sie hier eine Beschreibung ein",
  "MEDIA_DIALOG_TAB_USER_PHOTOS": "Meine Bilder",
  "MEDIA_DIALOG_TAB_PHOTOS": "Bilder",
  "MEDIA_DIALOG_TAB_SLIDESHOWGALLERY": "Bilder",
  "MEDIA_DIALOG_TAB_MATRIXGALLERY": "Bilder",
  "MEDIA_DIALOG_TAB_SLIDERGALLERY": "Bilder",
  "MEDIA_DIALOG_TAB_BACKGROUNDS": "Bilder",
  "MEDIA_DIALOG_TAB_PATTERNS": "Muster",
  "MEDIA_DIALOG_TAB_TEXTURES": "Strukturen",
  "MEDIA_DIALOG_TAB_ICONS": "Symbole",
  "MEDIA_DIALOG_TAB_SOCIAL_ICONS": "Soziale Netzwerk Symbole",
  "MEDIA_DIALOG_TAB_USER_DOCS": "Dokumente",
  "MEDIA_DIALOG_TAB_USER_SWF": "Flash",
  "MEDIA_DIALOG_TAB_CLIPART": "Clipart",
  "MEDIA_DIALOG_TITLE_PHOTOS": "Bildergalerie",
  "MEDIA_DIALOG_TITLE_SLIDESHOWGALLERY": "Bildergalerie",
  "MEDIA_DIALOG_TITLE_MATRIXGALLERY": "Galerie Bilder",
  "MEDIA_DIALOG_TITLE_SLIDERGALLERY": "Bildergalerie",
  "MEDIA_DIALOG_TITLE_BACKGROUNDS": "Galerie Hintergr眉nde",
  "MEDIA_DIALOG_TITLE_PATTERNS": "Galerie Muster",
  "MEDIA_DIALOG_TITLE_ICONS": "Galerie Symbole",
  "MEDIA_DIALOG_TITLE_FAVICON": "Galerie Favicons",
  "MEDIA_DIALOG_TITLE_SOCIAL_ICONS": "Galerie Soziale Netzwerk Symbole",
  "MEDIA_DIALOG_TITLE_CLIPART": "Galerie Clipart",
  "MEDIA_DIALOG_TITLE_DOCUMENTS": "Galerie Dokumente",
  "MEDIA_DIALOG_TITLE_SWF": "Flash Galerie",
  "DELETE_MEDIA_TITLE": "Sind Sie sicher, dass dieses Medienelement entfernen m枚chten",
  "DELETE_MEDIA_TEXT": "Das Medienelement wird weiterhin da angezeigt werden, wo es auf der Website angebracht wurde. ",
  "MEDIA_DIALOG_DESCRIPTION_PHOTOS": "Laden Sie Ihre Bilder hoch (jpg, png, gif). Die Maximalgr枚脽e betr盲gt 5MB.<BR> Oder Sie w盲hlen aus den Galerien. W盲hlen Sie ein Bild und klicken Sie auf OK.",
  "MEDIA_DIALOG_DESCRIPTION_SLIDESHOWGALLERY": "Laden Sie eigene Bilder hoch (jpg, png, gif). Die Maximalgr枚脽e betr盲gt 5MB.<BR> Oder Sie w盲hlen aus unseren Galerien. Danach klicken Sie auf OK.",
  "MEDIA_DIALOG_DESCRIPTION_MATRIXGALLERY": "Laden Sie eigene Bilder hoch (jpg, png, gif). Die Maximalgr枚脽e betr盲gt 5MB.<BR> Oder Sie w盲hlen aus unseren Galerien. Danach klicken Sie auf OK.",
  "MEDIA_DIALOG_DESCRIPTION_SLIDERGALLERY": "Laden Sie eigene Bilder hoch (jpg, png, gif). Die Maximalgr枚脽e betr盲gt 5MB.<BR> Oder Sie w盲hlen aus unseren Galerien. Danach klicken Sie auf OK.",
  "MEDIA_DIALOG_DESCRIPTION_BACKGROUNDS": "Laden Sie Ihr eigenes Hintergrundbild hoch (jpg, png, gif). Die Maximale Dateigr枚脽e, die hochgeladen werden kann betr盲gt 5MB.<BR> Oder Sie w盲hlen ein Bild von einer unserer Galerien aus. Nachdem Sie ein Bild gew盲lt haben, klicken Sie auf OK.",
  "MEDIA_DIALOG_DESCRIPTION_PATTERNS": "Galerie Muster",
  "MEDIA_DIALOG_DESCRIPTION_ICONS": "Galerie Symbole",
  "MEDIA_DIALOG_DESCRIPTION_FAVICON": "Galerie Favicons",
  "MEDIA_DIALOG_DESCRIPTION_SOCIAL_ICONS": "Laden Sie Ihre Symbole hoch (jpg, png, gif). Die Maximalgr枚脽e betr盲gt 5MB.<BR> Oder Sie w盲hlen aus den Galerien. W盲hlen Sie ein Symbol und klicken Sie auf OK.",
  "MEDIA_DIALOG_DESCRIPTION_CLIPART": "Laden Sie eigene Bilder hoch (jpg, png, gif). Die Maximalgr枚脽e betr盲gt 5MB.<BR> Oder Sie w盲hlen aus unseren Galerien. Danach klicken Sie auf OK.",
  "MEDIA_DIALOG_DESCRIPTION_DOCUMENTS": "Laden Sie Ihre eigenen Dokumente hoch (doc & .docs, .xls & .xlsx, .ppt & .pptx, .odt, .pdf). <BR>Die Maximale Dateigr枚脽e betr盲gt 10MB. Nachdem Sie ein Bild gew盲lt haben, klicken Sie auf OK.",
  "MEDIA_DIALOG_DESCRIPTION_SWF": "Um Ihrer Galerie eine Flash Datei (swf) hinzuzuf眉gen, klicken Sie auf Flash hochladen und w盲hlen Sie die Flash <BR>Datei aus, die Sie hinzuf眉gen m枚chten. Die Maximale Dateigr枚脽e, die hochgeladen werden kann, betr盲gt 5MB.",
  "MEDIA_DIALOG_ITEM_TYPE_ICON": "Symbol",
  "GALLERY_DIALOG_HEADER": "Klicken Sie auf \"Hochladen\", um Ihre eigenen Fotos hochzuladen oder klicken Sie auf \"Bilder\" um gratis professionell Fotos zu benutzen",
  "MEDIA_GALLERY_EMPTY_TEXT": "Ihr Verzeichnis ist zur Zeit leer. Klicken Sie auf \"Hochladen\", um Ihr eigenes Verzeichnis aufzubauen. Der Button Hochladen befindet sich oben rechts im Fenster",
  "UPLOAD_IMAGE": "Bild hochladen",
  "UPLOAD_SWF": "Flash hochladen",
  "UPLOAD_ICON": "Symbol hochladen",
  "UPLOAD_GENERAL": "Hochladen",
  "add": "Hinzuf眉gen",
  "cancel": "Abbrechen",
  "NOTE_AFTER_UPLOAD": "Hochladen vollst盲ndig. W盲hlen Sie Bilder aus und klicken Sie dann auf \"Hinzuf眉gen\"",
  "SERVICES_ADD_ANOTHER_LINK": "Element hinzuf眉gen",
  "SERVICES_DEFAULT_TITLE_1": "Suchmaschinenoptimierung",
  "SERVICES_DEFAULT_DESCRIPTION_1": "SEO erfordert ein sehr spezifisches Set an F盲higkeiten. Daher bieten wir Ihnen ein Team an erfahrenen SEO Experten an, die 眉ber das Basisschl眉sselw枚rter einsetzen hinausgehen. Wir untersuchen sorgf盲lltig die erfolgreichsten Schl眉sselw枚rter f眉r Ihr Busiess, um die besten Verkaufsums盲tze zu erzielen.",
  "SERVICES_DEFAULT_IMAGE_ID_1": "a1067eb81022cee26465d626871733b0.wix_mp",
  "SERVICES_DEFAULT_TITLE_2": "Businessentwicklung",
  "SERVICES_DEFAULT_DESCRIPTION_2": "Adrian Shell Consulting wird Ihnen Ideen liefern, wie Sie Ihre Firmenprodukte entwickeln und ihr Potential aussch枚pfen k枚nnen. Unser Expertenteam wird sein weltweites Netzwerk mit globaeln Corportationen und Individuen nutzen, um Ihrer Firma dabei zu helfen, die notwendigen Partnerschaften aufzubauen, um den ulitmativen Wachstum f眉r Ihr Business zu erzielen.",
  "SERVICES_DEFAULT_IMAGE_ID_2": "9b1a89112226cb45cc8006722ba0e32c.wix_mp",
  "SERVICES_DEFAULT_TITLE_3": "Blogabdeckung",
  "SERVICES_DEFAULT_DESCRIPTION_3": "Erreichen Sie Blogger auf richtige Weise, um eine positive Abdeckung in der immer weiter wachsenden Blog Welt zu erhalten. Unsere Schreibexperten und weltweiten Verbindungen mit Top-Bloggern wird Ihre Marke an die richtigen Adressaten bringen, um Ihnen dabei zu helfen, eine erfolgreiche Online Pr盲sens aufzubauen.",
  "SERVICES_DEFAULT_IMAGE_ID_3": "d5f43c8954963e8a05a7d9dc5531d089.wix_mp",
  "SERVICES_COLLECTION_DEFAULT_TITLE_1": "Flexi Avokado Schneider",
  "SERVICES_COLLECTION_DEFAULT_DESCRIPTION_1": "Schneiden und h枚len Sie Avokados mit Stil und Leichtigkeit aus. Unser glatter, moderner Avokadosch盲ler erstellt perfekt gleichm盲脽ige Portionen und macht das Avokadoschneiden zu einem Erlebnis! Flexibler Griff ohne Abrutschen und Waschmaschinenfest!",
  "SERVICES_COLLECTION_DEFAULT_IMAGE_ID_1": "d01f8b2648838a896b354e9b3bf96568.wix_mp",
  "SERVICES_COLLECTION_DEFAULT_TITLE_2": "Flache Messl枚ffel",
  "SERVICES_COLLECTION_DEFAULT_DESCRIPTION_2": "Werden Sie mit diesen super akkuraten, Platzsparenden Messbechern zu dem Chefkoch, der Sie schon immer sein wollten. Die frischen und fr枚hlichen Farben bringen einen einzigartigen Blickfang in Ihre K眉che. Perfekt zum Portionieren von Eis, Reis, M眉sli und mehr!",
  "SERVICES_COLLECTION_DEFAULT_IMAGE_ID_2": "5f6190118dab695ddfe63fc0a63aea1a.wix_mp",
  "SERVICES_COLLECTION_DEFAULT_TITLE_3": "Runde Messl枚ffel",
  "SERVICES_COLLECTION_DEFAULT_DESCRIPTION_3": "Aus leichtem best盲ndigem Melamin, k枚nnen mit jedem L枚ffel Fl眉ssigkeiten und trockene Zutaten perfekt abgemessen werden. Das Set erhalten Sie inklusive einer Halterung zum leichten Gebrauch, Aufbewahrung und Waschen",
  "SERVICES_COLLECTION_DEFAULT_IMAGE_ID_3": "62383acf9b044b76755b2fc5a556d07b.wix_mp",
  "SERVICES_EVENTS_DEFAULT_TITLE_1": "Empfang, 24. M盲rz 2011, um 18:00 Uhr. ",
  "SERVICES_EVENTS_DEFAULT_DESCRIPTION_1": "Treffen Sie die New Yorker Kreativen bei unserem j盲hrlichen Empfang! Veranstaltet von Wix Lounge Creative, werden Ihnen frische Marketinginspiration f眉r Ihr Business und neue Netzwerkkontakte geboten. Snacks und Cokctails sind auf uns!",
  "SERVICES_EVENTS_DEFAULT_IMAGE_ID_1": "1f641c79474396cfd3bab484e974dc08.wix_mp",
  "SERVICES_EVENTS_DEFAULT_TITLE_2": "Smith Austellung im Brookly Museu, 23.M盲rz 2011 um 14:00 Uhr",
  "SERVICES_EVENTS_DEFAULT_DESCRIPTION_2": "Besuchen Sie das Brooklyn Museum und schauen Sie sich meine neuesten schwarz-wei脽 Portraits von Lonnie Anderson an. Freie Cocktails und Snacks werden angeboten. Wir sehen uns dort!",
  "SERVICES_EVENTS_DEFAULT_IMAGE_ID_2": "4ebd947586d4dd2ab80edd01d8aa6b98.wix_mp",
  "SERVICES_EVENTS_DEFAULT_TITLE_3": "Jahresmarketingkonferenz, 10. M盲rz 2011, 12:00-15:00 Uhr",
  "SERVICES_EVENTS_DEFAULT_DESCRIPTION_3": "Wir freuen uns, Sie zu unserer j盲hrlichen Marketingkonferenz einladen zu d眉rfen. Auf dieser Konferenz werden wir 眉ber PPC/SEO Methoden und mehr sprechen.",
  "SERVICES_EVENTS_DEFAULT_IMAGE_ID_3": "044ac6c97df0315457a4575edb0309f7.wix_mp",
  "SERVICES_RESTAURANT_DEFAULT_TITLE_1": "Cafe Espreso",
  "SERVICES_RESTAURANT_DEFAULT_DESCRIPTION_1": "Probieren Sie die s眉脽e, cremige Mischung des aromatischen Geschmacks aus S眉damerika. Vollmundig und cremig sind alle unsere Espressobohnen aus 枚kologischem Anbau und fair gehandelt. Die perfekte Wahl f眉r die Fr眉hschicht.",
  "SERVICES_RESTAURANT_DEFAULT_IMAGE_ID_1": "56ac36c542c15ab900160db98f2c82dd.wix_mp",
  "SERVICES_RESTAURANT_DEFAULT_TITLE_2": "Cafe Cappuccino",
  "SERVICES_RESTAURANT_DEFAULT_DESCRIPTION_2": "So traditionell wie ein Cappuccino nur sein kann. Geniessen Sie reichhaltigen und breiten Geschmack mit perfekt temperierter Milch. Wir toppen diesen italienischen Genu脽 mit einer Prise dunkler Belgischer Schokolade. Der perfekte Europatrip! Der Eis-Cappuccino kommt bald auch...",
  "SERVICES_RESTAURANT_DEFAULT_IMAGE_ID_2": "7014e2e1bae9cf2b84764d9e5c30de58.wix_mp",
  "SERVICES_RESTAURANT_DEFAULT_TITLE_3": "Tea Time",
  "SERVICES_RESTAURANT_DEFAULT_DESCRIPTION_3": "Unsere hausgemachter Tee verbindet k枚stliche dunkle Beere mit einem reichhaltigen im Schatten gewachsenen schwarzen Tee. Erhalten Sie das beste aus beiden Welten mit diesem Kaffeeliebhaber Favouriten. So wie alle unsere Kaffeebohnen, sind auch unsere Teebl盲tter aus 枚kologischem Anbau und fair gehandelt.",
  "SERVICES_RESTAURANT_DEFAULT_IMAGE_ID_3": "5c9997b9a65175138c1d56cf1ab61b08.wix_mp",
  "PUBLISH_DIALOG_HEADER": "Ihre Mobile Site ist fertig",
  "PUBLISH_BUTTON": "Publizieren",
  "FINISH_DIALOG_HEADER": "Herzlichen Gl眉ckwunsch!",
  "SUB_DIALOG_HEADER": "Ihre Mobile Site ist jetzt online.",
  "MOBILE_SITE_ADDRESS": "Um Ihre neue Mobile Site auf Ihrem Smartphone anzuzeigen, besuchen Sie: ",
  "SEND_ADDRESS": "Emailen Sie mir den Link zu meiner neuen Mobile Site",
  "SEND_BUTTON": "Senden",
  "SENDING": "Sendet...",
  "SEND_SUCCESS": "Die Mobile Site Adresse wurde an Ihre Email gesendet",
  "SEND_ERROR": "Es ist ein Problem mit der Email aufgetreten",
  "MY_ACCOUNT_PART_1": "Bitte gehen Sie zu",
  "MY_ACCOUNT_LINK": "\"Mein Konto\"",
  "MY_ACCOUNT_PART_2": "um Ihre neue Mobile Site anzuzeigen und zu verwalten",
  "UPGRADE_BUTTON": "Jetzt Upgraden!",
  "BACK_BUTTON": "Zur眉ck",
  "FINISH_HEADLINE": "Herzlichen Gl眉ckwunsch!",
  "SITE_READY": "Ihre Mobile Site ist jetzt fertig",
  "FINISH_INSTRUCTIONS": "Klicken Sie auf publizieren und schauen Sie es sich auf Ihrem Mobile Ger盲t an",
  "DELETE_PAGE_DIALOG_TITLE": "Warten Sie!",
  "DELETE_PAGE_DIALOG_TEXT": "Sind Sie sicher, dass Sie diese Seite l枚schen m枚chten",
  "DELETE_PAGE_LASTPAGE_DIALOG_TITLE": "Seite l枚schen",
  "DELETE_PAGE_LASTPAGE_DIALOG_TEXT": "Die Website muss mindestens eine Seite enthalten",
  "RESET_COLORS_DIALOG_TITLE": "Sitefarben zur眉cksetzen",
  "RESET_COLORS_DIALOG_TEXT": "Sind Sie sicher, dass Sie Ihre Sitefarben zur眉cksetzen m枚chten?",
  "RESET_COLORS_DIALOG_DETAILS": "Hinweis: Indem Sie auf \"OK\" klicken, werden die Farben Ihrer Site auf ihren letzten Stand zur眉ckgesetzt.",
  "SOCIAL_INTERACT_TEXT": "Um dieses Soziale Netzwerk Widget zu nutzen, m眉ssen Sie Ihre Site zun盲chst publizieren. ",
  "SOCIAL_INTERACT_DETAILS": "Hinweis: Indem Sie auf \"Ja\" klicken, werden Sie zum Dialogfenster Publizieren umgeleitet",
  "RESET_THEME_OVERRIDES_DIALOG_TITLE": "Themen眉berschreibung zur眉cksetzen",
  "RESET_THEME_OVERRIDES_DIALOG_TEXT": "Sind Sie sicher, dass Sie Ihre Thema zur眉cksetzen m枚chten?",
  "RESET_THEME_OVERRIDES_DIALOG_DETAILS": "Hinweis: Indem Sie auf \"OK\" klicken, werden Ihre Sitethemen眉berschreibungen auf Ihren letzten Stand zur眉ckgesetzt. ",
  "ERROR_GET_THEME_OVERRIDES_DIALOG_TITLE": "Fehler",
  "ERROR_GET_THEME_OVERRIDES_DIALOG_TEXT": "Es sind einige Probleme aufgetreten, w盲hrend die Details des Templates abgerufen wurden. ",
  "mediaBg": "W盲hlen Sie ein Hintergrundbild",
  "bgColor": "W盲hlen Sie eine Hintergrundfarbe",
  "CLICK_TO_EDIT": "Klicken um zu bearbeiten",
  "PAGE_TITLE_MASTER": "Masterseite",
  "PAGE_TITLE_GALLERY": "Galerie",
  "PAGE_TITLE_ABOUT": "脺ber",
  "PAGE_TITLE_SERVICES": "Services",
  "PAGE_TITLE_TEXT": "Text",
  "PAGE_TITLE_EVENTS": "Events",
  "PAGE_TITLE_COLLECTION": "Collection",
  "PAGE_TITLE_RESTAURANT": "Restaurant",
  "PAGE_TITLE_CONTACT": "Kontakt",
  "PAGE_TITLE_NETWORK": "Netzwerk",
  "PAGE_TITLE_BLANK": "Leer",
  "PAGE_TITLE_BLANK_DESCRIPTION": "This is the description of blank page. MISSING DESCRIPTION - Product Please provide!",
  "PAGE_TITLE_MENU": "Men眉",
  "PAGE_TITLE_MENU01_DESCRIPTION": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx - MISSING DESCRIPTION - Product Please provide!",
  "PAGE_TITLE_VIDEO": "Video",
  "PAGE_TITLE_VIDEO01_DESCRIPTION": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx - MISSING DESCRIPTION - Product Please provide!",
  "BACK_TO_DESIGN": "Zur眉ck zu Design",
  "COLORSET_TITLE": "Palette",
  "COLORSET_CONTENT": "Klicken, um zu 盲ndern. Nachdem 脛nderungen vorgenommen wurden, kann die voreingestellte Ansicht wieder hergestellt werden. Klicken Sie doppelt, um zu bearbeiten.",
  "COLORSET_RESET": "Auf voreingestellte Palette zur眉cksetzen",
  "PAGES_TITLE": "Seiten",
  "PAGES_DESCRIPTION": "Navigieren Sie durch Ihre Seiten. Um eine Seite umzubenennen, klicken Sie bitte auf das Rad-Symbol. Sie k枚nnen Seiten nach oben und unten ziehen, um sie neuzuordnen, und nach rechts ziehen, um Unterseiten zu erstellen.",
  "TIP_TITLE": "Tipp:",
  "PAGES_TIP": "Um Ihre Seiten neuzuordnen, ziehen Sie diese nach oben/unten. Um eine Unterseite zu erstellen, ziehe Sie diese nach links/rechts",
  "PAGE_SETTINGS": "Einstellungen und SEO",
  "PAGE_TITLE": "Seitentitel",
  "PAGE_DESCRIPTION": "Seitenbeschreibung",
  "META_KEYWORDS": "Schl眉sselw枚rter",
  "HIDE_PAGE": "Vom Men眉 ausblenden",
  "UNDER_CONSTRUCTION": "Baustelle",
  "DESIGN_TITLE": "Design",
  "DESIGN_DESCRIPTION": "Spielen Sie mit den Designtools, um Ihre Site genau so aussehen zu lassen, wie <i>Sie</i> es m枚chten. ",
  "ADD_COMPONENT_TITLE": "Hinzuf眉gen",
  "ADD_COMPONENT_DESCRIPTION": "W盲hlen Sie Elemente aus, die Sie auf Ihrer Site hinzuf眉gen m枚chten.",
  "ADD_COMP_TITLE_text": "Text",
  "ADD_COMP_TITLE_image": "Bild",
  "ADD_COMP_TITLE_media": "Medien",
  "ADD_COMP_TITLE_gallery": "Galerie",
  "ADD_COMP_TITLE_areas": "Formen & Linien",
  "ADD_COMP_TITLE_buttons": "Buttons",
  "ADD_COMP_TITLE_social": "Soziale Netzwerke",
  "ADD_COMP_TITLE_widgets": "AddOn",
  "ADD_COMP_DESC_text": "W盲hlen Sie einen Titel, Untertitel oder Paragrafen aus und beginnen Sie Ihren eigenen Text hinzuzuf眉gen.",
  "ADD_COMP_DESC_image": "Bilder und Clip Art auf Ihrer Site hinzuf眉gen",
  "ADD_COMP_DESC_media": "Videos und Musik auf Ihrer Site hinzuf眉gen",
  "ADD_COMP_DESC_gallery": "W盲hlen Sie aus, welche Galerie Sie Ihrer Site hinzuf眉gen m枚chten und passen Sie sie dann an. ",
  "ADD_COMP_DESC_areas": "W盲hlen Sie eine Form, Linie oder Clipart aus und gestalten Sie diese nach Ihren W眉nschen",
  "ADD_COMP_DESC_buttons": "W盲hlen Sie einen Button oder ein Men眉 aus und passen diesen/dieses an.",
  "ADD_COMP_DESC_social": "F眉gen Sie Links zu Ihren Facebook, Twitter und Google+ Profilen in einer Leiste hinzu.",
  "ADD_COMP_DESC_widgets": "F眉gen Sie Widgets wie Google Maps, eBay, Flickr und mehr hinzu.",
  "BACKGROUND_DESIGN_CUSTOMIZE": "Hintergrund hochladen und anpassen",
  "BACKGROUND_DESIGN_UPLOAD": "Hintergrundbild hochladen",
  "BACKGROUND_DESIGN_TITLE": "Hintergrund",
  "BACKGROUND_DESIGN_DESCRIPTION": "Benutzen Sie die voreingestellten Hintergr眉nde und laden Sie Ihr eigenes Bild hoch. <br/> W盲hlen Sie eine Hintergrundfarbe und passen Sie das Design weiter an, indem Sie auf Hintergrund anpassen klicken. ",
  "BACKGROUND_EDITOR_TITLE": "Hintergrund anpassen",
  "BACKGROUND_EDITOR_DESCRIPTION": "Das Bild 盲ndern und die Skalierung, Position und das Scrollen anpassen. Sie k枚nnen die Hintergrundfarbe auch von hier aus 盲ndern.",
  "COLOR_DESIGN_TITLE": "Farben",
  "COLOR_DESIGN_DESCRIPTION": "W盲hlen Sie eine Farbpalette, um das Design Ihrer Website sofort zu transformieren. Um die Farbpalette anzupassen, klicken Sie auf Palette anpassen",
  "COLOR_DYNAMIC_DESCRIPTION": "Passen Sie die Palette Ihrer Site an, indem Sie auf die Hauptfarben in der oberen Reihe klicken",
  "COLOR_DESIGN_CUSTOMIZE": "Palette anpassen",
  "COLOR_PALETTE_INVERT": "Palette umkehren",
  "DYNAMIC_PALETTE_MAIN_COLORS": "Hauptfarben",
  "DYNAMIC_PALETTE_MORE_COLORS": "Mehr Farben",
  "DISCARD_CHANGES": "脛nderungen entfernen",
  "FONTS_DESIGN_TITLE": "Fonts",
  "FONTS_DESIGN_DESCRIPTION": "Transformieren Sie das Fontschema Ihrer Site mit einem Klick. Um anzupassen, klicken Sie auf Fonts anpassen",
  "FONTS_DESIGN_CUSTOMIZE": "Fonts anpassen",
  "FONT_PRESET_TITLE": "Der kleine Prinz",
  "FONT_PRESET_SUB_TITLE": "La脽t sie Kuchen essen",
  "FONT_PRESET_SIZE_WARNING": "Der angezeigte Font ist kleiner als seine eigentliche Gr枚脽e",
  "CONTAINER_HIGHLIGHT_ATTACH": "Anh盲ngen",
  "CONTAINER_HIGHLIGHT_ATTACH_FALLBACK": "Anh盲ngen",
  "CONTAINER_HIGHLIGHT_ATTACH_PAGE": "An Seite h盲ngen",
  "CONTAINER_HIGHLIGHT_ATTACH_CONTAINER": "An Box h盲ngen",
  "CONTAINER_HIGHLIGHT_ATTACH_HEADER": "An Kopfzeilen h盲ngen",
  "CONTAINER_HIGHLIGHT_ATTACH_FOOTER": "An Fu脽leiste h盲ngen",
  "CONTAINER_HIGHLIGHT_PARENT_FALLBACK": "",
  "CONTAINER_HIGHLIGHT_PARENT_PAGE": "Seite",
  "CONTAINER_HIGHLIGHT_PARENT_CONTAINER": "Box",
  "CONTAINER_HIGHLIGHT_PARENT_HEADER": "Kopfzeile",
  "CONTAINER_HIGHLIGHT_PARENT_FOOTER": "Fu脽leiste",
  "SEO_PANEL_TITLE_FULL": "Suchmaschinenoptimierung",
  "SEO_PANEL_DESCRIPTION": "Suchmaschinenoptimierung (SEO) ist ein Vorgang, der die Sichtbarkeit einer Website oder einer Webseite in Suchmaschinen verbessert",
  "SEO_PANEL_ALLOW_SE_FIND_MY_SITE": "Meine Site von Suchmaschinen finden lassen",
  "SEO_PANEL_SITE_DESCRIPTION_LABEL": "Site-Beschreibung",
  "SEO_PANEL_SITE_TITLE_LABEL": "Site-Titel",
  "SEO_PANEL_KEYWORD_LABEL": "Schl眉sselw枚rter",
  "SEO_PANEL_LEARN_MORE": "Erfahren Sie mehr 眉ber die SEO Optionen",
  "STATISTICS_PANEL_LABEL": "Statistiken",
  "STATISTICS_PANEL_TITLE_FULL": "Statistiken & Google Analytics",
  "STATISTICS_PANEL_DESCRIPTION": "Analysieren Sie die Statistiken und den Traffic Ihrer Site",
  "THIS_IS_PREMIUM_FEATURE": "Verfolgen Sie die Leistungsf盲higkeit Ihrer Site und analysieren Sie, von wo Ihre Besucher kommen, wie lange sie auf jeder Seite verbleiben und welche Schl眉sselw枚rter sie benutzt haben, um Sie zu finden.",
  "UPGRADE": "Um Ihre Google Analytics ID einzurichten oder zu bearbeiten, gehen Sie bitte zu Premium verwalten > Domain Tab",
  "SET_ANALYTICS": "Um Ihre Google Analytics ID einzurichten, gehen Sie bitte zu",
  "SET_ANALYTICS_BUTTON": "Premium verwalten > Domains Tab",
  "FAVICON_AND_THUMBNAIL_PANEL_FAVICON_LABEL": "Favicon",
  "FAVICON_AND_THUMBNAIL_PANEL_FAVICON_THUMBNAIL": "Thumbnail",
  "FAVICON_AND_THUMBNAIL_PANEL_FAVICON_DESCRIPTION": "Das Favicon ist Ihr eigenes 16x16 Websitesymbol, das f眉r alle Seiten Ihrer Website im Browser erscheint",
  "FAVICON_AND_THUMBNAIL_PANEL_THUMBNAIL_DESCRIPTION": "Passen Sie an, wie Ihre Site bei Facebook erscheint, wenn jemand auf \"Gef盲llt mir\" klickt oder in seinem Status postet.",
  "FAVICON_AND_THUMBNAIL_PANEL_UPGRADE_TO_UPLOAD_FAVICON_DESCRIPTION": "Upgraden und Ihr eigenes Favicon hochladen",
  "FAVICON_AND_THUMBNAIL_PANEL_UPGRADE_NOW": "Jetzt Upgraden",
  "FAVICON_AND_THUMBNAIL_PANEL_CHANGE": "脛ndern",
  "REFRESH_WHEN_UPGRADE_COMPLETED_TITLE": "Auf Premium upgraden",
  "REFRESH_WHEN_UPGRADE_COMPLETED_DESCRIPTION": "Bitte vergessen Sie nicht, nach dem Upgrade Ihre Seite zu speichern und zu aktualisieren.",
  "SITE_NAME_TITLE": "Siteadresse",
  "SITE_NAME_TITLE_FULL": "Sitename und Adresse",
  "SITE_NAME_DESCRIPTION": "Site Mitglieder wurde entworfen um Site Besitzern zu erm枚glichen, deren eigene Nutzerbasis zu behalten und zu haben",
  "SITE_NAME_LITERALLY": "Site_Name",
  "SITE_NAME_INPUT_LABEL": "Site Adresse",
  "SITE_NAME_SITE_ADDRESS_LABEL_BEFORE_SAVE": "Ihre Siteadresse wird sein: ",
  "SITE_NAME_SITE_ADDRESS_LABEL_BEFORE_PUBLISH": "Ihre Siteadresse ist: ",
  "SITE_NAME_SITE_ADDRESS_DESCRIPTION_BEFORE_SAVE": "Ihre Siteadresse lautet: ",
  "SITE_NAME_SITE_ADDRESS_DESCRIPTION_BEFORE_PUBLISH": "Bitte publizieren Sie Ihre Site, um sie live zu sehen",
  "COPY_SITE_ADDRESS": "Websiteadresse kopieren",
  "SITE_NAME_PREMIUM_BUTTON": "W盲hlen Sie mit Wix Premium eine Domain",
  "SITE_NAME_CONNECT_TO_DOMAIN": "Verbinden Sie Ihre Website mit einer Domain,",
  "SITE_NAME_MANAGE_DOMAINS": "Domains verwalten",
  "SITE_NAME_MANAGE_DOMAIN_NOTE": "<strong>Hinweis> </strong> Ihre Domaininformation wird beim n盲chsten Mal, wenn Sie den Editor 枚ffnen, aktualisert",
  "SITE_NAME_WIX_UPGRADE_AD_VOUCHERS": "Erhalten Sie Gutscheine im Wert von 125$!",
  "SITE_NAME_SWITCH_TO_YEARLY_PLAN": "Zum j盲rhlichen Plan wechseln > ",
  "SITE_NAME_CONNECT_THIS_DOMAIN": "Verbinden Sie eine Domain mit dieser Website,",
  "SITE_NAME_REMOVE_ADS": "Entfernen Sie alle Anzeigen von Wix,",
  "SITE_NAME_CLICK_HERE": "Klicken Sie hier",
  "FAVICON_AND_THUMBNAIL_TITLE": "Favicon & Thumbnail",
  "ONLY_THUMBNAIL_TITLE": "Thumbnail",
  "PAGE_SETTINGS_PAGE_NAME_AND_URL_LABEL": "Seitenname",
  "PAGE_SETTINGS_HIDE_PAGE_LABEL": "Aus dem Men眉 ausblenden",
  "PAGE_SETTINGS_SEO_SETTINGS_LABEL": "SEO Seiteneinstellungen",
  "PAGE_SETTINGS_SEO_PAGE_TITLE_LABEL": "Seitentitel",
  "PAGE_SETTINGS_SEO_SITE_DESCRIPTION_LABEL": "Seitenbeschreibung",
  "PAGE_SETTINGS_SEO_KEYWORDS_LABEL": "Schl眉sselw枚rter",
  "PAGE_SETTINGS_PAGE_NAME_LABEL": "Seitenname",
  "PAGE_SETTINGS_SEO_PAGE_URL_LABEL": "Seitenadresse",
  "PAGE_SETTINGS_TOO_MANY_KEYWORDS": "Zu viele Schl眉sselw枚rter (max. 15)",
  "PAGE_NAME_TOO_SHORT": "Seitenname kann nicht leer sein",
  "PAGE_NAME_PREFIX_ERROR": "Seitenname kann nicht mit \"&lt;\" beginnen",
  "INPUT_INVALID_CHARACTERS": "Ung眉ltiges Zeichen",
  "SAVE_YOUR_SITE": "Bitte speichern Sie Ihre Site",
  "SAVE_WAIT_FOR_EDITOR_RELOAD": "Bitte warten Sie, bis der Editor nach dem Speichern neugeladen wird.",
  "SAVE_YOUR_FACEBOOK_PAGE": "Bitte speichern Sie Ihre Seite",
  "SAVE_YOUR_SITE_DESC": "Der Name, den Sie w盲hlen, wird in Ihrer Webadresse erscheinen. Sie k枚nnen diesen sp盲ter in Mein Konto 盲ndern",
  "SAVE_YOUR_SITE_DESC_META_SITE_EXISTS": "Nachdem Sie publiziert haben, wird Ihre Website unter folgender Webadresse verf眉gbar sein:",
  "SITE_NAME_PLACEHOLDER": "Geben Sie Ihre Sitenamen ein",
  "BECOME_PREMIUM_MEMBER": "Werden Sie ein Premium Mitglied",
  "CONNECT_SITE_TO_DOMAIN": "Verbinden Sie Ihre Website mit einer Domain, die Sie bereits besitzen, um Ihre eigene Doman graits erhalten!",
  "SITE_NAME_SANITIZED": "Geben Sie Ihren Sitenamen ein",
  "FACEBOOK_PAGE_NAME_PLACEHOLDER": "Geben Sie einen Seitennamen ein",
  "SITE_NAME_INVALID_CHAR": "ist in einem Sitenamen ung眉ltig",
  "SITE_NAME_TOO_SHORT": "Sitename muss mindesten 4 Zeichen enthalten",
  "SITE_NAME_TOO_LONG": "Sitename musst weniger als 20 Zeichen enthalten",
  "SITE_NAME_EXISTS_SUGGEST": "Dieser Sitename existiert bereits- Wie w盲re es mit:",
  "SAVE_CONTINUE_EDIT_BUTTON": "Mit der Bearbeitung fortfahren",
  "MUST_SAVE_BEFORE_PUBLISH": "Sie m眉ssen Ihre Site speichern bevor Sie upgraden",
  "SAVE_DIALOG_CONTINUE_EDIT_LINK": "Danke, nicht jetzt",
  "SAVE_SUCCESS_MAIN_LABEL_WEB": "Sie haben Ihre Site erfolgreich gespeichert!",
  "SAVE_SUCCESS_MAIN_LABEL_FB": "Sie haben Ihre Seite erfolgreich gespeichert!",
  "SAVE_SUCCESS_PREVIEW_BUTTON": "Vorschau?",
  "SAVE_SUCCESS_PUBLISH_BUTTON_WEB": "Publizieren Sie Ihre Site jetzt",
  "SAVE_SUCCESS_PUBLISH_BUTTON_FB": "Publizieren Sie Ihre Seite jetzt",
  "SAVE_SUCCESS_CONTINUE_EDIT_BUTTON": "Mit der Bearbeitung fortfahren",
  "PUBLISH_WEB_MAIN_LABEL_FIRSTTIME": "Sie sind dabei, Ihre Website LIVE zu publizieren",
  "PUBLISH_WEB_MAIN_LABEL_NOT_FIRSTTIME": "Sie sind dabei, Ihre LIVE Website zu aktualisieren",
  "PUBLISH_WEB_URL_LABEL": "Ihre Site wird unter folgender Adresse zu sehen sein: ",
  "PUBLISH_WEB_SEO_LABEL": "Wichtig! Definieren Sie die Art und Weise, wie Ihre Site in Suchmaschinen wie Google erscheint BEVOR Sie Ihre Site zum ersten Mal publizieren",
  "PUBLISH_WEB_SEO_TITLE_EXAMPLE": "z.B: Johan Schmidt Hochzeitsfotografie",
  "PUBLISH_WEB_SEO_DESCRIPTION_EXAMPLE": "z.B. Johan Schmidt Hochzeitsfotografie bietet Ihnen professionelle Fotografie f眉r Ihren Hochzeitstag an",
  "PUBLISH_WEB_SEO_KEYWORDS_EXAMPLE": "z.B. Hochzeit, professionell, Fotografie, Fotograf",
  "PUBLISH_WEB_PUBLISH_NOW_BUTTON": "Jetzt publizieren",
  "PUBLISH_WEB_OPTIMIZE_SEO_LABEL": "Optimieren Sie Ihre SEO Einstellungen",
  "PUBLISH_WEB_OPTIMIZE_SEO_POSTFIX": "und erhalten Sie mehr Traffic.",
  "PUBLISH_WEB_UPDATE_BUTTON": "Aktualisieren",
  "PUBLISH_FB_MAIN_LABEL_FIRSTTIME": "Publizieren Sie Ihre Seite",
  "PUBLISH_FB_MAIN_LABEL_NOT_FIRSTTIME": "Sie sind dabei, Ihre LIVE Seite zu aktualisieren",
  "PUBLISH_FB_SETUP_FB_PREFIX": "Bereit zu publizieren? Stellen Sie sicher, dass Sie eine Facebook-Seite eingerichtet haben. Wenn nicht, ",
  "PUBLISH_FB_SETUP_FB_LINK": "脰ffnen Sie eine hier",
  "PUBLISH_FB_SETUP_FB_POSTFIX": "Nach dem Publizieren werden Sie zu Facebook weitergeleitet, um unsere Facebook Anwendung zu installieren.",
  "PUBLISH_FB_AUTOMATIC_CHANGE_LABEL": "Ihre Facebook Seite wird automatisch ge盲ndert, wenn diese Wix Seite zur Zeit auf Ihrer Facebook Seite angezeigt wird",
  "PUBLISH_FB_PUBLISH_BUTTON_FIRSTTIME": "Publizieren Sie meine Facebook-Seite",
  "PUBLISH_FB_PUBLISH_BUTTON_NOT_FIRSTTIME": "Aktualisieren",
  "PUBLISH_FB_HELP_SET_FB_PREFIX": "Brauchen Sie Hilfe, um Ihre Facebook Seite einzurichten?",
  "PUBLISH_FB_HELP_SET_FB_LINK": "Klicken Sie hier",
  "PUBLISH_FB_MORE_INFO_PREFIX": "F眉r mehr Informationen besuchen Sie unsere",
  "PUBLISH_FB_MORE_INFO_LINK": "Supportseite",
  "PUBLISH_WEB_SUCCESS_MAIN_LABEL": "Sie haben Ihre Site erfolgreich publiziert!",
  "PUBLISH_WEB_SUCCESS_URL_LABEL": "Ihre Site wurde publiziert und ist unter folgender Adresse sichtbar: ",
  "PUBLISH_WEB_SUCCESS_PREVIEW_BUTTON": "Live Site ansehen",
  "PUBLISH_WEB_SUCCESS_YOR_OWN_DOMAIN_LABEL": "Erhalten Sie jetzt Ihre GRATIS Domain",
  "PUBLISH_WEB_SUCCESS_RMV_WIX_ADS": "Die gesamte Werbung von Wix entfernen",
  "PUBLISH_WEB_SUCCESS_UPGRADE_FEATURES": "Erhalten Sie jetzt Ihre GRATIS Domain<br/> Entfernen Sie die Werbung von Wix",
  "PUBLISH_WEB_SUCCESS_UPGRADE_BUTTON": "JETZT UPGRADEN",
  "PUBLISH_WEB_SUCCESS_PROMOTE_BUTTON_LABEL": "Promoten Sie Ihre Site mit einer beeindruckenden<br/> Facebook Seite",
  "PUBLISH_WEB_SUCCESS_PROMOTE_BUTTON": "ERSTELLEN",
  "PUBLISH_WEB_SUCCESS_MOBILE_BUTTON_LABEL": "Erstellen Sie in f眉nf Minuten eine Mobile Site",
  "PUBLISH_WEB_SUCCESS_MOBILE_BUTTON": "GO MOBILE",
  "PUBLISH_WEB_SUCCESS_CONTINUE_EDIT_LINK": "Nicht jetzt, danke",
  "PUBLISH_WEB_SUCCESS_FB_CREATED": "Eine Facebook-Seite wurde erstellt",
  "PUBLISH_WEB_SUCCESS_MOBILE_CREATED": "Eine Mobile Site wurde erstellt!",
  "PUBLISH_FB_SUCCESS_MAIN_LABEL": "Sie habe Ihre Seite erfolgreich publiziert!",
  "PUBLISH_FB_SUCCESS_SUB_LABEL_FIRSTTIME": "Ihre Seite von Wix kann nun auf Ihrer Facebook-Seite angezeigt werden.",
  "PUBLISH_FB_SUCCESS_SUB_LABEL_NOT_FIRSTTIME": "Ihre Seite wurde aktualisiert.",
  "PUBLISH_FB_SUCCESS_RMV_WIX_ADS": "Entfernen Sie die Werbung von Wix",
  "PUBLISH_FB_SUCCESS_UPGRADE_BUTTON": "JETZT UPGRADEN",
  "PUBLISH_FB_SUCCESS_CREATE_WEBSITE_BUTTON_LABEL": "Erstellen Sie eine beeindruckende Website",
  "PUBLISH_FB_SUCCESS_CREATE_WEBSITE_BUTTON": "Erstellen",
  "PUBLISH_FB_SUCCESS_MOBILE_BUTTON_LABEL": "Erstellen Sie in f眉nf Minuten eine Mobile Site",
  "PUBLISH_FB_SUCCESS_MOBILE_BUTTON": "GO MOBILE",
  "PUBLISH_FB_SUCCESS_CONTINUE_EDIT_LINK": "Nicht jetzt, danke",
  "PUBLISH_FB_WEBSITE_CREATED": "Die Website wurde erstellt!",
  "PUBLISH_FB_MOBILE_SITE_CREATED": "Eine Mobile Site wurde erstellt",
  "PUBLISH_WEB_SHARE_MAIN_LABEL": "Verbreiten Sie die Nachricht 眉ber Ihre Site!",
  "PUBLISH_WEB_SHARE_SUB_LABEL": "Unten finden Sie zwei MUSS Wege, um mehr Besucher f眉r Ihre Site zu gewinnen: ",
  "PUBLISH_WEB_SHARE_FACEBOOK_BUTTON_LABEL": "Auf Facebook posten",
  "PUBLISH_WEB_SHARE_FACEBOOK_BUTTON": "Auf Facebook teilen",
  "PUBLISH_WEB_SHARE_TWITTER_BUTTON_LABEL": "Tweet in Twitter",
  "PUBLISH_WEB_SHARE_TWITTER_BUTTON": "Tweet in Twitter",
  "PUBLISH_WEB_SHARE_CONTINUE_EDIT_LINK": "Danke, nicht jetzt. Ich m枚chte mit der Bearbeitung fortfahren",
  "PUBLISH_WEB_SHARE_MY_ACCOUNT": "Gehen Sie zu Mein Konto",
  "PUBLISH_WEB_SHARE_FB_MSG_FIRSTTIME": "Wix gibt es jetzt in HTML! Schauen Sie sich meine neue Site an, die ich mit Wix erstellt habe! Erstellen auch Sie Ihre eigene Website. Es ist einfach und kostenlos!",
  "PUBLISH_WEB_SHARE_FB_MSG_NOT_FIRSTTIME": "Schauen Sie sich meine Website an! Ich habe sie gerade mit Wix.com",
  "PUBLISH_WEB_SHARE_TW_MSG_FIRSTTIME": "Schauen Sie sich die Site an, die ich mit Wix erstellt habe: ",
  "PUBLISH_WEB_SHARE_TW_MSG_NOT_FIRSTTIME": "Schauen Sie sich meine Website an! Ich habe sie gerade mit Wix.com",
  "TWITTER_CHECK_OUT_MY_SITE_MSG_NON_PREMIUM": "Check%20out%20my%20@Wix%20site",
  "TWITTER_CHECK_OUT_MY_SITE_MSG_PREMIUM": "Check%20out%20my%20site",
  "TWITTER_RELATED_WIX_ACCOUNTS": "Wix,WixLounge,WixLoungeSf",
  "DAY_SUNDAY": "Sonntag",
  "DAY_MONDAY": "Montag",
  "DAY_TUESDAY": "Dienstag",
  "DAY_WEDNESDAY": "Mittwoch",
  "DAY_THURSDAY": "Donnerstag",
  "DAY_FRIDAY": "Freitag",
  "DAY_SATURDAY": "Samstag",
  "MONTH_1": "Januar",
  "MONTH_2": "Februar",
  "MONTH_3": "M盲rz",
  "MONTH_4": "April",
  "MONTH_5": "Mai",
  "MONTH_6": "Juni",
  "MONTH_7": "Juli",
  "MONTH_8": "August",
  "MONTH_9": "September",
  "MONTH_10": "Oktober",
  "MONTH_11": "November",
  "MONTH_12": "Dezember",
  "mobile.core.components.Container": "Container",
  "wysiwyg.viewer.components.GoogleMap": "Google Map",
  "wysiwyg.viewer.components.TwitterFeed": "Twitter Feed",
  "wysiwyg.viewer.components.WTwitterTweet": "Twitter Tweet",
  "wysiwyg.viewer.components.WFacebookLike": "Facebook \"Gef盲llt mir\"",
  "wysiwyg.viewer.components.WTwitterFollow": "Twitter Follow",
  "wysiwyg.viewer.components.WGooglePlusOne": "Google +1",
  "wysiwyg.viewer.components.FlickrBadgeWidget": "Flickr Badge",
  "wysiwyg.viewer.components.WFacebookComment": "Facebook Kommentar",
  "wysiwyg.viewer.components.VerticalLine": "Vertikale Linie",
  "wysiwyg.viewer.components.FooterContainer": "Fu脽leiste",
  "wysiwyg.viewer.components.HeaderContainer": "Kopfzeile",
  "wysiwyg.viewer.components.PagesContainer": "Seiten",
  "mobile.core.components.Page": "Seite",
  "mobile.core.components.PhotoGalleryGrid": "Matrix Bildgalerie",
  "wysiwyg.viewer.components.WImage": "Bild",
  "wysiwyg.viewer.components.ClipArt": "Clipart",
  "wysiwyg.viewer.components.HorizontalMenu": "Men眉",
  "wysiwyg.viewer.components.EbayItemsBySeller": "eBay",
  "wysiwyg.viewer.components.ContactForm": "Kontaktformular",
  "wysiwyg.viewer.components.Video": "Video",
  "wysiwyg.viewer.components.FlashComponent": "Flash",
  "wysiwyg.viewer.components.__ComponentPlaceHolder__": "__ComponentPlaceHolder__",
  "wysiwyg.viewer.components.FiveGridLine": "Linie",
  "wysiwyg.viewer.components.ScreenWidthContainer": "Streifen",
  "wysiwyg.viewer.components.MatrixGallery": "Raster",
  "wysiwyg.viewer.components.PaginatedGridGallery": "Animiertes Raster",
  "wysiwyg.viewer.components.SlideShowGallery": "Diashow",
  "wysiwyg.viewer.components.SliderGallery": "Slider",
  "wysiwyg.viewer.components.LinkBar": "Soziale Netzwerkleiste",
  "wysiwyg.viewer.components.PayPalButton": "PayPal",
  "wysiwyg.viewer.components.SiteButton": "Button",
  "wysiwyg.viewer.components.AdminLoginButton": "Admin/Webmaster Login",
  "SETTINGS_PANEL_TITLE": "Einstellungen",
  "SETTINGS_PANEL_DESCRIPTION": "脛ndern Sie Ihre Site Einstellungen inklusive SEO und Statistiken",
  "SETTINGS_PANEL_DESCRIPTION_FB_MODE": "脛ndern Sie die Einstellungen Ihrer Site",
  "BACK_TO": "Zur眉ck zu",
  "GROUP_COLLAPSE": "Herabfallen",
  "GROUP_EXPAND": "Ausdehnen",
  "SITE_NAME": "Site-Adresse",
  "FAVICON_AND_THUMBNAIL": "Favicon & Thumbnail",
  "ONLY_THUMBNAIL": "Thumbnail",
  "SEO": "SEO (Google)",
  "STATISTICS": "Statistiken",
  "SWITCH_THEME": "Thema wechseln",
  "BACKGROUND": "Hintergrund",
  "COLORS": "Farben",
  "ADVANCED_STYLES": "Fortgeschrittene Stile",
  "ADVANCED_STYLES_DESCRIPTION": "Sie k枚nnen Farben, R盲nder, Rahmen und Ecken personalisieren und 盲ndern.",
  "FONTS": "Fonts",
  "MASTER_COMPONENT_TITLE": "Hinzuf眉gen",
  "TEXT": "Text",
  "IMAGE": "Bild",
  "MEDIA": "Medien",
  "WIDGETS": "AddOn",
  "SOCIAL": "Soziale Netzwerke",
  "GALLERY_COMP": "Galerie",
  "BUTTONS_AND_MENUS": "Buttons & Men眉s",
  "AREAS": "Formen & Linien",
  "BOX": "Box",
  "LINE": "Linie",
  "NAVIGATION": "Navigation",
  "ADD_ON": "Add On",
  "BLOG": "Blog",
  "SWITCH_TO_EDITOR_MODE": "Zur眉ck zum Editormodus",
  "EDIT_MODE_TITLE_MASTER": "Masterseitenmodus",
  "EDIT_MODE_TITLE_PREVIEW": "Vorschaumodus",
  "EDIT_MODE_DESCRIPTION_MASTER": "Bearbeiten Sie Elemente, die auf allen Seiten erscheinen",
  "HtmlComponentPanel.stateCombo.external": "Websiteadresse",
  "HtmlComponentPanel.stateCombo.embedded": "HTML Code",
  "HtmlComponentPanel.HtmlMode": "Modus",
  "HtmlComponentPanel.HtmlSource": "Websiteadresse",
  "HtmlComponentPanel.HtmlSourceSample": "http://www.wix.com",
  "HtmlComponentPanel.HtmlCode": "HTML / eingebetteter Code",
  "HtmlComponentPanel.UpdateButton": "Aktualisieren",
  "HtmlComponentPanel.Loading": "Bitte warten Sie...",
  "HtmlComponentPanel.InvalidUrl": "Bitte geben Sie eine g眉litge Siteadresse ein",
  "HtmlComponentPanel.Errors.NotLoggedIn": "Bitte loggen Sie sich ein",
  "HtmlComponentPanel.Errors.UnableToStoreHtml": "HTML kann zur Zeit nicht abgespeichert werden, bitte versuchen Sie es sp盲ter noch einmal",
  "HtmlComponentPanel.Errors.HtmlCannotBeRetrieved": "HTML kann zur Zeit nicht angezeigt werden, bitte versuchen Sie es sp盲ter",
  "Types.GoogleMapProperties.mapType.ROADMAP": "Normal",
  "Types.GoogleMapProperties.mapType.SATELLITE": "Satellit",
  "Types.GoogleMapProperties.mapType.HYBRID": "Hybrid",
  "Types.GoogleMapProperties.mapType.TERRAIN": "Gel盲nde",
  "Types.FlashComponentProperties.displayMode.fit": "Anpassen",
  "Types.FlashComponentProperties.displayMode.stretch": "Strecken",
  "Types.FlashComponentProperties.displayMode.original": "Original Gr枚脽e",
  "Types.PayPalButtonProperties.buttonType.buy": "Jetzt kaufen",
  "Types.PayPalButtonProperties.buttonType.donate": "Spenden",
  "Types.PayPalButtonProperties.target._self": "Selbes Fenster",
  "Types.PayPalButtonProperties.target._blank": "Neues Fenster",
  "Types.PayPalButtonProperties.currencyCode.USD": "US Dollar",
  "Types.PayPalButtonProperties.currencyCode.GBP": "Britisches Pfund",
  "Types.PayPalButtonProperties.currencyCode.NIS": "Neuer Israelischer Schekel",
  "Types.WPhotoProperties.displayMode.fitWidth": "Anpassen",
  "Types.WPhotoProperties.displayMode.stretch": "Strecken",
  "Types.WPhotoProperties.displayMode.full": "Zentrieren",
  "Types.WPhotoProperties.displayMode.fill": "Zuschneiden",
  "EbayItemsBySellerPanel.sellerId": "Verk盲ufer ID",
  "EbayItemsBySellerPanel.sellerId.placeholder": "Ihre eBay ID",
  "EbayItemsBySellerPanel.sellerId.button": "Aktualisieren",
  "EbayItemsBySellerPanel.headerImage": "Kopfleistenbild",
  "EbayItemsBySellerPanel.checkingUser": "Benutzer best盲tigen...",
  "EbayItemsBySellerPanel.Errors.userDoesNotExist": "eBay erkennt diesen Benutzernamen nicht",
  "ContactFormPanel.emailTo": "Email an: ",
  "ContactFormPanel.emailTo.tip": "Ihre Emailadresse:",
  "ContactFormPanel.emailBcc": "Email Bcc:",
  "ContactFormPanel.helplet": "Vergessen Sie nicht, Ihre Emailadresse hinzuzuf眉gen! Ihr Kontaktformular wird nicht funktionieren, wenn Sie Ihre Emailadresse nicht in den Einstellungen eintragen.",
  "Types.WTwitterTweetProperties.dataCount.none": "Einfach",
  "Types.WTwitterTweetProperties.dataCount.horizontal": "Z盲hler rechts",
  "Types.WTwitterTweetProperties.dataCount.vertical": "Z盲hler oben",
  "Types.VideoProperties.showControls.always_show": "Anzeigen",
  "Types.VideoProperties.showControls.always_hide": "Ausblenden",
  "Types.VideoProperties.showControls.temp_show": "Automatisch ausblenden",
  "Types.WFacebookLikeProperties.layout.standard": "Einfach",
  "Types.WFacebookLikeProperties.layout.button_count": "Z盲hler rechts",
  "Types.WFacebookLikeProperties.layout.box_count": "Z盲hler oben",
  "Types.WFacebookLikeProperties.action.like": "\"Gef盲llt mir\"",
  "Types.WFacebookLikeProperties.action.recommend": "Empfohlen",
  "Types.WFacebookLikeProperties.colorScheme.light": "Hell",
  "Types.WFacebookLikeProperties.colorScheme.dark": "Dunkel",
  "Types.WFacebookCommentProperties.colorScheme.light": "Hell",
  "Types.WFacebookCommentProperties.colorScheme.dark": "Dunkel",
  "Types.WGooglePlusOneProperties.size.small": "Klein",
  "Types.WGooglePlusOneProperties.size.medium": "Mittel",
  "Types.WGooglePlusOneProperties.size.standard": "Standard",
  "Types.WGooglePlusOneProperties.size.tall": "Breite",
  "Types.WGooglePlusOneProperties.annotation.none": "Einfach",
  "Types.WGooglePlusOneProperties.annotation.bubble": "Mit Z盲hler",
  "Types.WGooglePlusOneProperties.annotation.inline": "Minimal",
  "Types.MatrixGalleryProperties.imageMode.clipImage": "Zuschneiden",
  "Types.MatrixGalleryProperties.imageMode.flexibleWidthFixed": "Anpassen",
  "Types.PaginatedGridGalleryProperties.transition.none": "Keine",
  "Types.PaginatedGridGalleryProperties.transition.seq_crossFade_All": "脺berblendung",
  "Types.PaginatedGridGalleryProperties.transition.seq_shrink_All": "Kleiner machen",
  "Types.PaginatedGridGalleryProperties.transition.swipe_horiz_All": "Horinzontal",
  "Types.PaginatedGridGalleryProperties.transition.swipe_vert_All": "Vertikal",
  "Types.PaginatedGridGalleryProperties.transition.seq_random": "Zuf盲llig",
  "Types.SlideShowGalleryProperties.imageMode.clipImage": "Zuschneiden",
  "Types.SlideShowGalleryProperties.imageMode.flexibleHeight": "An Breite anpassen",
  "Types.SliderGalleryProperties.imageMode.clipImage": "Zuschneiden",
  "Types.SliderGalleryProperties.imageMode.flexibleWidth": "An die H枚he anpassen",
  "Types.ButtonProperties.align.left": "Links",
  "Types.ButtonProperties.align.center": "Zentriert",
  "Types.ButtonProperties.align.right": "Rechts",
  "Types.SlideShowGalleryProperties.transition.swipeHorizontal": "Horinzontal",
  "Types.SlideShowGalleryProperties.transition.swipeVertical": "Vertikal",
  "Types.SlideShowGalleryProperties.transition.crossfade": "脺berblenden",
  "Types.SlideShowGalleryProperties.transition.outIn": "Raus & Rein",
  "Types.SlideShowGalleryProperties.transition.none": "Keine",
  "Types.SliderGalleryProperties.aspectRatioPreset.16:9": "16:9",
  "Types.SliderGalleryProperties.aspectRatioPreset.4:3": "4:3",
  "Types.SliderGalleryProperties.aspectRatioPreset.1:1": "1:1",
  "Types.SliderGalleryProperties.aspectRatioPreset.3:4": "3:4",
  "Types.SliderGalleryProperties.aspectRatioPreset.9:16": "9:16",
  "COMP_PagesContainer": "Seiten",
  "COMP_Page": "Seite Einstellungen",
  "COMP_HorizontalMenu": "Men眉 Einstellungen",
  "COMP_SiteButton": "Button Einstellungen",
  "COMP_DropDownMenu": "Men眉 Einstellungen",
  "COMP_AdminLoginButton": "Admin/Webmaster Login",
  "COMP_WRichText": "Text Einstellungen",
  "COMP_Container": "Box Einstellungen",
  "COMP_PhotoGalleryGrid": "Galerie Einstellungen",
  "COMP_GoogleMap": "Google Maps",
  "COMP_FiveGridLine": "Linien Einstellungen",
  "COMP_VerticalLine": "Linie Einstellungen",
  "COMP_PayPalButton": "PayPal Einstellungen",
  "COMP_WPhoto": "Bild Einstellungen",
  "COMP_FlashComponent": "Flash Einstellungen",
  "COMP_ScreenWidthContainer": "Strip Einstellungen",
  "COMP_WFacebookLike": "Facebook \"Gef盲llt mir\"",
  "COMP_WFacebookComment": "Facebook Kommentare",
  "COMP_WGooglePlusOne": "Google +1 Button",
  "COMP_SoundCloudWidget": "SoundCloud",
  "COMP_WTwitterTweet": "Twitter Tweet Button",
  "COMP_TwitterFeed": "Twitter Feed",
  "COMP_WTwitterFollow": "Twitter Follow Button",
  "COMP_SlideShowGallery": "Diashowgalerie Einstellungen",
  "COMP_MatrixGallery": "Grid-Galerie Einstellungen",
  "COMP_PaginatedGridGallery": "Animierte Grid-Galerie",
  "COMP_SliderGallery": "Slidergalerie Einstellungen",
  "COMP_LinkBar": "Soziale Netzwerkleiste",
  "COMP_HtmlComponent": "HTML Einstellungen",
  "COMP_HeaderContainer": "Kopfzeile",
  "COMP_FooterContainer": "Fu脽leiste",
  "COMP_Video": "Video",
  "COMP_ClipArt": "Clipart Einstellungen",
  "COMP_ContactForm": "Kontaktformular Einstellungen",
  "COMP_RichText": "Text Einstellungen",
  "COMP_ServiceList": "Serviceliste Einstellungen",
  "COMP_EbayItemsBySeller": "eBay",
  "COMP_FlickrBadgeWidget": "Flickr Galerie",
  "COMP_MultiSelectProxy": "Ausrichten und anordnen",
  "FPP_PagesContainer": "Seiten",
  "FPP_Page": "Seite",
  "FPP_HorizontalMenu": "Men眉",
  "FPP_SiteButton": "Button",
  "FPP_AdminLoginButton": "Admin/Webmaster Login",
  "FPP_WRichText": "Text",
  "FPP_Container": "Box",
  "FPP_PhotoGalleryGrid": "Galerie",
  "FPP_GoogleMap": "Google Maps",
  "FPP_FiveGridLine": "Linie",
  "FPP_VerticalLine": "Linie",
  "FPP_PayPalButton": "PayPal",
  "FPP_WPhoto": "Bild",
  "FPP_FlashComponent": "Flash",
  "FPP_ScreenWidthContainer": "Strip",
  "FPP_WFacebookLike": "Facebook \"Gef盲llt mir\"",
  "FPP_WFacebookComment": "Facebook Kommentare",
  "FPP_WGooglePlusOne": "Google +1 Button",
  "FPP_SoundCloudWidget": "SoundCloud",
  "FPP_WTwitterTweet": "Twitter Tweet Button",
  "FPP_TwitterFeed": "Twitter Feed",
  "FPP_WTwitterFollow": "Twitter Follow Button",
  "FPP_SlideShowGallery": "Diashogalerie",
  "FPP_MatrixGallery": "Grid-Galerie",
  "FPP_PaginatedGridGallery": "Animierte Grid-Galerie",
  "FPP_SliderGallery": "Slidergalerie",
  "FPP_LinkBar": "Soziale Netzwerkleiste",
  "FPP_HtmlComponent": "HTML",
  "FPP_HeaderContainer": "Header",
  "FPP_FooterContainer": "Fu脽leiste",
  "FPP_Video": "Video",
  "FPP_ClipArt": "Clipart",
  "FPP_ContactForm": "Kontaktformular",
  "FPP_RichText": "Text",
  "FPP_ServiceList": "Serviceliste",
  "FPP_EbayItemsBySeller": "eBay",
  "FPP_FlickrBadgeWidget": "Flickr Galerie",
  "FPP_MultiSelectProxy": "Anpassen & Anordnen",
  "COMP_DESC_PagesContainer": "脛ndern Sie die Farbe und den Stil der aktuellen Seite Ihrer Website. ",
  "COMP_DESC_HorizontalMenu": "Wir haben ein neues Men眉 hinzugef眉gt, das eine Dropdown-Funktion beinhaltet. Um dieses zu benutzen, l枚schen Sie einfach dieses Men眉 und w盲hlen Sie ein neues aus Hinzuf眉gen > Buttons & Men眉s aus.",
  "COMP_DESC_DropDownMenu": "Gehen Sie zu Seiten, um durch Ihre Seite zu navigieren, sie neu zu ordnen oder Unterseiten zu erstellen. Klicken Sie auf Vorschau, um zu sehen, wie Ihr Men眉 online aussehen wird.",
  "COMP_DESC_SiteButton": "F眉gen Sie Text und einen Link zu Ihrem Button hinzu. 脛ndern Sie den Stil Ihrem Geschmack entsprechend.",
  "COMP_DESC_AdminLoginButton": "Erhalten Sie mit dem Admin/Webmaster Login einfachen und direkten Zugang zu Ihrem Editor direkt von Ihrer eigenen Website aus (benutzen Sie Ihr Wix Passwort) ",
  "COMP_DESC_WRichText": "Klicken Sie doppelt auf die Textbox, um Ihren Inhalt hinzuzuf眉gen und zu bearbeiten oder klicken Sie auf Text bearbeiten. Um das Fontschema Ihrer Site zu 盲ndern, gehen Sie zu Design > Fonts.",
  "COMP_DESC_Container": "脛ndern Sie die Farbe und den Stil der Box und f眉gen Sie Texte und Bilder hinzu.",
  "COMP_DESC_PayPalButton": "F眉gen Sie einen PayPal Button hinzu und erm枚glichen Sie Ihren Kunden zu spenden oder Artikel direkt auf Ihrer Website zu kaufen.",
  "COMP_DESC_GoogleMap": "F眉gen Sie Ihrer Site eine Google Map hinzu. Geben Sie einfach Ihre Adresse ein. Suchen Sie den Standort und benennen Sie diesen unter Beschreibung. Nachdem Ihre Karte fertig ist, k枚nnen Sie diese anbringen, wo Sie m枚chten.",
  "COMP_DESC_FiveGridLine": "W盲hlen Sie Ihren Linien Stil und passen ihn an.",
  "COMP_DESC_VerticalLine": "W盲hlen Sie Ihren Linien Stil und passen ihn an. ",
  "COMP_DESC_WPhoto": "Laden Sie Ihr eigenes Bild hoch und passen Sie es an. F眉gen Sie Alt Text und Tooltips hinzu, um Ihr SEO aufzupeppen. ",
  "COMP_DESC_FlashComponent": "Laden Sie Ihr eigenes Flash Element hoch und f眉gen Sie es auf Ihrer HTML Site hinzu.",
  "COMP_DESC_ScreenWidthContainer": "Eine Box, die sich an die gesamte Breite Ihrer Website anpasst. Passen Sie den Stil an und f眉gen Sie Text und Bilder hinzu.",
  "COMP_DESC_WFacebookLike": "Lassen Sie Ihre Besucher den \"Gef盲llt mir\" Button f眉r Ihre Seite klicken und Ihre Seite auf ihren Facebook Profilen teilen. ",
  "COMP_DESC_WFacebookComment": "Lassen Sie Kommentare auf Ihrer Site und auf den Facebook Profilen Ihrer Kommentarschreiber erscheinen.",
  "COMP_DESC_WGooglePlusOne": "Lassen Sie Ihre Besucher Ihre Website in ihren Google+ Kreisen teilen.",
  "COMP_DESC_SoundCloudWidget": "F眉gen Sie Ihrer Site Ihre Lieblingsmusik hinzu, indem Sie den eingebetteten Soundcloud Player benutzen. Sie finden Ihre Musik unter http://www.soundcloud.com",
  "COMP_DESC_WTwitterTweet": "Lassen Sie Ihre Besucher einen Link zu Ihrer Site auf ihren Twitter Feed mit dem Inhalt teilen, den <i>Sie<i> m枚chten. ",
  "COMP_DESC_TwitterFeed": "F眉gen Sie Ihrer Site Ihren Twitter Feed hinzu und zeigen Sie Ihren Besuchern Ihre Tweets.",
  "COMP_DESC_WTwitterFollow": "Laden Sie Ihre Besucher ein, Ihnen auf Twitter zu folgen. ",
  "COMP_DESC_SlideShowGallery": "Zeigen Sie je eine Bild in Ihrer Diashow Galerie an. Um Ihre eigenen Bilder hinzuzuf眉gen, klicken Sie auf Bilder ordnen.",
  "COMP_DESC_MatrixGallery": "Zeigen Sie viele Bilder auf einmal in einer Rasterformation an. Um Ihre eigenen Bilder hinzuzuf眉gen, klicken Sie auf Bilder ordnen.  ",
  "COMP_DESC_PaginatedGridGallery": "Zeigen Sie viele Bilder auf einmal in einer Rasterformatierung an. Um Ihre eigenen Bilder hinzuzuf眉gen, klicken Sie auf Bilder ordnen.",
  "COMP_DESC_SliderGallery": "Zeigen Sie Ihre Bilder in einer dynamischen Galerie mit einer horizontalen Schiebebewegung an. Um Ihre eigenen Bilder hinzuzuf眉gen, klicken Sie auf Bilder ordnen.",
  "COMP_DESC_LinkBar": "F眉gen Sie Links zu Ihren Facebook, Twitter und Google + Profilen in einer Leiste hinzu.",
  "COMP_DESC_SocialBar": "",
  "COMP_DESC_HtmlComponent": "F眉gen Sie beliebigen Inhalt auf Ihrer Site hinzu. Sie k枚nnen eine Webadresse einbetten oder Ihren eigenen HTML Code schreiben.",
  "COMP_DESC_HeaderContainer": "F眉gen Sie Ihren Titel und Ihr Men眉 in der Kopfleiste hinzu, so dass diese auf allen Ihren Seiten erscheinen. Klicken Sie auf Stil 盲ndern, um den Stil und die Farbe zu 盲ndern. ",
  "COMP_DESC_FooterContainer": "F眉gen Sie Ihrer Fu脽leiste Elemente hinzu, die auf allen Seiten Ihrer Website erscheinen sollen. Klicken Sie auf Stil 盲ndern, um den Stil und die Farbe zu 盲ndern.",
  "COMP_DESC_Video": "Teilen Sie Ihre YouTube oder Vimeo Videos auf Ihrer Website.",
  "COMP_DESC_ClipArt": "F眉gen Sie Symbole und lustige Bilder aus der Clipart Galerie hinzu, um Ihrer Site das gewisse Etwas zu verleihen.",
  "COMP_DESC_ContactForm": "Lassen Sie Ihre Kunden Sie erreichen. Geben Sie Ihre Emailadresse in das vorgegebene Feld ein. Sie k枚nnen den Stil Ihres Kontaktformulars 盲ndern. ",
  "COMP_DESC_RichText": "Klicken Sie doppelt auf die Textbox, um Ihren Inhalt hinzuzuf眉gen oder zu bearbeiten oder klicken Sie auf Text bearbeiten. Um das Fontschema Ihrer Site zu 盲ndern, gehen Sie zu Design > Fonts.",
  "COMP_DESC_EbayItemsBySeller": "F眉gen Sie Ihrer Site einen eBay Shop hinzu.",
  "COMP_DESC_FlickrBadgeWidget": "Teilen Sie eine Galerie Ihrer Flickr Bilder auf Ihrer Site.",
  "COMP_DESC_MultiSelectProxy": "Ordnen Sie mehrere Elemente zusammen an. Sie k枚nnen auch alle ausgew盲hlten Elemente an eine Gr枚脽e anpassen und gew盲hrleisten, dass diese gleichm盲脽ig auf Ihrer Seite angeordnet werden.",
  "BACKGROUND_REPEAT": "Kachel",
  "BACKGROUND_REPEAT_NONE": "Normal",
  "BACKGROUND_REPEAT_X": "Kachel horizontal",
  "BACKGROUND_REPEAT_Y": "Kachel vertikal",
  "BACKGROUND_CONTAIN": "Anpassen",
  "BACKGROUND_COVER": "Vollbild",
  "BACKGROUND_SCROLL": "Scrollen",
  "BACKGROUND_FIXED": "Erledigt",
  "BACKGROUND_LABEL_IMAGE": "Bild 盲ndern",
  "BACKGROUND_LABEL_REPEAT": "Bildskalierung",
  "BACKGROUND_LABEL_ALIGN": "Position",
  "BACKGROUND_LABEL_SCROLL": "Den Hintergrund mit der Website scrollen",
  "BACKGROUND_LABEL_COLOR": "Farbe hinter dem Bild",
  "BACKGROUND_BUTTON_COLOR": "Farben 盲ndern",
  "LINK_NAVIGATE_DIALOG_TITLE": "Link geklickt",
  "LINK_NAVIGATE_DIALOG_TEXT": "Sie haben auf einen Link geklickt, der normalerweise zu einer anderen Website im selben Tab f眉hrt. Dieses Verhalten wird im Bearbeitungsmodus blockiert.",
  "LINK_NAVIGATE_DIALOG_DETAILS": "Wenn Sie zu diesem Link in einem neuen Tab navigieren m枚chten, klicken Sie auf Ja, wenn nicht, dann klicken Sie auf Nein",
  "FONT_DIALOG_TITLE": "Font Picker",
  "FONT_FAMILY_LABEL": "Font",
  "FONT_STYLE_LABEL": "Zeichen",
  "FONT_SAMPLE_PARAGRAPH": "Paragraf",
  "FONT_0_LABEL": "Titel",
  "FONT_1_LABEL": "Men眉",
  "FONT_2_LABEL": "Seitentitel",
  "FONT_3_LABEL": "Heading XL",
  "FONT_4_LABEL": "Heading L",
  "FONT_5_LABEL": "Heading M",
  "FONT_6_LABEL": "Heading S",
  "FONT_7_LABEL": "Body L",
  "FONT_8_LABEL": "Body M",
  "FONT_9_LABEL": "Body S",
  "FONT_10_LABEL": "Body XS",
  "FONT_0_NAME": "H1",
  "FONT_1_NAME": "H2",
  "FONT_2_NAME": "H3",
  "FONT_3_NAME": "H4",
  "FONT_4_NAME": "",
  "FONT_5_NAME": "",
  "FONT_6_NAME": "",
  "FONT_7_NAME": "",
  "FONT_8_NAME": "",
  "FONT_9_NAME": "",
  "FONT_10_NAME": "",
  "COMPONENT_STYLE_rt1": "Text Men眉",
  "COMPONENT_STYLE_rt2": "Button Men眉",
  "COMPONENT_STYLE_rt3": "Zus盲tzliches Men眉",
  "COMPONENT_STYLE_ddm1": "Textmen眉",
  "COMPONENT_STYLE_ddm2": "Buttonmen眉",
  "COMPONENT_STYLE_ddm3": "Zus盲tzliches Men眉",
  "COMPONENT_STYLE_p1": "Homepage",
  "COMPONENT_STYLE_p2": "Standard",
  "COMPONENT_STYLE_p3": "Spezial",
  "COMPONENT_STYLE_wp1": "Standard",
  "COMPONENT_STYLE_wp2": "Kein Rahmen",
  "COMPONENT_STYLE_wp3": "Spezialrahmen 1",
  "COMPONENT_STYLE_wp4": "Spezialrahmen 2",
  "COMPONENT_STYLE_mg1": "Standard",
  "COMPONENT_STYLE_mg2": "Kein Rahmen",
  "COMPONENT_STYLE_mg3": "Rahmen",
  "COMPONENT_STYLE_pagg1": "Animierte Galerie Stil 1",
  "COMPONENT_STYLE_pagg2": "Animierte Galerie Stil 2",
  "COMPONENT_STYLE_pagg3": "Animierte Galerie Stil 3",
  "COMPONENT_STYLE_sg1": "Standard",
  "COMPONENT_STYLE_sg2": "Kein Rahmen",
  "COMPONENT_STYLE_sg3": "Rahmen",
  "COMPONENT_STYLE_ssg1": "Standard",
  "COMPONENT_STYLE_ssg2": "Kein Rahmen",
  "COMPONENT_STYLE_ssg3": "Rahmen",
  "COMPONENT_STYLE_c1": "Box Stil 1",
  "COMPONENT_STYLE_c2": "Box Stil 2",
  "COMPONENT_STYLE_c3": "Box Stil 3",
  "COMPONENT_STYLE_c4": "Box Stil 4",
  "COMPONENT_STYLE_sc1": "Strip Stil 1",
  "COMPONENT_STYLE_sc2": "Strip Stil 2",
  "COMPONENT_STYLE_sc3": "Strip Stil 3",
  "COMPONENT_STYLE_sc4": "Strip Stil 4",
  "COMPONENT_STYLE_hc1": "Keine",
  "COMPONENT_STYLE_hc2": "Linie",
  "COMPONENT_STYLE_hc3": "Strip",
  "COMPONENT_STYLE_fc1": "Keine",
  "COMPONENT_STYLE_fc2": "Linie",
  "COMPONENT_STYLE_fc3": "Strip",
  "COMPONENT_STYLE_pc1": "Keine",
  "COMPONENT_STYLE_pc2": "Box",
  "COMPONENT_STYLE_cf1": "Formstil 1",
  "COMPONENT_STYLE_cf2": "Formstil 2",
  "COMPONENT_STYLE_hl1": "Linienstil 1",
  "COMPONENT_STYLE_hl2": "Linienstil 2",
  "COMPONENT_STYLE_hl3": "Linienstil 3",
  "COMPONENT_STYLE_hl4": "Linienstil 4",
  "COMPONENT_STYLE_vl1": "Linie Stil 1",
  "COMPONENT_STYLE_vl2": "Linie Stil 2",
  "COMPONENT_STYLE_vl3": "Linie Stil 3",
  "COMPONENT_STYLE_vl4": "Linie Stil 4",
  "COMPONENT_STYLE_b1": "Standardbutton",
  "COMPONENT_STYLE_b2": "Textbutton",
  "COMPONENT_STYLE_b3": "Gro脽er Button",
  "COMPONENT_STYLE_b4": "Betonungsbutton",
  "COMPONENT_STYLE_lb1": "Soziale Netzwerkleiste",
  "COMPONENT_STYLE_swf": "Flash",
  "COMPONENT_STYLE_vl": "Video",
  "COMPONENT_STYLE_twf1": "Twitter Feed",
  "COMPONENT_STYLE_twt1": "Tweeter Tweet",
  "COMPONENT_STYLE_tf1": "Tweeter Follow",
  "COMPONENT_STYLE_gm1": "Google Maps",
  "COMPONENT_STYLE_eib1": "eBay",
  "COMPONENT_STYLE_htco1": "HTML Komponente",
  "COMPONENT_STYLE_fbc1": "Facebook Kommentar",
  "COMPONENT_STYLE_fbl1": "Facebook \"Gef盲llt mir\"",
  "COMPONENT_STYLE_gp1": "Google +1",
  "COMPONENT_STYLE_ca1": "Clipart",
  "COMPONENT_STYLE_fk1": "Flickr Badge",
  "COMPONENT_STYLE_pp": "PayPal Button",
  "LINK_DIALOG_DEFAULT_TITLE": "Link",
  "LINK_DIALOG_DESCRIPTION": "W盲hlen Sie einen Linktyp aus",
  "LINK_DIALOG_WEB_TITLE": "Mit Webadresse verlinken",
  "LINK_DIALOG_PAGE_TITLE": "Mit Seite verlinken",
  "LINK_DIALOG_DOC_TITLE": "Mit einem Dokument verlinken",
  "LINK_DIALOG_EMAIL_TITLE": "Mit Email verlinken",
  "LINK_DIALOG_LOGIN_TITLE": "Anmelden / Registrieren Fenster",
  "LINK_DIALOG_DEFAULT_DESCRIPTION": "W盲hlen Sie einen Link aus",
  "LINK_DLG_BACK_TO_OPTIONS": "Zur眉ck zu Linkoptionen",
  "LINK_DLG_REMOVE_LINK": "Link entfernen",
  "LINK_DLG_WEB_ADDRESS": "Webadresse",
  "LINK_DLG_PAGE": "Seite",
  "LINK_DLG_EMAIL": "Email",
  "LINK_DLG_DOCUMENT": "Dokument",
  "LINK_DLG_LOGIN": "Anmelden/Registrieren",
  "LINK_DLG_SELECT_PAGE": "Seite w盲hlen: ",
  "LINK_DLG_TYPE_POST_LOGIN_URL": "Post Login weiterleiten an:",
  "LINK_DLG_TYPE_POST_SIGNUP_URL": "Post Registrierung weiterleiten an:",
  "LINK_DLG_TYPE_START_WITH": "Beginnen mit: ",
  "LINK_DLG_TYPE_URL": "Eine Webadresse eingeben:",
  "LINK_DLG_URL_EXAMPLE": "z.B. www.wix.com",
  "LINK_DLG_OPT_OPEN_IN_NEW": "In einem neuen Fenster 枚ffnen",
  "LINK_DLG_OPT_OPEN_IN_SAME": "Im selben Fenster 枚ffnen",
  "LINK_DLG_SELECT_DOC": "Dokument hinzuf眉gen/盲ndern: ",
  "LINK_DLG_TYPE_EMAIL": "Geben Sie eine Emailadresse ein",
  "LINK_DLG_EMAIL_EXAMPLE": "z.B. info@wix.vom ",
  "LINK_DLG_BAD_URL": "Bitte geben Sie eine g眉ltige URL ein",
  "LINK_DLG_BAD_EMAIL": "Bitte geben Sie eine g眉ltige Emailadresse ein",
  "LINK_DLG_EMAIL_TITLE": "Geben Sie ein Betreff ein",
  "LINK_DLG_EMAIL_TITLE_EXAMPLE": "z.B. Informationsanfrage",
  "LINK_DLG_LOGIN_OPT_LOGIN_TAB": "Anmeldetab",
  "LINK_DLG_LOGIN_OPT_SIGNUP_TAB": "Registriertab",
  "BORDER_RADIUS_LOCK": "Ecken zusammen schlie脽en",
  "IFRAME_POPOUT": "In einem neuen Fenster sehen",
  "IFRAME_HELP_TITLE": "Hilfe Zentrum",
  "IFRAME_HELP_DESCRIPTION": "",
  "STYLE_CHANGE_BUTTON": "Stil bearbeiten",
  "MEDIA_DIALOG_DESCRIPTION": "脛ndern Sie den Stil Ihres Elements. Alle Elemente mit dem gleichen Stil werden ge盲ndert, um zu passen. ",
  "HELPLET_LEARN_MORE": "Erfahren Sie mehr",
  "ADVANCED_STYLING_LEARN_MORE": "Hinweis: 脛nderungen, die hier vorgenommen werden, werden auf alle Elemente Ihrer Site 眉bertragen. M枚chten Sie mehr erfahren? ",
  "CHOOSE_STYLE_TITLE": "Stil 盲ndern ",
  "CHOOSE_STYLE_DESCRIPTION": "W盲hlen Sie einen der voreingestellten Stile unten aus. Sie k枚nnen die Farben, R盲nder, Rahmen und Ecken anpassen und 盲ndern, indem Sie auf Bearbeiten klicken.",
  "ADJUST_DIALOG_TITLE": "Farbe anpassen",
  "ADJUST_DIALOG_DESCRIPTION": "",
  "COLOR_PICKER_DIALOG_TITLE": "Farbpicker",
  "COLOR_PICKER_DIALOG_DESCRIPTION": "Farbpickerbeschreibung",
  "ORGANIZE_PHOTOS_DIALOG_TITLE": "Bilder ordnen",
  "ORGANIZE_PHOTOS_DIALOG_DESCRIPTION": "Hier k枚nnen Sie Ihre Bilder ordnen",
  "ADD_PHOTOS_BUTTON_TEXT": "Bild hinzuf眉gen",
  "ORGANIZE_SLIDESHOWGALLERY_DIALOG_TITLE": "Bilder ordnen",
  "ORGANIZE_SLIDESHOWGALLERY_DIALOG_DESCRIPTION": "Hier k枚nnen Sie Ihre Bilder ordnen",
  "ADD_SLIDESHOWGALLERY_BUTTON_TEXT": "Bild hinzuf眉gen",
  "ORGANIZE_MATRIXGALLERY_DIALOG_TITLE": "Bilder ordnen",
  "ORGANIZE_MATRIXGALLERY_DIALOG_DESCRIPTION": "Hier k枚nnen Sie Ihre Bilder ordnen",
  "ADD_MATRIXGALLERY_BUTTON_TEXT": "Bild hinzuf眉gen",
  "ORGANIZE_SLIDERGALLERY_DIALOG_TITLE": "Bilder ordnen",
  "ORGANIZE_SLIDERGALLERY_DIALOG_DESCRIPTION": "Hier k枚nnen Sie Ihre Bilder ordnen",
  "ADD_SLIDERGALLERY_BUTTON_TEXT": "Bild hinzuf眉gen",
  "ORGANIZE_SOCIAL_ICONS_DIALOG_TITLE": "Soziale Netzwerksymbole ordnen",
  "ORGANIZE_SOCIAL_ICONS_DIALOG_DESCRIPTION": "Hier k枚nnen Sie Ihre Sozialen Netzwerksymbole ordnen",
  "ADD_SOCIAL_ICONS_BUTTON_TEXT": "Soziales Netzwerk Symbol hinzuf眉gen",
  "ORGANIZE_ICONS_DIALOG_TITLE": "Symbole ordnen",
  "ORGANIZE_ICONS_DIALOG_DESCRIPTION": "Hier k枚nnen Sie Ihre Symbole ordnen",
  "ADD_ICONS_BUTTON_TEXT": "Symbol hinzuf眉gen",
  "GALLERY_OBJECT_SOCIAL_ICONS": "Soziales Netzwerk Symbol",
  "GALLERY_OBJECT_ICONS": "Symbol",
  "GALLERY_OBJECT_PHOTOS": "Bild",
  "SELECT_COMPONENT_FOR_STYLE": "W盲hlen Sie ein Element",
  "SELECT_STYLE_FOR_COMPONENT": "W盲hlen Sie einen Stil",
  "REPLACE_COMPONENT_SKIN": "Skin 盲ndern",
  "ADVANCED_COLORS": "Farben:",
  "ADVANCED_FONTS": "Fonts:",
  "ADVANCED_RADIUS": "Eckengr枚脽e:",
  "ADVANCED_ADDITIONAL": "Weitere Konfigurationen:",
  "GALLERY_ORGANIZE_PHOTOS": "Bilder ordnen",
  "GALLERY_IMAGE_MODE": "Bildskalierung",
  "GALLERY_EXPAND_MODE": "Ausdehnungsmodus",
  "GALLERY_MARGIN": "Abstand (px)",
  "MATRIX_GALLERY_COLUMNS": "Spalten",
  "MATRIX_GALLERY_ROWS": "Zeilen",
  "MATRIX_GALLERY_SHOW_MORE": "Mehr (Zeilen) anzeigen",
  "SLIDESHOW_GALLERY_TRANSITIONS": "脺berg盲nge",
  "SLIDESHOW_GALLERY_DURATION": "Dauer",
  "SLIDESHOW_GALLERY_REVERSE": "R眉ckw盲rts",
  "SLIDESHOW_GALLERY_AUTOPLAY": "Automatische Wiedergabe",
  "SLIDESHOW_GALLERY_INTERVAL": "Pause zwischen Bildern (sek)",
  "SLIDESHOW_GALLERY_SHOW_AUTOPLAY": "Button zur automatischen Wiedergabe anzeigen",
  "SLIDESHOW_GALLERY_SHOW_NAVIGATION": "Navigationsbuttons anzeigen",
  "SLIDER_GALLERY_ASPECT_RATIO": "Schnittgr枚脽e",
  "SLIDER_GALLERY_SPEED": "Geschwindigkeit",
  "SLIDER_GALLERY_LOOP": "Schleife",
  "ADDIMAGESCREEN_HEADING": "Hallo,",
  "ADDIMAGESCREEN_PAR1": "Ihre Galerie ist leer",
  "ADDIMAGESCREEN_PAR2": "Beginnen Sie, indem Sie Ihre eigenen Bilder hinzuf眉gen",
  "ADDIMAGESCREEN_ADD_BUTTON": "Fotos hinzuf眉gen",
  "ADDIMAGESCREEN_KEEP_PRESET_BUTTON": "Nein, ich beginne lieber mit den aktuellen Bildern",
  "MORE_INFO": "Mehr Informationen",
  "DONT_SHOW_AGAIN": "Nicht wieder anzeigen",
  "INPUT_DIALOG_DUPLICATE_PAGE": "Seite verdoppeln",
  "DUPLICATE_PAGE_LABEL": "Seitentitel",
  "DUPLICATE_PAGE_COPY_OF": "Kopie von",
  "FLOATING_MENU_GRID_TITLE": "Gridgriff",
  "FLOATING_MENU_COPY_TITLE": "Komponente kopieren",
  "FLOATING_MENU_PASTE_TITLE": "Komponente einf眉gen",
  "PARAGRAPH_DEFAULT_TEXT": "Ich bin ein Paragraf. Klicken Sie hier, um Ihren eigenen Text hinzuzuf眉gen und mich zu bearbeiten. Es ist einfach. Klicken Sie einfach auf \"Text bearbeiten\" oder klicken Sie doppelt auf mich und Sie k枚nnen damit beginnen Ihren eigenen Inhalt hinzuzuf眉gen und die Fonts zu 盲ndern. Sie k枚nnen mich auf Ihrer Seite 眉berall hin verschieben. Ich erm枚gliche Ihnen noch mehr zu schreiben. Erz盲hlen Sie mir Ihre Geschichte, damit Ihre Nutzer Sie kennenlernen.",
  "TITLE_DEFAULT_TEXT": "Ich bin ein Titel. Klicken Sie doppelt, um mich zu bearbeiten.",
  "SUB_TITLE_DEFAULT_TEXT": "Ich bin ein Untertitel. Klicken Sie doppelt, um mich zu bearbeiten.",
  "SHOW_ON_ALL_PAGES": "Auf allen Seiten anzeigen",
  "ERROR_UPLOADING_FILE": "Fehler beim Hochladen der Datei",
  "DESIGN_CUSTOMIZE_MAIN_COLORS": "Hauptfarben",
  "DESIGN_CUSTOMIZE_MORE_COLORS": "Mehr Farben",
  "mobile.core.components.NetworkList": "Linkliste",
  "fold": "Kantengr枚脽e",
  "foldR": "Rechte Kantenfarbe",
  "foldL": "Linke Kantenfarbe",
  "APPS_SETTINGS_APPS": "App Einstellungen",
  "APPS_ADD_DIALOG_BOTTOM_DESCRIPTION": "Klicken Sie auf den Button oben, um diese App mit Ihrer Website zu verbinden. Nachdem die Verbindung besteht, 枚ffnen Sie das App Einstellungspanel, um diese zu personalisieren.",
  "ADD_AS_PAGE": "Als Seite hinzuf眉gen",
  "ADD_TO_PAGE": "Auf Seite hinzuf眉gen",
  "CONTAINER_HIGHLIGHT_ATTACH_STRIP": "An Strip h盲ngen",
  "CONTAINER_HIGHLIGHT_PARENT_STRIP": "Strip",
  "COMP_DESC_TPAWidget": "Klicken Sie auf den Button unten, um die Einstellungen der Anwendung zu 盲ndern",
  "COMP_DESC_TPASection": "Klicken Sie auf den Button unten, um die Einstellungen der Anwendung zu 盲ndern ",
  "GENERAL_TT_PREMIUM_FEATURE": "Premium Feature",
  "GENERAL_TIP": "Tipp:",
  "CURRENT_COLOR": "Aktuelle Farbe",
  "PREVIOUS_COLOR": "Vorherige Farbe",
  "CUSTOMIZE_COLOR": "Farbe anpassen",
  "WALK_THROUGH": "Spaziergang",
  "MAIN_SNAP_TO_GRID_TT": "An Gitter anpassen",
  "MAIN_PASTE_TT": "Einf眉gen Strg - V",
  "MAIN_COPY_TT": "Kopieren Strg - C",
  "MAIN_GRIDLINES_TT": "Gitterlinien",
  "DUPLICATE_TT": "Verdoppeln Strg D",
  "LINK_ON_PREVIEW_TT": "Ihr Link wird nicht im selben Fenster angzeigt, solange Sie sich im Vorschaumodus befinden, dies wird jedoch auf Ihrer Website funktionieren!",
  "DUPLICATE_BUTTON": "Speicher unter",
  "PAGES_PANEL_REORDER_TIP": "Um Ihre Seiten zu ordnen, ziehen Sie diese nach oben oder unten. Um eine unterseite zu erstellen, ziehen Sie diese nach rechts/links.",
  "PAGE_TRANS_NONE": "Kein",
  "PAGE_TRANS_SWIPE_HORIZONTAL": "Horizontal gleiten",
  "PAGE_TRANS_SWIPE_VERTIVAL": "Vertikal gleiten",
  "PAGE_TRANS_CROSS_FADE": "脺berblenden",
  "PAGE_TRANS_OUT_IN": "Au脽en-Innen",
  "MULTI_SELECT_ALIGN": "Ausrichten",
  "MULTI_SELECT_DISTRIBUTE": "Verteilen",
  "MULTI_SELECT_RELATIVE_TO_PARENT": "Bezieht sich auf das 眉bergeordnete Element",
  "MULTI_SELECT_MATCH_SIZE": "Gr枚脽e anpassen",
  "MULTI_SELECT_TT_ALIGN_MIDDLE": "Mitte",
  "MULTI_SELECT_TT_ALIGN_CENTER": "Zentrum",
  "MULTI_SELECT_TT_ALIGN_BOTTOM": "Unten",
  "MULTI_SELECT_TT_ALIGN_TOP": "Oben",
  "MULTI_SELECT_TT_ALIGN_RIGHT": "Rechts",
  "MULTI_SELECT_TT_ALIGN_LEFT": "Links",
  "MULTI_SELECT_TT_ALIGN": "Stellen Sie sicher, \"Bezieht sich auf das 眉bergeordnete Element\" zu 眉berpr眉fen, um die Elemente an ihren 眉bergeordneteten Elementen auszurichten und nicht an dem ersten ausgew盲hlten Element.",
  "MULTI_SELECT_TT_DISTRIBUTE_BOTH": "Beides",
  "MULTI_SELECT_TT_DISTRIBUTE_H": "Horizontal",
  "MULTI_SELECT_TT_DISTRIBUTE_V": "Vertikal",
  "MULTI_SELECT_TT_DISTRIBUTE": "Die Elemente gleichm盲脽ig vertikal oder horizontal verteilen.",
  "MULTI_SELECT_TT_MATCH_SIZE_BOTH": "An beide",
  "MULTI_SELECT_TT_MATCH_SIZE_WIDTH": "An Breite",
  "MULTI_SELECT_TT_MATCH_SIZE_HEIGHT": "An H枚he",
  "MULTI_SELECT_TT_MATCH_SIZE": "Die Gr枚脽e wird an das erste ausgew盲hlte Element angepasst.",
  "MULTI_SELECT_TT_UNDO": "R眉ckg盲ngig",
  "PHOTE_TT_TITLE": "Der Bildtitel ist auch der Text im Bildtooltip.",
  "PHOTE_ALT_TEXT_TT": "Alt Text stellt Informationen zu Ihren Bildern f眉r Suchmaschinen bereit",
  "PHOTE_SCALE_MODE_TT": "<p><strong>Anpassen:</strong> Bilder an die Gr枚脽e des Bilderrahmens anpassen.<br /> <strong>Zuschneiden:</strong> Das Bild zuschneiden und seine Gr枚脽e/sein Verh盲ltnis festlegen / ratio.<br /> <strong>Zentrieren:</strong> Zentriert das Bild innerhalb des Rahmens, w盲hrend es das Verh盲ltnis beibeh盲lt.<br /> <strong>Strecken:</strong> Streckt das Bild auf die Gr枚脽e des Bildrahmens.</p>",
  "FLASH_TT_ORIGINAL_TITLE": "Original:",
  "FLASH_TT_ORIGINAL_DESC": "Originalgr枚脽e des Bildes anzeigen, wenn es hochgeladen wird.",
  "FLASH_TT_FIT_TITLE": "Anpassen:",
  "FLASH_TT_FIT_DESC": "Das Bild an die Gr枚脽e des Rahmens anpassen.",
  "FLASH_TT_STRETCH_TITLE": "Strecken:",
  "FLASH_TT_STRETCH_DESC": "Das Bild strecken, um die Gr枚脽e an den Rahmen anzupassen.",
  "FLASH_TT_FALLBACK_IMG": "Ein alternatives Bild anzeigen, wenn Flash nicht geladen werden kann, wie z.B auf iPads und iPhones.",
  "FLICKR_GALLERY_TT_TAG_SORT": "Fotos, die mit der ausgew盲hlten Markierung versehen sind, werden angezeigt.",
  "FLICKR_GALLERY_TT_ORDER": "W盲hlen Sie, ob Ihre letzten Bilder oder eine zuf盲llige Auswahl angezeigt werden sollen.",
  "SOUNDCLOUD_EMBED_PH": "Geben Sie hier Text ein",
  "SOUNDCLOUD_INVALID_EMBED_CODE": "Ung眉ltiger eingebetteter Code",
  "SOUNDCLOUD_UPDATE": "Aktualisieren",
  "SOUNDCLOUD_TT_EMBED": "Klicken Sie auf den Teilen Button oberhalb jedes SoundCloud Musikplayers, um den eingebetteten Code zu erhalten.",
  "ADMIN_LOG_TT_PUBLIC_OPTION": "Diese Option ist f眉r Ihre live geschaltete Website aktiviert",
  "BUTTON_LABEL_TEXT": "Button Text",
  "BUTTON_TEXT_ALIGN": "Textausrichtung",
  "BUTTON_MARGIN": "Begrenzung",
  "FB_LIKE_TT_SEND": "Der Button Senden erm枚glicht Ihren Besuchern, ihren Freunden Ihren Linkin einer privaten Facebook Nachricht zu schicken.",
  "TWITTER_USER": "Twitter Benutzername",
  "TWITTER_USER_TT": "Dies ist Ihr Twitter Handle ohne @.",
  "TWITTER_USER_TO_FOLLOW_TT": "Dies ist Ihr Twitter Handle ohne @. Besucher, die twittern, werden eine Einladung erhalten, diesem Twitter Benutzernamen zu folgen.",
  "TWITTER_TWEET_TWEET_TEXT_TT": "F眉gen Sie den Inhalt hinzu, den Leute in ihren Tweets anzeigen sollen. Schlie脽en Sie Ihren Twitter Handle, Hashtags und Erw盲hnungen ein, falls relevant.",
  "LINK_ADD_LABEL": "Klicken Sie hier, um einen Link hinzuzuf眉gen",
  "PAGES_TRANSITIONS_TT": "Stellen Sie ein, wie Ihre Seiten ineinander 眉bergehen sollen.",
  "PAGE_SETTINGS_TT": "Seiteneinstellungen",
  "PAGE_SETTINGS_ADDRESS_TT": "Jede Seite Ihrer Site hat ihre eigene spezifische Seitenadresse. Die Seitenadresse sollte kurz und relevant sein.",
  "PAGE_SETTINGS_MENU_HIDE_TT": "Sie k枚nnen eine Seite aus Ihrem Men眉 ausblenden, ohne die Seite von Ihrer Site zu l枚schen.",
  "PAGE_SETTINGS_TITLE_TT": "Die 脺berschrift Ihrer Website in den Google Suchergebnissen. In unserem Beispiel schlie脽en wir den Gesch盲ftsnamen, relevante Schl眉脽elw枚rter und den Ort mit ein.",
  "PAGE_SETTINGS_DESC_TT": "Eine Zusammenfassung f眉r die Google Suchergebnisse, worum es sich bei Ihrer Seite handelt.",
  "PAGE_SETTINGS_KEYWORDS_TT": "Listen Sie Ihre Schl眉脽elw枚rter durch Kommata getrennt auf.",
  "BACKGROUND_EDITOR_SCROLL_TT": "Die Scrollleiste erm枚glicht es Besuchern, Ihre Site anzusehen, auch wenn der Bildschirm kleiner als Ihr Bild ist.",
  "BACKGROUND_EDITOR_IMAGE_SCALE_TT": "<strong>Vollbild:</strong> Das Bild wurde an die Gr枚脽e des Bildschirms auf dem Ihre Site angezeigt wird, angepasst.</p><p><strong>Anpassen: </strong>Passen Sie das Bild an die Hintergrundgr枚脽e ohne zurechtschneiden an.</p><p><strong>Kachel:</strong> Bild wird 眉ber den Bildschirm verteilt wiederholt.</p><p><strong>Normal:</strong> Bild beh盲lt seine Dimensionen bei.",
  "CUSTOME_PALETTE_TT_MORE_COLORS": "Dies sind weitere Farben, die Sie benutzen k枚nnen, die nicht mit Ihrer Palette verbunden sind. Wir behalten schwarz/weiss immer bei.",
  "CUSTOME_PALETTE_TT_MAIN_COLORS": "Dies sind die Hauptfarben Ihrer Site. 脛ndern Sie Ihre Farben w盲hrend Sie Ihre Farbpalette beibehalten, indem Sie die Farben in der oberen Reihe 盲ndern.",
  "CUSTOME_PALETTE_TT_INVERT": "]Sie k枚nnen die Farben wechseln, indem Sie auf <strong>Palette umkehren<strong/> klicken",
  "DRAG_PUSH_FOOTER": "Klicken Sie auf \"<strong>Auf allen Seiten anzeigen</strong>\" um etwas an die Fu脽leiste anzuh盲ngen",
  "DRAG_PUSH_FOOTER_TITLE": "Sie versuchen die Fu脽leiste zu ziehen?",
  "SEO_PANEL_TT_TITLE": "Die 脺berschrift Ihrer Website in den Google Suchergebnissen. In unserem Beispiel haben wir den Gesch盲ftsnamen, relevante Schl眉sselw枚rter und den Ort mit einbezogen.",
  "SEO_PANEL_TT_DESC": "Ein Zusammenfassung des Inhaltes Ihrer Site f眉r die Google Suchergebnisse und eine M枚glichkeit f眉r Ihre Site zu werben.",
  "SEO_PANEL_TT_KEYWORDS": "Listen Sie Ihre Schl眉sselw枚rter durch Kommata getrennt auf.",
  "STATISTICS_PANEL_COOKIE_TITLE": "Cookie Genehmigung (nur EU)",
  "STATISTICS_PANEL_COOKIE_DESCRIPTION_1": "Eine 脛nderung im EU Gesetzt legt fest, dass alle Websites ihre Besucher auf alle nicht-essentiellen Cookies aufmerksam machen m眉ssen, die auf ihren Ger盲ten verbleiben k枚nnen, und die Besucher um deren Erlaubnis bitten m眉ssen, um fortfahren zu k枚nnen.",
  "STATISTICS_PANEL_COOKIE_DESCRIPTION_2": "Nicht-essentielle Cookies werden f眉r analysierende Zwecke genutzt.",
  "STATISTICS_PANEL_COOKIE_PREMIUM": "Bitte beachten Sie, dass die Deaktivierung von nivht-essentiellen Cookies Google Analytics blockieren wird.",
  "STATISTICS_PANEL_COOKIE_CHECKBOX_LABEL": "Alle nicht-essentiellen Cookies deaktivieren",
  "SOCIAL_TITLE": "Soziale Netzwerke",
  "SOCIAL_PANEL_FAVICON_FAVICON": "Favicon",
  "SOCIAL_PANEL_FAVICON_THUMBNAIL": "Thumbnail",
  "SOCIAL_PANEL_THUMBNAIL_DESCRIPTION": "Personalisieren Sie, wie Ihre Site auf Facebook erscheint, immer wenn jemand den \"Gef盲llt mir\" Button klickt oder die Site in einem Status postet.",
  "SOCIAL_PANEL_CHANGE": "脛ndern",
  "SOCIAL_PANEL_FACEBOOK": "Facebook Benutzername",
  "SOCIAL_PANEL_FACEBOOK_DESCRIPTION": "Erm枚glicht Ihnen einen Facebook Gef盲llt mir Button und andere Plugins auf Ihrer Site hinzuzuf眉gen",
  "SOCIAL_PANEL_FACEBOOK_LEARN_MORE": "Mehr erfahren",
  "SOCIAL_PANEL_FACEBOOK_LABEL": "www.facebook.com/",
  "SOCIAL_PANEL_FACEBOOK_PLACEHOLDER": "geben Sie Ihren Benutzernamen ein",
  "FAVICON_PANEL_FAVICON_LABEL": "Favicon",
  "FAVICON_PANEL_FAVICON_DESCRIPTION": "Das Favicon ist Ihr eigenes 16x16 Websitesymbol, das f眉r alle Seiten Ihrer Website im Browser erscheint ",
  "FAVICON_PANEL_UPGRADE_TO_UPLOAD_FAVICON_DESCRIPTION": "Upgraden, um Ihr eigenes Favicon hochzuladen",
  "FAVICON_PANEL_UPGRADE_NOW": "Jetzt upgraden",
  "FAVICON_PANEL_CHANGE": "脛ndern",
  "FAVICON_TITLE": "Favicon",
  "FAVICON": "Favicon",
  "CONTACT_FORM_EMAIL_TT": "Vergessen Sie nicht, Ihre Emailadresse hinzuzuf眉gen! Ihr Kontaktformular wird nicht funktionieren, wenn Sie Ihre Emailadresse nicht in den Einstellungen eintragen.",
  "FPP_DropDownMenu": "Men眉",
  "ADJUST_DIALOG_OPACITY": "Deckkraft",
  "ORGANIZE_PHOTOS_DIALOG_IMAGE_TITLE_PH": "Titel hier eingeben",
  "ORGANIZE_IMAGES_TT_DESC": "Ihre Beschreibung wird im vergr枚脽erten Modus erhscheinen und in bestimmten Galerien.",
  "MENU_BUTTONS_ALIGNMENT": "Button Ausrichtung",
  "MENU_BUTTON_TEXT_ALIGNMENT": "Textausrichtung",
  "MENU_BUTTONS_CONSTANT_WIDTH": "Gleiche Breite f眉r alle Men眉 Elemente",
  "MENU_BUTTONS_FILL_MENU_WIDTH": "Buttons strecken, um den gesamten Platz auszuf眉llen",
  "MENU_MORE_BUTTON_LABEL": "Mehr Button Label",
  "MENU_MORE_BUTTON_TT": "Wenn Ihr Men眉 mehr Seiten enth盲lt, als die Gr枚脽e Ihrer Kopfleiste, dann grupppiert \"Mehr\" die 眉berstehenden Seiten in einem Drop Down Men眉 Button. Diesen k枚nnen Sie umbenennen.",
  "GALLERY_EXPAND_MODE_TT": "Vergr枚脽ert Ihre Bilder, wenn sie angeklickt werden.",
  "GALLERY_SCALE_MODE_TT": "<strong> An H枚he anpassen:</strong> Bilder an die H枚he der Galerie anpassen.<br/><strong>Zuschneiden:</strong> Das Bild zuschneiden und seine Gr枚脽e / Verh盲ltnis anpassen.",
  "MATRIX_GALLERY_SHOW_MORE_TT": "\"Mehr anzeigen\" erm枚glicht Ihren Nutzern, weitere Reihen von Bildern anzuzeigen. W盲hlen Sie, wie viele Reihen pro Klick sichtbar werden",
  "SHOW_ON_ALL_PAGES_TT": "Markieren Sie diese Box, damit das Element auf allen Seiten Ihrer Site erscheint.",
  "SHOW_ON_ALL_PAGES_COMP_TT": "Ich bin ein Element, das auf allen Seiten erscheint.",
  "ADD_TITLE": "Titel",
  "ADD_HEADING": "Titel",
  "ADD_PARAGRAPH": "Paragraf",
  "ADD_IMAGE": "Bild",
  "ADD_IMAGE_WITHOUT_FRAME": "Bild ohne Rahmen",
  "ADD_IMAGE_WITH_FRAME": "Bild mit Rahmen",
  "ADD_CLIP_ART": "Clipart",
  "ADD_GRID_GALLERY": "Grid",
  "ADD_SLIDESHOW_GALLERY": "Diashow",
  "ADD_SLIDER_GALLERY": "Slider",
  "ADD_ANIMATED_GRID_GALLERY": "Animiertes Grid",
  "ADD_VIDEO": "Video",
  "ADD_SOUNDCLOUD_AUDIO": "SoundCloud Audio",
  "ADD_BOX": "Box",
  "ADD_STRIP": "Strip",
  "ADD_VERTICAL_LINE": "Vertikale Linie",
  "ADD_HORIZONTAL_LINE": "Horinzontale Linie",
  "ADD_DEFAULT_BUTTON": "Standard Button",
  "ADD_LARGE_BUTTON": "Gro脽er Button",
  "ADD_EMPHASIS_BUTTON": "Betonungsbutton",
  "ADD_TEXT_BUTTON": "Text Button",
  "ADD_TEXT_MENU": "Text Men眉",
  "ADD_BUTTONS_MENU": "Buttons Men眉",
  "ADD_FACEBOOK_LIKE": "Facebook \"Gef盲llt mir\"",
  "ADD_FACEBOOK_COMMENTS": "Facebook Kommentare",
  "ADD_TWITTER_FOLLOW": "Twitter Follow",
  "ADD_TWITTER_TWEET": "Twitter Tweet",
  "ADD_TWITTER_FEED": "Twitter Feed",
  "ADD_GOOGLE_PLUS_ONE": "Google +1",
  "ADD_SOCIAL_BAR": "Soziale Netzwerkleiste",
  "ADD_CONTACT_FORM": "Kontaktformular",
  "ADD_GOOGLE_MAP": "Google Maps",
  "ADD_HTML": "HTML",
  "ADD_PAYPAL": "PayPal",
  "ADD_ADMIN_LOGIN": "Amin/Webmaster Login",
  "ADD_ICON_BAR": "Symbolleiste",
  "ADD_FLASH": "Flash",
  "ADD_FLICKR_GALLERY": "Flickr Galerie",
  "ADD_EBAY_ITEMS_BY_SELLER": "eBay",
  "SIDE_BTN_PAGES": "Seiten",
  "SIDE_BTN_DESIGN": "Design",
  "SIDE_BTN_ADD": "Hinzuf眉gen",
  "SIDE_BTN_SETTINGS": "Einstellungen",
  "EDIT_BOX_PUSH_TIP_TITLE": "Streckgriff",
  "EDIT_BOX_PUSH_TIP_CONTENT": "Dieser Griff ist besonders. Benutzen Sie ihn, um die Gr枚脽e eines Elements anzupassen, w盲hrend Sie das Seitenlayout beibehalten",
  "EDIT_BOX_DRAG_TIP_TITLE": "Streckgriff ziehen",
  "EDIT_BOX_DRAG_TIP_CONTENT": "Dieser Griff ist besonders. Ziehen Sie vertikal an ihm w盲hrend das gesamte Layout Ihrer Seite bestehen bleibt.",
  "EDIT_BOX_MAGNET_TIP_TITLE": "Magnet",
  "EDIT_BOX_MAGNET_TIP_CONTENT": "Verbinden Sie Elemente miteinander und bearbeiten Sie, w盲hrend Sie das Layout Ihrer Seite beibehalten",
  "EDIT_BOX_DELETE_TT": "Entfernen",
  "EDIT_BOX_DUPLICATE_TT": "Verdoppeln",
  "EDIT_BOX_MOVE_FORWARD_TT": "Nach vorne bringen",
  "EDIT_BOX_MOVE_BACK_TT": "Nach hinten schicken",
  "PUBLIH_FB_SHARE_CAPTION": "hat eine neue HTML5 Site publiziert",
  "GENERAL_AUDIO": "Audio",
  "MAIN_WALKME_TT": "Lassen Sie sich <br> durch den Editor f眉hren",
  "NAVIGATION_DROP_DOWN_LABEL": "Seite:",
  "AUDIO_REPLACE_AUDIO": "Song 盲ndern",
  "MEDIA_DIALOG_TITLE_AUDIO": "Audio Galerie",
  "MEDIA_DIALOG_DESCRIPTION_AUDIO": "Um eine neue Audiodatei (mp3) in Ihrer Galerie hinzuzuf眉gen, klicken Sie auf Hochladen und w盲hlen<BR>die Datei aus, die Sie hinzuf眉gen m枚chten. Die maximale Dateigr枚脽e betr盲gt 5MB.",
  "COMP_AudioPlayer": "Audio Player",
  "COMP_DESC_AudioPlayer": "F眉gen Sie Ihre Lieblingsmusik auf Ihrer Site hinzu",
  "SITE_MEMBERS_TITLE": "Site Members",
  "SITE_MEMBERS_TITLE_FULL": "Site Members",
  "SITE_MEMBERS_DESCRIPTION": "Site Members allows you to manage your own user base within your Wix site XXX XXX",
  "SITE_MEMBERS": "Site Members",
  "FPP_NAVIGATE_LABEL": "Navigieren",
  "FPP_SETTINGS_LABEL": "Einstellungen",
  "FPP_DESIGN_LABEL": "Design",
  "ADVANCED_ENABLE_SHADOW": "Enable Shadow",
  "AUDIO_SET_AUDIO": "Upload Track",
  "AUDIO_NO_ITEM_TEXT": "No mp3 file selected",
  "AUDIO_OPTIONS_TEXT": "Options",
  "AUDIOPLAYER_AUTOPLAY": "Autoplay",
  "AUDIOPLAYER_LOOP": "Loop",
  "AUDIOPLAYER_VOLUME": "Volume",
  "FPP_AudioPlayer": "Audio Player",
  "COMPONENT_STYLE_ap1": "Audio Player",
  "COMPONENT_STYLE_ap2": "Minimal Audio Player",
  "DISCARD_BUTTON": "Discard",
  "SAVE_BUTTON": "Save",
  "OK_ADD_ANOTHER_BUTTON": "OK and add another",
  "COMP_DESC_PaginatedGridGalleryWixApps": "Display many images at once in a grid formation. To add your own images click Organize Images.",
  "EDIT_DATA_BUTTON": "Edit Data",
  "GRIDLINES_LABEL_HEADER": "Header",
  "GRIDLINES_LABEL_PAGE": "Page",
  "GRIDLINES_LABEL_FOOTER": "Footer"
});