(function(global){
	global.template={
		modal:_.template(
					[
					'<div class="modal hide <%=type%>" id=<%=name%> tabindex="-1" role="dialog" aria-labelledby="<%=name%>Label" aria-hidden="true">',
					'<%if(options.header){%>',
					'	<div class="modal-header">',
					'	</div>',
					'<%}%>',
					'<%if(options.body){%>',
					'	<div class="modal-body">',
					'	</div>',
					'<%}%>',
					'<%if(options.footer){%>',
					'	<div class="modal-footer">',
					'	</div>',
					'<%}%>',
					'</div>'
					].join("")
		),
		modal_preview:_.template(
			[
'			<div class="modal hide large-modal preview-modal" id=<%=name%> tabindex="-1" role="dialog" aria-labelledby="previewLabel" aria-hidden="true">',
'			</div>',
			].join("")
		),
		list:_.template(
			[
'	      <div class="left-column">',
'	        <div class="column-hd">',
'	          <h3>分类目录</h3>',
'	        </div>',
'	        <div class="column-bd nanoscrollbar">',
'	          <div class="categories list-tree" id="contentstree">',
'	            <ul>',
'	              <li class="active">',
'					<div class="wraparea">',
'	                	<h4><a href="#">所有</a></h4>',
'					</div>',
'	              </li>',
'	              <li id="owner">',
'					<div class="wraparea">',
'	                <h4><a href="#">我的内容</a></h4>',
'					</div>',
'	              </li>',
'	              <li id="unset">',
'					<div class="wraparea">',
'	                <h4><a href="#">未分类</a></h4>',
'					</div>',
'	              </li>',
'				</ul>',
'	          </div>',
'	        </div>',
'	      </div>',
'	      <div class="right-column">',
'	        <div class="column-hd list-menu">',
'	        </div>',
'	        <div class="column-bd nanoscrollbar list-content">',
'	          <table cellspacing="0" class="hascheckbox units list">',
'	            <tbody>',
'	            </tbody>',
'	          </table>',
'	        </div>',
'	        <div class="column-ft list-page">',
'	        </div>',
'	      </div>',
			].join("")
		),
		list_2:_.template(
			[
'	      <div class="left-column">',
'	        <div class="column-hd">',
'	          <h3>分类目录</h3>',
'	        </div>',
'	        <div class="column-bd nanoscrollbar">',
'	          <div class="categories list-tree" id="contentstree">',
'	            <ul>',
'	              <li class="active">',
'					<div class="wraparea">',
'	                	<h4><a href="#">所有</a></h4>',
'					</div>',
'	              </li>',
'				</ul>',
'	          </div>',
'	        </div>',
'	      </div>',
'	      <div class="right-column">',
'	        <div class="column-hd list-menu">',
'	        </div>',
'	        <div class="column-bd nanoscrollbar">',
' 		         <div class="categories list-content"></div>',
'	        </div>',
'	        <div class="column-ft list-page">',
'	        </div>',
'	      </div>',
			].join("")
		),
		list_left:_.template(
			[
			'	<ul>',
'	              <li class="active">',
'	                <h4><a href="#">所有</a></h4>',
'	              </li>',
'	              <li id="owner">',
'	                <h4><a href="#">我的内容</a></h4>',
'	              </li>',
'	              <li id="unset">',
'	                <h4><a href="#">未分类</a></h4>',
'	              </li>',
'				</ul>',
			].join("")
		),
		list_menu:_.template(
			[
'	          <table cellspacing="0" class="hascheckbox list">',
'	            <thead>',
'	              <tr>',
'	                <th scope="col" width="5%"><input type="checkbox" name="selectall"></th>',
'	                <th scope="col" colspan="2">标题</th>',
'	                <th scope="col" width="12%">创建时间</th>',
'	                <th scope="col" width="10%"><select>',
'	                    <option>创建者</option>',
'	                    <option>LXH</option>',
'	                    <option>Laozhao</option>',
'	                    <option>Jason</option>',
'	                  </select></th>',
'	                <th scope="col" width="10%"><select>',
'	                    <option>状态</option>',
'	                    <option>已发布</option>',
'	                    <option>未发布</option>',
'	                    <option>草稿</option>',
'	                  </select></th>',
'	              </tr>',
'	            </thead>',
'	          </table>',
			].join("")
		),
		list_page:_.template(
			[
'	          <div class="pagination pagination-centered">',
'	            <ul>',
'				 <% var startpage=global.get_page(page,numpages,10).start; var endpage=global.get_page(page,numpages,10).end; %>',
'	              <li <% var left=(page!=1&&numpages>1)?"":"class=disabled";%><%=left%>><a class="first" href="#">«</a></li>',
'	              <li <% var left=(page!=1&&numpages>1)?"":"class=disabled";%><%=left%>><a class="prev" href="#">‹</a></li>',
'				<% for(i=startpage;i<=endpage;i++){ %>',
'					<li <% var current=(i==page)?"class=active":""; %><%=current%>><a class="page" href="#"><%=i%></a></li>',
'				<% } %>',
'	              <li <% var right=(page!=numpages&&numpages>0)?"":"class=disabled";%><%=right%>><a class="next" href="#">›</a></li>',
'	              <li <% var right=(page!=numpages&&numpages>0)?"":"class=disabled";%><%=right%>><a class="last" href="#">»</a></li>',
'	            </ul>',
'	          </div>',
			].join("")
		),
		msg:_.template(
			[
'  			<div class="status <%=type%>">',
'   			 <p><%=globaldict_lookup(msg)%></p>',
 '   		<a href="#" class="close">Close</a></div>',
 			].join("")
		),
		preview:_.template(
			[
'	  <div class="modal-header">',
'	    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>',
'	    <h3><%=title%></h3>',
'	    <!--<div class="pages">1/7</div>-->',
'	  </div>',
'	  <div class="modal-body">', 
'	    <div class="preview-content"><%=preview%></div>',
// '	    <div class="more-info"><a href="javascript:void(0)">更多信息</a></div>',
// '	    <div class="info-mod" style="display: none;">',
// '	      <div class="info-hd">',
// '	        <h4><%=title%></h4>',
// '	        <div class="close"><a href="javascript:void(0)">Close</a></div>',
// '	      </div>',
// '	      <div class="info-bd">',
// '	        <%=description%>',
// '	      </div>',
// '	    </div>',
'	  </div>',
			].join("")
		),
	   text_form:_.template(
	   	[
'			<div class="editform" style="display: block;">',
'				<input name=<%=id%> type="text" style="width:234px;" value="<%=text%>">',
'				<div>',
'					<button class="btn btn-small btn-primary action-save" type="button">确认</button>',
'					<button class="btn btn-small action-cancel" style="margin-left:10px;" type="button">取消</button>',
'				</div>',
'			</div>',
	   	].join("")
	   ),
	   confirm:_.template(
	   	[
'		  <div class="modal-header">',
'		    <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>',
'		    <h3>确认框</h3>',
'		  </div>',
'		  <div class="modal-body"> <span style="font-size:14px;">确认删除 ？</span></div>',
'		  <div class="modal-footer">',
'		    <button class="btn btn-primary btn-confirm">确定</button>',
'		    <button aria-hidden="true" data-dismiss="modal" style="margin-left:20px;" class="btn">取消</button>',
'		  </div>',
	   	].join("")
	   ),
	}
})(global);
