/*{"version":"11488622","mac":"1:708be35761c558fd06a1e584d625675e4f3df483503a3a9baa702a469d809522","k":"0.16.0","created":"2012-06-20T16:32:10Z"}*/
;(function(window,document,undefined){
var g=void 0,l=!0,n=null,o=!1;function p(a){return function(){return this[a]}}var q;function r(a,c,b){var e=2<arguments.length?Array.prototype.slice.call(arguments,2):[];return function(){e.push.apply(e,arguments);return c.apply(a,e)}}function s(a){this.l=a;this.w=g}s.prototype.createElement=function(a,c,b){a=this.l.createElement(a);if(c)for(var e in c)c.hasOwnProperty(e)&&("style"==e?this.qa(a,c[e]):a.setAttribute(e,c[e]));b&&a.appendChild(this.l.createTextNode(b));return a};
function t(a,c,b){a=a.l.getElementsByTagName(c)[0];a||(a=document.documentElement);a&&a.lastChild&&a.insertBefore(b,a.lastChild)}function u(a){function c(){document.body?a():setTimeout(c,0)}c()}function v(a){a.parentNode&&a.parentNode.removeChild(a)}function w(a,c){for(var b=a.className.split(/\s+/),e=0,d=b.length;e<d;e++)if(b[e]==c)return;b.push(c);a.className=b.join(" ").replace(/^\s+/,"")}
function x(a,c){for(var b=a.className.split(/\s+/),e=[],d=0,f=b.length;d<f;d++)b[d]!=c&&e.push(b[d]);a.className=e.join(" ").replace(/^\s+/,"").replace(/\s+$/,"")}function y(a,c){for(var b=a.className.split(/\s+/),e=0,d=b.length;e<d;e++)if(b[e]==c)return l;return o}s.prototype.qa=function(a,c){this.V()?a.setAttribute("style",c):a.style.cssText=c};s.prototype.V=function(){if(this.w===g){var a=this.l.createElement("p");a.innerHTML='<a style="top:1px;">w</a>';this.w=/top/.test(a.getElementsByTagName("a")[0].getAttribute("style"))}return this.w};
function z(a,c,b,e,d,f,h){this.X=a;this.Ra=c;this.xa=b;this.wa=e;this.Ma=d;this.La=f;this.va=h}q=z.prototype;q.getName=p("X");q.getVersion=p("Ra");q.getEngine=p("xa");q.getEngineVersion=p("wa");q.getPlatform=p("Ma");q.getPlatformVersion=p("La");q.getDocumentMode=p("va");function aa(a,c){this.c=a;this.v=c}var ba=new z("Unknown","Unknown","Unknown","Unknown","Unknown","Unknown",g);
aa.prototype.parse=function(){var a;if(-1!=this.c.indexOf("MSIE"))if(a=A(this.c,/(MSIE [\d\w\.]+)/,1),""!=a){var c=a.split(" ");a=c[0];c=c[1];a=new z(a,c,a,c,B(this),C(this),D(this.v),6<=E(c))}else a=new z("MSIE","Unknown","MSIE","Unknown",B(this),C(this),D(this.v));else if(-1!=this.c.indexOf("Opera"))a:{var c=a="Unknown",b=A(this.c,/(Presto\/[\d\w\.]+)/,1);""!=b?(c=b.split("/"),a=c[0],c=c[1]):(-1!=this.c.indexOf("Gecko")&&(a="Gecko"),b=A(this.c,/rv:([^\)]+)/,1),""!=b&&(c=b));if(-1!=this.c.indexOf("Version/")&&
(b=A(this.c,/Version\/([\d\.]+)/,1),""!=b)){a=new z("Opera",b,a,c,B(this),C(this),D(this.v),10<=E(b));break a}b=A(this.c,/Opera[\/ ]([\d\.]+)/,1);a=""!=b?new z("Opera",b,a,c,B(this),C(this),D(this.v),10<=E(b)):new z("Opera","Unknown",a,c,B(this),C(this),D(this.v))}else if(-1!=this.c.indexOf("AppleWebKit")){a=B(this);c=C(this);b=A(this.c,/AppleWebKit\/([\d\.]+)/,1);""==b&&(b="Unknown");var e="Unknown";-1!=this.c.indexOf("Chrome")||-1!=this.c.indexOf("CrMo")?e="Chrome":-1!=this.c.indexOf("Safari")?
e="Safari":-1!=this.c.indexOf("AdobeAIR")&&(e="AdobeAIR");var d="Unknown";-1!=this.c.indexOf("Version/")?d=A(this.c,/Version\/([\d\.\w]+)/,1):"Chrome"==e?d=A(this.c,/(Chrome|CrMo)\/([\d\.]+)/,2):"AdobeAIR"==e&&(d=A(this.c,/AdobeAIR\/([\d\.]+)/,1));"AdobeAIR"==e?(A(d,/\d+\.(\d+)/,1),2<E(d)||E(d)):(A(b,/\d+\.(\d+)/,1),526<=E(b)||E(b));a=new z(e,d,"AppleWebKit",b,a,c,D(this.v))}else if(-1!=this.c.indexOf("Gecko")){c=a="Unknown";e=o;-1!=this.c.indexOf("Firefox")?(a="Firefox",b=A(this.c,/Firefox\/([\d\w\.]+)/,
1),""!=b&&(e=A(b,/\d+\.(\d+)/,1),c=b,e=""!=b&&3<=E(b)&&5<=parseInt(e,10))):-1!=this.c.indexOf("Mozilla")&&(a="Mozilla");b=A(this.c,/rv:([^\)]+)/,1);if(""==b)b="Unknown";else if(!e){var e=E(b),d=parseInt(A(b,/\d+\.(\d+)/,1),10),f=parseInt(A(b,/\d+\.\d+\.(\d+)/,1),10);1<e||1==e&&9<d||1==e&&9==d&&2<=f||b.match(/1\.9\.1b[123]/)!=n||b.match(/1\.9\.1\.[\d\.]+/)}a=new z(a,c,"Gecko",b,B(this),C(this),D(this.v))}else a=ba;return a};
function B(a){var c=A(a.c,/(iPod|iPad|iPhone|Android)/,1);if(""!=c)return c;a=A(a.c,/(Linux|Mac_PowerPC|Macintosh|Windows|CrOS)/,1);return""!=a?("Mac_PowerPC"==a&&(a="Macintosh"),a):"Unknown"}function C(a){var c=A(a.c,/(OS X|Windows NT|Android|CrOS) ([^;)]+)/,2);if(c||(c=A(a.c,/(iPhone )?OS ([\d_]+)/,2)))return c;return(a=A(a.c,/Linux ([i\d]+)/,1))?a:"Unknown"}function E(a){a=A(a,/(\d+)/,1);return""!=a?parseInt(a,10):-1}function A(a,c,b){return(a=a.match(c))&&a[b]?a[b]:""}
function D(a){if(a.documentMode)return a.documentMode}function ca(a,c,b){this.j=a;this.n=c;this.aa=b;this.p="wf";this.o=new fa("-")}function ga(a){x(a.n,a.o.k(a.p,"loading"));y(a.n,a.o.k(a.p,"active"))||w(a.n,a.o.k(a.p,"inactive"));G(a,"inactive")}function G(a,c,b,e){if(a.aa[c])a.aa[c](b,e)}function H(a,c,b,e,d){this.j=a;this.C=c;this.F=b;this.u=e;this.I=d;this.P=0;this.ra=this.ia=o}
H.prototype.watch=function(a,c,b,e,d){for(var f=a.length,h=0;h<f;h++){var i=a[h];c[i]||(c[i]=["n4"]);this.P+=c[i].length}d&&(this.ia=d);for(h=0;h<f;h++)for(var i=a[h],d=c[i],j=b[i],k=0,m=d.length;k<m;k++){var da=d[k],F=this.C,M=i,ea=da;w(F.n,F.o.k(F.p,M,ea,"loading"));G(F,"fontloading",M,ea);F=r(this,this.ya);M=r(this,this.za);(new e(F,M,this.j,this.F,this.u,this.I,i,da,j)).start()}};
H.prototype.ya=function(a,c){var b=this.C;x(b.n,b.o.k(b.p,a,c,"loading"));x(b.n,b.o.k(b.p,a,c,"inactive"));w(b.n,b.o.k(b.p,a,c,"active"));G(b,"fontactive",a,c);this.ra=l;ha(this)};H.prototype.za=function(a,c){var b=this.C;x(b.n,b.o.k(b.p,a,c,"loading"));y(b.n,b.o.k(b.p,a,c,"active"))||w(b.n,b.o.k(b.p,a,c,"inactive"));G(b,"fontinactive",a,c);ha(this)};
function ha(a){0==--a.P&&a.ia&&(a.ra?(a=a.C,x(a.n,a.o.k(a.p,"loading")),x(a.n,a.o.k(a.p,"inactive")),w(a.n,a.o.k(a.p,"active")),G(a,"active")):ga(a.C))}
function I(a,c,b,e,d,f,h,i,j){this.ta=a;this.Ea=c;this.j=b;this.F=e;this.u=d;this.I=f;this.Ka=new ia;this.Ba=new ja;this.R=h;this.Q=i;this.Aa=j||"BESbswy";this.ka=ka(this,"arial,'URW Gothic L',sans-serif");this.la=ka(this,"Georgia,'Century Schoolbook L',serif");this.ga=this.ka;this.ha=this.la;this.Y=J(this,"arial,'URW Gothic L',sans-serif");this.Z=J(this,"Georgia,'Century Schoolbook L',serif")}I.prototype.start=function(){this.Pa=this.I();this.ba()};
I.prototype.ba=function(){var a=this.F.U(this.Y),c=this.F.U(this.Z);(this.ka!=a||this.la!=c)&&this.ga==a&&this.ha==c?(a=this.ta,v(this.Y),v(this.Z),a(this.R,this.Q)):5E3<=this.I()-this.Pa?(a=this.Ea,v(this.Y),v(this.Z),a(this.R,this.Q)):(this.ga=a,this.ha=c,la(this))};function la(a){a.u(function(a,b){return function(){b.call(a)}}(a,a.ba),25)}function ka(a,c){var b=J(a,c,l),e=a.F.U(b);v(b);return e}function J(a,c,b){c=a.j.createElement("span",{style:ma(a,c,a.Q,b)},a.Aa);t(a.j,"body",c);return c}
function ma(a,c,b,e){b=a.Ba.expand(b);return"position:absolute;top:-999px;left:-999px;font-size:300px;width:auto;height:auto;line-height:normal;margin:0;padding:0;font-variant:normal;font-family:"+(e?"":a.Ka.quote(a.R)+",")+c+";"+b}function fa(a){this.Ia=a||"-"}fa.prototype.k=function(a){for(var c=[],b=0;b<arguments.length;b++)c.push(arguments[b].replace(/[\W_]+/g,"").toLowerCase());return c.join(this.Ia)};function ia(){this.pa="'"}
ia.prototype.quote=function(a){for(var c=[],a=a.split(/,\s*/),b=0;b<a.length;b++){var e=a[b].replace(/['"]/g,"");-1==e.indexOf(" ")?c.push(e):c.push(this.pa+e+this.pa)}return c.join(",")};function ja(){this.na=na;this.G=oa}var na=["font-style","font-weight"],oa={"font-style":[["n","normal"],["i","italic"],["o","oblique"]],"font-weight":[["1","100"],["2","200"],["3","300"],["4","400"],["5","500"],["6","600"],["7","700"],["8","800"],["9","900"],["4","normal"],["7","bold"]]};
function pa(a,c,b){this.Fa=a;this.Na=c;this.G=b}pa.prototype.expand=function(a,c){for(var b=0;b<this.G.length;b++)if(c==this.G[b][0]){a[this.Fa]=this.Na+":"+this.G[b][1];break}};ja.prototype.expand=function(a){if(2!=a.length)return n;for(var c=[n,n],b=0,e=this.na.length;b<e;b++){var d=this.na[b];(new pa(b,d,this.G[d])).expand(c,a.substr(b,1))}return c[0]&&c[1]?c.join(";")+";":n};function K(a){this.l=a;this.w=g}K.prototype=s.prototype;function L(a){return"https:"==a.l.location.protocol}
K.prototype.Ca=function(){return this.l.location.hostname};function qa(a,c,b){var e=a.l.getElementsByTagName("head")[0];if(e){var d=a.l.createElement("script");d.src=c;var f=o;d.onload=d.onreadystatechange=function(){if(!f&&(!this.readyState||"loaded"==this.readyState||"complete"==this.readyState))f=l,b&&b(),d.onload=d.onreadystatechange=n,"HEAD"==d.parentNode.tagName&&e.removeChild(d)};e.appendChild(d)}}K.prototype.qa=function(a,c){this.V()?a.setAttribute("style",c):a.style.cssText=c};
K.prototype.V=function(){if(this.w===g){var a=this.l.createElement("p");a.innerHTML='<a style="top:1px;">w</a>';this.w=/top/.test(a.getElementsByTagName("a")[0].getAttribute("style"))}return this.w};function N(a,c){this.Oa=a;this.ca=c}function ra(a){for(var c=a.Oa.join(","),b=[],e=0;e<a.ca.length;e++){var d=a.ca[e];b.push(d.name+":"+d.value+";")}return c+"{"+b.join("")+"}"}function O(a,c){this.D=a;this.H=c;this.ea={};this.da={}}O.prototype.z=function(a){return a?(this.ea[a.J]||this.H).slice(0):this.H.slice(0)};
function sa(a,c,b){for(var e=[],d=a.D.split(",")[0].replace(/"|'/g,""),f=a.z(),h,i=[],j={},k=0;k<f.length;k++)h=f[k],0<h.length&&!j[h]&&(j[h]=l,i.push(h));b=b.oa?b.oa(d,i,e):i;c=c.J;a.ea[c]=b;a.da[c]=e}O.prototype.watch=function(a,c,b){var e=[],d={};ta(this,c,e,d);a(e,d,b)};function ta(a,c,b,e){b.push(a.D);e[a.D]=a.z(c);a=a.da[c.J]||[];for(c=0;c<a.length;c++){for(var d=a[c],f=d.D,h=o,i=0;i<b.length;i++)b[i]==f&&(h=l);h||(b.push(f),e[f]=d.z())}}function ua(a,c){this.D=a;this.H=c}ua.prototype.z=p("H");
function va(a){var c=new Image(1,1);c.src=a;c.onload=function(){c.onload=n}}function P(a,c){this.J=a;this.fa=c}function Q(a){wa.M.push(a)}function xa(a){this.j=a;this.r=this.c=this.L=n;this.ua=this.Ga=this.Ha=l;this.m=[];this.B=[];this.sa=this.S=this.N=this.O=n}
function ya(a,c){a.c=c;if(a.L){var b;a:{b=a.L;for(var e=a.c,d=a.Ha,f=a.Ga,h=a.ua,i=0;i<b.M.length;i++){var j=b.M[i];if(j.fa&&j.fa(e.getName(),e.getVersion(),e.getEngine(),e.getEngineVersion(),e.getPlatform(),e.getPlatformVersion(),e.getDocumentMode(),d,f,h)){b=j;break a}}b=n}a.r=b}}q=xa.prototype;q.supportsConfiguredBrowser=function(){return!!this.r};
q.init=function(){for(var a=[],c=0;c<this.B.length;c++)a.push(ra(this.B[c]));var c=this.j,a=a.join(""),b=this.j.l.createElement("style");b.setAttribute("type","text/css");b.styleSheet?b.styleSheet.cssText=a:b.appendChild(document.createTextNode(a));t(c,"head",b)};
q.load=function(a,c){var b=this.r.J;if(this.S)for(var e=za(this.S,b),d=0;d<this.m.length;d++)sa(this.m[d],this.r,e);this.O&&(e=[],this.N&&(e=new Aa(this.j,this.r,this.m),e=Ba(this.N,b,e)),b=this.O.k(L(this.j),Ca(b,e)),t(this.j,"head",this.j.createElement("link",{rel:"stylesheet",href:b})));a&&u(function(a,b,c,d){return function(){for(var e=0;e<a.m.length;e++)a.m[e].watch(b,c,d&&e==a.m.length-1)}}(this,a,this.r,c))};
q.collectFontFamilies=function(a,c){for(var b=0;b<this.m.length;b++)ta(this.m[b],this.r,a,c)};q.performOptionalActions=function(a){this.W&&u(function(a,b,e,d){return function(){var b=a.W;if(b.ma){var h=window.__adobewebfontsappname__,h=h?h.toString().substr(0,20):"";va(b.ma.k(L(d),{host:encodeURIComponent(d.l.location.hostname),app:encodeURIComponent(h),_:(+new Date).toString()}))}b=a.W;b.$&&(b=b.$.k(e,d),t(d,"body",b))}}(this,a,this.c,this.j))};
function R(a,c,b,e){this.Ja=a;this.j=c;this.n=b;this.u=e;this.q=[]}R.prototype.K=function(a){this.q.push(a)};R.prototype.load=function(a,c){var b=a,e=c||{};if("string"==typeof b)b=[b];else if(!b||!b.length)e=b||{},b=[];if(b.length)for(var d=this,f=b.length,h=0;h<b.length;h++)Da(this,b[h],function(){0==--f&&Ea(d,e)});else Ea(this,e)};function Da(a,c,b){qa(a.j,a.Ja.k(L(a.j),{id:encodeURIComponent(c)}),b)}
function Ea(a,c){for(var b=new ca(a.j,a.n,c),e=o,d=0;d<a.q.length;d++)a.q[d].init(),e=e||a.q[d].supportsConfiguredBrowser();e?(w(b.n,b.o.k(b.p,"loading")),G(b,"loading"),Fa(a,b)):ga(b);a.q=[]}function Fa(a,c){function b(a,b,c){e.watch(a,b,{},I,c)}for(var e=new H(a.j,c,{U:function(a){return a.offsetWidth}},a.u,function(){return+new Date}),d=0;d<a.q.length;d++){var f=a.q[d];f.supportsConfiguredBrowser()&&(f.load(b,d==a.q.length-1),f.performOptionalActions(window))}}
function S(a,c){this.A=a;this.u=c;this.q=[]}S.prototype.K=function(a){this.q.push(a)};S.prototype.load=function(){var a=this.A.__webfonttypekitmodule__;if(a)for(var c=0;c<this.q.length;c++){var b=this.q[c],e=a[b.sa];if(e){var d=this.u;e(function(a,c,e){var c=[],j={};ya(b,a);b.supportsConfiguredBrowser()&&(b.init(),b.load(n,d),b.collectFontFamilies(c,j),b.performOptionalActions(window));e(b.supportsConfiguredBrowser(),c,j)})}}};function T(a,c){this.X=a;this.oa=c}T.prototype.getName=p("X");
function Ga(a){var c=U;Ha(c,a.getName())||c.T.push(a)}function Ha(a,c){for(var b=0;b<a.T.length;b++){var e=a.T[b];if(c===e.getName())return e}return n}function za(a,c){var b=a.s[c];return b?Ha(a,b):n}function Ba(a,c,b){for(var e=[],a=a.t[c]||[],c=0;c<a.length;c++){var d;a:switch(a[c]){case "observeddomain":d=new Ia(b.j);break a;case "fontmask":d=new Ja(b.r,b.m);break a;default:d=n}d&&e.push(d)}return e}function Aa(a,c,b){this.j=a;this.r=c;this.m=b}function Ia(a){this.j=a}
Ia.prototype.toString=function(){return encodeURIComponent(this.j.Ca?this.j.l.location.hostname:document.location.hostname)};function Ja(a,c){this.r=a;this.m=c}Ja.prototype.toString=function(){for(var a=[],c=0;c<this.m.length;c++)for(var b=this.m[c],e=b.z(),b=b.z(this.r),d=0;d<e.length;d++){var f;a:{for(f=0;f<b.length;f++)if(e[d]===b[f]){f=l;break a}f=o}a.push(f?1:0)}a=a.join("");a=a.replace(/^0+/,"");c=[];for(e=a.length;0<e;e-=4)b=a.slice(0>e-4?0:e-4,e),c.unshift(parseInt(b,2).toString(16));return c.join("")};
function V(a){this.Qa=a}V.prototype.k=function(a,c){var b=c||{},e=this.Qa.replace(/\{\/?([^*}]*)(\*?)\}/g,function(a,c,e){return e&&b[c]?"/"+b[c].join("/"):b[c]||""});e.match(/^\/\//)&&(e=(a?"https:":"http:")+e);return e.replace(/\/*\?*($|\?)/,"$1")};function Ca(a,c){for(var b=[],e=0;e<c.length;e++)b.push(c[e].toString());return{format:a,extras:b}}function Ka(a,c,b,e){this.A=a;this.l=c;this.Da=b;this.ja=e}
Ka.prototype.k=function(a,c){var b=this.l.createElement("img");b.setAttribute("width",62);b.setAttribute("height",25);b.setAttribute("src",this.Da.k(L(c)));b.setAttribute("class","typekit-badge");b.setAttribute("alt","Fonts by Typekit");b.setAttribute("title","Information about the fonts used on this site");b.style.position="fixed";b.style.zIndex=2E9;b.style.right=0;b.style.bottom=0;b.style.cursor="pointer";b.style.border=0;"Opera"!=a.getName()&&(b.style.content="none");b.style.display="inline";b.style["float"]=
"none";b.style.height="25px";b.style.left="auto";b.style.margin=0;b.style.maxHeight="25px";b.style.maxWidth="62px";b.style.minHeight="25px";b.style.minWidth="62px";b.style.orphans=2;b.style.outline="none";b.style.overflow="visible";b.style.padding=0;b.style.pageBreakAfter="auto";b.style.pageBreakBefore="auto";b.style.pageBreakInside="auto";b.style.tableLayout="auto";b.style.textIndent=0;b.style.top="auto";b.style.unicodeBidi="normal";b.style.verticalAlign="baseline";b.style.visibility="visible";b.style.widows=
2;b.style.width="65px";if(this.ja){var e=this.l,d=this.ja;W(this,b,"click",function(){e.location.href=d})}if("MSIE"==a.getName()){b.style.position="absolute";var f=this,h=function(){var a=La(f,"scrollLeft","scrollTop"),c=La(f,"clientWidth","clientHeight");b.style.bottom="auto";b.style.right="auto";b.style.top=a[1]+c[1]-25+"px";b.style.left=a[0]+c[0]-3-62+"px"};W(this,this.A,"scroll",h);W(this,this.A,"resize",h)}h=a.getPlatform();if("iPhone"==h||"iPod"==h||"iPad"==h||"Android"==h)b.style.display="none";
return b};function La(a,c,b){var e=0,d=0,a=a.l;if(a.documentElement&&(a.documentElement[c]||a.documentElement[b]))e=a.documentElement[c],d=a.documentElement[b];else if(a.body&&(a.body[c]||a.body[b]))e=a.body[c],d=a.body[b];return[e,d]}function W(a,c,b,e){if(c.attachEvent){var d=a.A;c["e"+b+e]=e;c[b+e]=function(){c["e"+b+e](d.event)};c.attachEvent("on"+b,c[b+e])}else c.addEventListener(b,e,o)}var wa=new function(){this.M=[]};
Q(new P("a",function(a,c,b,e,d,f){if(o||("Windows"==d&&"Unknown"==f?l:o)||("Ubuntu"==d||"Linux"==d?l:o))a:{if("AdobeAIR"==a&&(a=/([0-9]+.[0-9]+)/.exec(c))){a=2.5<=parseFloat(a[1]);break a}a=o}else a=o;return a}));
Q(new P("b",function(a,c,b,e,d,f,h,i,j,k){var m;m=o||function(a,b,c,e,d,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==d&&a?(d=parseInt(a[1],10),f=parseInt(a[3],10),10<d||10==d&&4<=f):"Macintosh"==d&&"Unknown"==f?l:o}(a,c,b,e,d,f,h,i,j,k);return!m?o:function(a,b){if("AdobeAIR"==a){var c=/([0-9]+.[0-9]+)/.exec(b);if(c)return 2.5<=parseFloat(c[1])}return o}(a,c,b,e,d,f,h,i,j,k)}));
Q(new P("a",function(a,c,b,e,d,f,h,i,j,k){var m;m=(m=o||("Windows"==d&&"5.1"==f?l:o)||("Windows"==d&&"5.2"==f?l:o)||("Windows"==d&&"6.0"==f?l:o)||function(a,b,c,e,d,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==d&&a?(d=parseInt(a[1],10),a=parseInt(a[2],10),6<d||6==d&&1<=a):o}(a,c,b,e,d,f,h,i,j,k))||function(a,b,c,d,e,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==e&&a?(e=parseInt(a[1],10),f=parseInt(a[3],10),10<e||10==e&&4<=f):"Macintosh"==e&&"Unknown"==f?l:o}(a,c,b,e,d,f,h,i,j,k);
return!m&&!("Ubuntu"==d||"Linux"==d?l:o)?o:function(a,b){if("Chrome"==a){var c=/([0-9]+.[0-9]+).([0-9]+).([0-9]+)/.exec(b);if(c){var e=parseFloat(c[1]),d=parseInt(c[2],10),c=parseInt(c[3],10);if(!(6<=e)&&(4<e||4==e&&249<d||4==e&&249==d&&4<=c))return l}}return o}(a,c,b,e,d,f,h,i,j,k)}));
Q(new P("d",function(a,c,b,e,d,f,h,i,j,k){var m;m=(m=(m=o||("Windows"==d&&"5.1"==f?l:o)||("Windows"==d&&"5.2"==f?l:o)||("Windows"==d&&"6.0"==f?l:o)||function(a,b,c,e,d,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==d&&a?(d=parseInt(a[1],10),a=parseInt(a[2],10),6<d||6==d&&1<=a):o}(a,c,b,e,d,f,h,i,j,k))||function(a,b,c,d,e,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==e&&a?(e=parseInt(a[1],10),f=parseInt(a[3],10),10<e||10==e&&4<=f):"Macintosh"==e&&"Unknown"==f?l:o}(a,c,b,e,d,f,h,i,j,
k))||("Ubuntu"==d||"Linux"==d?l:o)||function(a,b,c,e,d,f,h,i,j,k){a=/([0-9]+).([0-9]+)/.exec(f);return k&&"Android"==d&&a?(d=parseInt(a[1],10),k=parseInt(a[2],10),3==d&&1<=k||3<d):o}(a,c,b,e,d,f,h,i,j,k);return!(m||"CrOS"==d)?o:function(a,b){if("Chrome"==a){var c=/([0-9]+.[0-9]+).([0-9]+).([0-9]+)/.exec(b);if(c&&6<=parseFloat(c[1]))return l}}(a,c,b,e,d,f,h,i,j,k)}));
Q(new P("a",function(a,c,b,e,d,f,h,i,j,k){var m;m=o||("Windows"==d&&"5.1"==f?l:o)||("Windows"==d&&"5.2"==f?l:o)||("Windows"==d&&"6.0"==f?l:o)||function(a,b,c,e,d,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==d&&a?(d=parseInt(a[1],10),a=parseInt(a[2],10),6<d||6==d&&1<=a):o}(a,c,b,e,d,f,h,i,j,k);return!m&&!("Ubuntu"==d||"Linux"==d?l:o)?o:function(a,b,c,d){return"Gecko"==c?(a=/1.9.1b[1-3]{1}/,/1.9.1/.test(d)&&!a.test(d)):o}(a,c,b,e,d,f,h,i,j,k)}));
Q(new P("b",function(a,c,b,e,d,f,h,i,j,k){var m;m=o||function(a,b,c,d,e,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==e&&a?(e=parseInt(a[1],10),f=parseInt(a[3],10),10<e||10==e&&4<=f):"Macintosh"==e&&"Unknown"==f?l:o}(a,c,b,e,d,f,h,i,j,k);return!m?o:function(a,b,c,d){return"Gecko"==c?(a=/1.9.1b[1-3]{1}/,/1.9.1/.test(d)&&!a.test(d)):o}(a,c,b,e,d,f,h,i,j,k)}));
Q(new P("d",function(a,c,b,e,d,f,h,i,j,k){var m;m=(m=o||("Windows"==d&&"5.1"==f?l:o)||("Windows"==d&&"5.2"==f?l:o)||("Windows"==d&&"6.0"==f?l:o)||function(a,b,c,d,e,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==e&&a?(e=parseInt(a[1],10),a=parseInt(a[2],10),6<e||6==e&&1<=a):o}(a,c,b,e,d,f,h,i,j,k))||function(a,b,c,d,e,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==e&&a?(e=parseInt(a[1],10),f=parseInt(a[3],10),10<e||10==e&&4<=f):"Macintosh"==e&&"Unknown"==f?l:o}(a,c,b,e,d,f,h,i,j,k);
return!m&&!("Ubuntu"==d||"Linux"==d?l:o)?o:function(a,b,c,e){return"Gecko"==c&&(b=/([0-9]+.[0-9]+)(.([0-9]+)|)/.exec(e))?(a=parseFloat(b[1]),b=parseInt(b[3],10),1.9<a||1.9<=a&&1<b):o}(a,c,b,e,d,f,h,i,j,k)}));
Q(new P("i",function(a,c,b,e,d,f,h,i,j,k){var m;m=o||("Windows"==d&&"5.1"==f?l:o)||("Windows"==d&&"5.2"==f?l:o)||("Windows"==d&&"6.0"==f?l:o)||function(a,b,c,e,d,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==d&&a?(d=parseInt(a[1],10),a=parseInt(a[2],10),6<d||6==d&&1<=a):o}(a,c,b,e,d,f,h,i,j,k);return!m?o:function(a,b,c,e,d,f,h){if("MSIE"==a)return(a=/([0-9]+.[0-9]+)/.exec(b))?6<=parseFloat(a[1])&&(h===g||9>h):o}(a,c,b,e,d,f,h,i,j,k)}));
Q(new P("d",function(a,c,b,e,d,f,h){if(!(c=o))b=/^([0-9]+).([0-9]+)/.exec(f),"Windows"==d&&b?(c=parseInt(b[1],10),b=parseInt(b[2],10),c=6<c||6==c&&1<=b):c=o;a=c||("Windows"==d&&"6.0"==f?l:o)?"MSIE"==a?9<=h:g:o;return a}));
Q(new P("a",function(a,c,b,e,d,f,h,i,j,k){var m;m=o||("Windows"==d&&"5.1"==f?l:o)||("Windows"==d&&"5.2"==f?l:o)||("Windows"==d&&"6.0"==f?l:o)||function(a,b,c,e,d,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==d&&a?(d=parseInt(a[1],10),a=parseInt(a[2],10),6<d||6==d&&1<=a):o}(a,c,b,e,d,f,h,i,j,k);return!m&&!("Ubuntu"==d||"Linux"==d?l:o)?o:function(a,b){if("Opera"==a){var c=parseFloat(b);return 10.54<=c&&11.1>c}return o}(a,c,b,e,d,f,h,i,j,k)}));
Q(new P("b",function(a,c,b,e,d,f,h,i,j,k){var m;m=o||function(a,b,c,d,e,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==e&&a?(e=parseInt(a[1],10),f=parseInt(a[3],10),10<e||10==e&&4<=f):"Macintosh"==e&&"Unknown"==f?l:o}(a,c,b,e,d,f,h,i,j,k);return!m?o:function(a,b){if("Opera"==a){var c=parseFloat(b);return 10.54<=c&&11.1>c}return o}(a,c,b,e,d,f,h,i,j,k)}));
Q(new P("d",function(a,c,b,e,d,f,h,i,j,k){var m;m=(m=o||("Windows"==d&&"5.1"==f?l:o)||("Windows"==d&&"5.2"==f?l:o)||("Windows"==d&&"6.0"==f?l:o)||function(a,b,c,e,d,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==d&&a?(d=parseInt(a[1],10),a=parseInt(a[2],10),6<d||6==d&&1<=a):o}(a,c,b,e,d,f,h,i,j,k))||function(a,b,c,d,e,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==e&&a?(e=parseInt(a[1],10),f=parseInt(a[3],10),10<e||10==e&&4<=f):"Macintosh"==e&&"Unknown"==f?l:o}(a,c,b,e,d,f,h,i,j,k);
return!m&&!("Ubuntu"==d||"Linux"==d?l:o)?o:"Opera"==a?11.1<=parseFloat(c):o}));Q(new P("b",function(a,c,b,e,d,f,h,i,j,k){var m;m=o||function(a,b,c,e,d,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==d&&a?(d=parseInt(a[1],10),f=parseInt(a[3],10),10<d||10==d&&4<=f):"Macintosh"==d&&"Unknown"==f?l:o}(a,c,b,e,d,f,h,i,j,k);return!m?o:function(a,b,c,d){return"Safari"==a&&"AppleWebKit"==c&&(a=/([0-9]+.[0-9]+)/.exec(d))?(a=parseFloat(a[1]),525.13<=a&&534.5>a):o}(a,c,b,e,d,f,h,i,j,k)}));
Q(new P("a",function(a,c,b,e,d,f,h,i,j,k){var m;m=o||("Windows"==d&&"5.1"==f?l:o)||("Windows"==d&&"5.2"==f?l:o)||("Windows"==d&&"6.0"==f?l:o)||function(a,b,c,d,e,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==e&&a?(e=parseInt(a[1],10),a=parseInt(a[2],10),6<e||6==e&&1<=a):o}(a,c,b,e,d,f,h,i,j,k);return!m?o:function(a,b,c,e){return"Safari"==a&&"AppleWebKit"==c&&(a=/([0-9]+.[0-9]+)/.exec(e))?(a=parseFloat(a[1]),525.13<=a&&534.5>a):o}(a,c,b,e,d,f,h,i,j,k)}));
Q(new P("d",function(a,c,b,e,d,f,h,i,j,k){var m;m=(m=o||("Windows"==d&&"5.1"==f?l:o)||("Windows"==d&&"5.2"==f?l:o)||("Windows"==d&&"6.0"==f?l:o)||function(a,b,c,e,d,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==d&&a?(d=parseInt(a[1],10),a=parseInt(a[2],10),6<d||6==d&&1<=a):o}(a,c,b,e,d,f,h,i,j,k))||function(a,b,c,d,e,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==e&&a?(e=parseInt(a[1],10),f=parseInt(a[3],10),10<e||10==e&&4<=f):"Macintosh"==e&&"Unknown"==f?l:o}(a,c,b,e,d,f,h,i,j,k);
return!m?o:function(a,b,c,e){return"Safari"==a&&"AppleWebKit"==c&&(a=/([0-9]+.[0-9]+)/.exec(e))?534.5<=parseFloat(a[1]):o}(a,c,b,e,d,f,h,i,j,k)}));
Q(new P("a",function(a,c,b,e,d,f,h,i,j,k){var m;m=(m=(m=o||function(a,b,c,e,d,f,h,i,k,j){a=/([0-9]+).([0-9]+)/.exec(f);return j&&"Android"==d&&a?(d=parseInt(a[1],10),j=parseInt(a[2],10),2==d&&2<=j||3==d&&1>j):o}(a,c,b,e,d,f,h,i,j,k))||function(a,b,c,e,d,f,h,i,j){return j&&"iPad"==d&&(a=/^([0-9]+)_([0-9]+)/.exec(f))?(b=parseInt(a[2],10),4==parseInt(a[1],10)&&2<=b):o}(a,c,b,e,d,f,h,i,j,k))||function(a,b,c,e,d,f,h,i){if(i&&("iPhone"==d||"iPod"==d))if(a=/^([0-9]+)_([0-9]+)/.exec(f))return b=parseInt(a[2],
10),4==parseInt(a[1],10)&&2<=b;return o}(a,c,b,e,d,f,h,i,j,k);return!m?o:"Safari"==a&&"AppleWebKit"==b||"Unknown"==a&&"AppleWebKit"==b&&("iPhone"==d||"iPad"==d)?l:o}));Q(new P("f",function(a,c,b,e,d,f,h,i,j,k){if(!(c=o))f=/([0-9]+).([0-9]+)/.exec(f),k&&"Android"==d&&f?(k=parseInt(f[1],10),f=parseInt(f[2],10),c=3==k&&1<=f||3<k):c=o;return!c?o:"Safari"==a&&"AppleWebKit"==b||"Unknown"==a&&"AppleWebKit"==b&&("iPhone"==d||"iPad"==d)?l:o}));
Q(new P("d",function(a,c,b,e,d,f,h,i,j,k){var m;m=(m=o||function(a,b,c,d,e,f,h,i,j){return j&&"iPad"==e?(a=/^([0-9]+)_([0-9]+)/.exec(f))?5<=parseInt(a[1],10):o:o}(a,c,b,e,d,f,h,i,j,k))||function(a,b,c,e,d,f,h,i){return i&&("iPhone"==d||"iPod"==d)?(a=/^([0-9]+)_([0-9]+)/.exec(f))?5<=parseInt(a[1],10):o:o}(a,c,b,e,d,f,h,i,j,k);return!m?o:"Safari"==a&&"AppleWebKit"==b||"Unknown"==a&&"AppleWebKit"==b&&("iPhone"==d||"iPad"==d)?l:o}));var U=new function(){this.T=[];this.s={}};
Ga(new T("AllFonts",function(a,c){return c}));
Ga(new T("DefaultFourFontsWithSingleFvdFamilies",function(a,c,b){for(var e=0;e<c.length;e++){var d=c[e],f=a.replace(/(-1|-2)$/,"").slice(0,28)+"-"+d;b.push(new ua(f,[d]))}a={};for(d=0;d<c.length;d++)b=c[d],e=b.charAt(1),(a[e]||(a[e]=[])).push(b);b=[[4,3,2,1,5,6,7,8,9],[7,8,9,6,5,4,3,2,1]];e=[];for(d=0;d<b.length;d++)for(var f=b[d],h=0;h<f.length;h++){var i=f[h];if(a[i]){e=e.concat(a[i]);break}}b=e;e={};a=[];for(d=0;d<b.length;d++)f=b[d],e[f]||(e[f]=l,a.push(f));b=[];for(e=0;e<c.length;e++){d=c[e];
for(f=0;f<a.length;f++)h=a[f],h==d&&b.push(h)}return b}));U.s.a="AllFonts";U.s.b="AllFonts";U.s.d="AllFonts";U.s.e="AllFonts";U.s.f="AllFonts";U.s.g="AllFonts";U.s.h="AllFonts";U.s.i="DefaultFourFontsWithSingleFvdFamilies";var X=new function(){this.t={}};X.t.a=[];X.t.b=[];X.t.d=[];X.t.e=[];X.t.f=["observeddomain"];X.t.g=["observeddomain"];X.t.h=["observeddomain"];X.t.i=["observeddomain","fontmask"];window.Typekit||(window.Typekit={});
if(!window.Typekit.load){var Ma=function(a,c){setTimeout(a,c)},Y=new R(new V("//use.typekit.com/{id}.js"),new K(document),document.documentElement,Ma),Z=new S(window,Ma);window.Typekit.load=function(){Y.load.apply(Y,arguments)};window.Typekit.addKit=function(){Y.K.apply(Y,arguments)}}var Na=n,Oa=n,Pa,$,Na=new V("//use.typekit.com/badges/default.gif"),Oa=new Ka(window,document,Na,"https://typekit.com/colophons/yyf0ttn");Pa=new function(){this.$=Oa;this.ma=n};$=new xa(new K(document));$.sa="yyf0ttn";
$.O=new V("//use.typekit.com/k/yyf0ttn-{format}.css?3bb2a6e53c9684ffdc9a9bf4195b2a62ac2abccc2253da0ff4783e9014f8153f8c23c5d70817b18df8ffa1867fda49d841146849609d4e9d40562925a9c6e5aef5949e2fe07859165e8e047abbb8e78e326d1fb3b872e4205a1f78aae25102b45278189860ed32224e29aea0963a171b91dca5878b102838b8b6d2");$.W=Pa;$.m.push(new O("myriad-pro",["n9"]));$.m.push(new O("myriad-pro-condensed",["n3"]));$.m.push(new O("minion-pro-caption",["n4"]));$.B.push(new N([".tk-myriad-pro"],[{name:"font-family",value:'"myriad-pro",sans-serif'}]));
$.B.push(new N([".tk-myriad-pro-condensed"],[{name:"font-family",value:'"myriad-pro-condensed",sans-serif'}]));$.B.push(new N([".tk-minion-pro-caption"],[{name:"font-family",value:'"minion-pro-caption",sans-serif'}]));$.L=wa;$.N=X;$.S=U;Z&&Z.A.__webfonttypekitmodule__?(Z.K($),Z.load()):(ya($,(new aa(navigator.userAgent,document)).parse()),window.Typekit.addKit($));
})(this,document);
window.Typekit.config={"p":"//p.typekit.net/p.gif?s=1&k=yyf0ttn&ht=tk&h={host}&f=6844.6810.6764&a=522719&_={_}"};
/*{"created":"2013-04-11T09:35:38Z","k":"1.5.2"}*/
;(function(window,document,undefined){
function c(a){return function(){return this[a]}}var f=this;function g(a,b){var d=a.split("."),e=f;!(d[0]in e)&&e.execScript&&e.execScript("var "+d[0]);for(var h;d.length&&(h=d.shift());)!d.length&&void 0!==b?e[h]=b:e=e[h]?e[h]:e[h]={}}f.F=!0;function j(a,b,d){this.D=a;this.B=b;this.C=d}g("webfont.BrowserInfo",j);j.prototype.o=c("D");j.prototype.hasWebFontSupport=j.prototype.o;j.prototype.q=c("B");j.prototype.hasWebKitFallbackBug=j.prototype.q;j.prototype.r=c("C");j.prototype.hasWebKitMetricsBug=j.prototype.r;
function k(a,b,d,e,h,q,r,s){this.t=a;this.A=b;this.g=d;this.f=e;this.v=h;this.u=q;this.e=r;this.d=s}g("webfont.UserAgent",k);k.prototype.getName=c("t");k.prototype.getName=k.prototype.getName;k.prototype.n=c("A");k.prototype.getVersion=k.prototype.n;k.prototype.j=c("g");k.prototype.getEngine=k.prototype.j;k.prototype.k=c("f");k.prototype.getEngineVersion=k.prototype.k;k.prototype.l=c("v");k.prototype.getPlatform=k.prototype.l;k.prototype.m=c("u");k.prototype.getPlatformVersion=k.prototype.m;
k.prototype.i=c("e");k.prototype.getDocumentMode=k.prototype.i;k.prototype.h=c("d");k.prototype.getBrowserInfo=k.prototype.h;function l(a,b){this.s=a;this.b=b||a;this.a=document;this.w=void 0}l.prototype=function(a,b){this.s=a;this.b=b||a;this.a=this.b.document;this.w=void 0}.prototype;function m(a){var b=new Image(1,1);b.src=a;b.onload=function(){b.onload=null}}function n(){this.z=window.Typekit.config.p}
function p(a,b,d){var e=d||{};a=a.z.replace(/\{\/?([^*}]*)(\*?)\}/g,function(a,b,d){return d&&e[b]?"/"+e[b].join("/"):e[b]||""});a.match(/^\/\//)&&(a=(b?"https:":"http:")+a);return a.replace(/\/*\?*($|\?)/,"$1")}window.Typekit||(window.Typekit={});var t=new l(window),u=new function(){var a=new n;this.G=null;this.c=a},v=!1;
function w(){if(!v)for(var a=document.getElementsByTagName("link"),b=0;b<a.length;b++){var d=a[b].getAttribute("href");if(d&&0<=d.indexOf("use.typekit")){a=u;b=t;a.c&&(d=(d=window.__adobewebfontsappname__)?d.toString().substr(0,20):"",m(p(a.c,"https:"==b.a.location.protocol,{host:encodeURIComponent(b.a.location.hostname),app:encodeURIComponent(d),_:(+new Date).toString()})));v=!0;break}}}var x=window.Typekit.load;window.Typekit.load=function(){x&&x.apply(window.Typekit,arguments);w()};
window.__webfonttypekitmodule__&&w();
})(this,document);
