({
    baseUrl: "../../",
    paths: {
		'jquery':'common_js/jquery/jquery-1.8.1.min',
		'text':'common_js/requireJS/text',
		'template':'common_js/interaction/template',
		'paperJS':'common_js/paperJS/paper.min',
		'interaction_view':'common_js/interaction/view/main',
		'backbone':'common_js/backbone/backbone-min-0.9.10',
		'underscore':'common_js/backbone/underscore-min-1.4.4',
		'interaction':'common_js/interaction/interaction',
		'interaction_model':'common_js/interaction/model',
		'preview_model':'common_js/interaction/view/model',
		'jquery.nanoscroller':'common_js/jquery_nanoscroller/jquery.nanoscroller.min',
		'greensock':'common_js/greensock',
		'animation':'common_js/interaction/animation_transform',
		'TimelineMax':'common_js/greensock/TimelineMax.min',
		'TweenMax':'common_js/greensock/TweenMax',
		'buzz':'common_js/buzz/buzz',
		'videojs':'common_js/videojs/video.min',
		'jqueryui':'common_js/jquery/ui/minified/jquery-ui.min',
		'bootstrap':'common_js/bootstrap/bootstrap.min',
		'interaction_main':'common_js/interaction/interaction_main',
		'globalJS':'app/js/global/globalJS',
		'filter':'app/js/web/filter/filter',
		'material':'app/js/web/material/material',
		'category':'app/js/web/category/category',
		'upload':'app/js/web/upload/upload',
		'tEditor':'app/js/web/tEditor/tEditor',
		'jqwait':'common_js/jqwait/jqwait',
		'quickupload':'common_js/quickupload',
		'jswait':'common_js/jswait/jswait',
		'revealJS':'common_js/revealjs/js/reveal.min',
		'templatePage':'common_js/interaction/templatepage',
		'classList':'common_js/revealjs/lib/js/classList',
		'preview_data':'app/js/web/interaction/data/preview',
	},
    name: "app/js/web/interaction/preview",
    out: "preview-build.js"
})