function get_progress_data(id,callback){
	var ret = {
		"content_trs":[
			{
				"classname":"progress-started",
				"status":"完成",
				"id":1,
				"title":"进行中的主项目",
				"operationalitems":[
					{
						"enabled":0,
						"id":"active",
						"name":"启动"
					},
					{
						"enabled":1,
						"id":"close",
						"name":"关闭"
					}
				],
				"planEnd":"2012-05-15",
				"planStart":"2012-01-20",
				"editable":1,
				"progress":55,
				"roles":{
					"外审":"user",
					"审批":"user1"
				},
				"points":"学习重点",
				"references":"参考内容",
				"left":5,
				"WRITING_TYPE":"LXH"
			},
			{
				"classname":"progress-closed",
				"status":"完成",
				"id":2,
				"title":"进行中的主项目",
				"operationalitems":[
					{
						"enabled":0,
						"id":"active",
						"name":"启动"
					},
					{
						"enabled":1,
						"id":"close",
						"name":"关闭"
					}
				],
				"planEnd":"2012-05-15",
				"planStart":"2012-01-20",
				"editable":0,
				"progress":55,
				"roles":{
					"外审":"user",
					"审批":"user1"
				},
				"points":"学习重点",
				"references":"参考内容",
				"left":5,
				"WRITING_TYPE":"LXH"
			},
			{
				"classname":"progress-done",
				"status":"完成",
				"id":3,
				"title":"进行中的主项目",
				"operationalitems":[
					{
						"enabled":0,
						"id":"active",
						"name":"启动"
					},
					{
						"enabled":1,
						"id":"close",
						"name":"关闭"
					}
				],
				"planEnd":"2012-05-15",
				"planStart":"2012-01-20",
				"editable":1,
				"progress":55,
				"roles":{
					"外审":"user",
					"审批":"user1"
				},
				"points":"学习重点",
				"references":"参考内容",
				"left":5,
				"WRITING_TYPE":"LXH"
			}
		]
	}
	callback(ret);
}
function get_project_data(callback){
	var ret = {
		"content_num":27,
		"project_num":3,
		"project_lis":[
			{
				"classname":"project-started",
				"id":1,
				"title":"1.进行中的主项目",
				"demand":"Please write the book using S1000D specification",
				"editable":0,
				"operationalitems":[
					{
						"enabled":0,
						"id":"submit_review",
						"name":"提交审核"
					},
					{
						"enabled":1,
						"id":"submit_publish",
						"name":"提交发布"
					}	
				],
				"roles":{
					"外审":"user",
					"审批":"user1"
				}
					
			},
			{
				"classname":"project-closed",
				"id":2,
				"title":"2.进行中的主项目",
				"demand":"Please write the book using S1000D specification",
				"editable":1,
				"operationalitems":[
					{
						"enabled":0,
						"id":"submit_review",
						"name":"提交审核"
					},
					{
						"enabled":1,
						"id":"submit_publish",
						"name":"提交发布"
					}
				],
				"roles":{
					"外审":"user",
					"审批":"user1"
				}
					
			},
			{
				"classname":"project-done",
				"id":3,
				"title":"3.进行中的主项目",
				"demand":"Please write the book using S1000D specification",
				"editable":1,
				"operationalitems":[
					{
						"enabled":0,
						"id":"submit_review",
						"name":"提交审核"
					},
					{
						"enabled":1,
						"id":"submit_publish",
						"name":"提交发布"
					}
				],
				"roles":{
					"外审":"user",
					"审批":"user1"
				}
					
			}
		]
	}
	callback(ret);
}
$(function(){
	var gPMLAPP = new PMLAPP({
		/*
		*依赖的模块
		*/
		dependents:{
			/*
			*模块名称
			*/
			'List_project':{
				/*
				*模块初始化需要的参数
				*/
				options:{
					/*
					*获取项目数据
					*/
					get_project_data:function(callback){
						get_project_data(callback);
					}
				}

			},
			/*
			*模块名称
			*/
			'List_content':{
				
				/*
				*模块初始化需要的参数
				*/
				options:{
					/*
					*获取子项目数据
					*/
					get_progress_data:function(id,callback){
						get_progress_data(id,callback);
					}
				}

			},
			/*
			*模块名称
			*/
			'List_detail':{

				/*
				*模块初始化需要的参数
				*/
				options:{
					/*
					*项目编制说明
					*/
					projectDes:function(opt){
						alert('项目编制说明')
					},
					/*
					*项目任务管理
					*/
					projectTask:function(opt){
						alert('项目任务管理')
					},
					
					/*
					*子项目任务管理
					*/
					contentTask:function(opt){
						alert('子项目任务管理')
					}
						
				}

			},
			/*
			*模块名称
			*/
			'List_menu':{
				
				/*
				*模块初始化需要的参数
				*/
				options:{
					/*
					*项目组成员设置
					*/
					projectGroup:function(opt){alert('项目组成员设置')},
					/*
					*启动选中子项目
					*/
					startupProject:function(opt){alert('启动选中子项目')}
				}

			}
		}
	});
	
})