global.template.process_info=
    [
'    <div class="mod info-mod related-info baseinfo" data-model="process" data-id="process_info" id="<%=id%>">',
'      <div class="mod-hd">专题信息</div>',
'      <div class="mod-bd">',
'        <dl>',
'          <dt>名称</dt>',
'          <dd>',
'            <p id="title"><%if (typeof title != undefined){%><%=title%><%}%></p>',
'        </dl>',
'        <dl class="task-management">',
'          <dt style="position:relative; line-height:30px;">任务管理',
'            <%if(editable){%><button class="btn btn-small action-modal" data-attr="roles" type="button" style="position:absolute; top:3px; right:10px;"><i class="icon-edit"></i> 编辑</button><%}%>',
'          </dt>',
'          <dd>',
'            <ul>',
'              <li><span class="alignleft">开始时间：</span><span class="alignright"><%if (typeof planStart != undefined){%><%=planStart%><%}%></span></li>',
'              <li><span class="alignleft">结束时间：</span><span class="alignright"><%if (typeof planEnd != undefined){%><%=planEnd%><%}%></span></li>',
'              <li><span class="alignleft"><%=global.dict.query("writing")%>：</span><span class="alignright"><%if (typeof roles[0]["writing"] != undefined){%><%=roles[0]["writing"]%><%}%></span></li>',
'              <li><span class="alignleft"><%=global.dict.query("proof")%>：</span><span class="alignright"><%if (typeof roles[1]["proof"] != undefined){%><%=roles[1]["proof"]%><%}%></span></li>',
'              <li><span class="alignleft"><%=global.dict.query("sreview")%>：</span><span class="alignright"><%if (typeof roles[2]["sreview"] != undefined){%><%=roles[2]["sreview"]%><%}%></span></li>',
'              <li><span class="alignleft"><%=global.dict.query("sreview1")%>：</span><span class="alignright"><%if (typeof roles[3]["sreview1"] != undefined){%><%=roles[3]["sreview1"]%><%}%></span></li>',
'              <li><span class="alignleft"><%=global.dict.query("sreview2")%>：</span><span class="alignright"><%if (typeof roles[4]["sreview2"] != undefined){%><%=roles[4]["sreview2"]%><%}%></span></li>',
'            </ul>',
'          </dd>',
'        </dl>',
'      </div>',
'    </div>'
    ].join("")
